### ISSUE TITLE
打开页面的时候报以下错误

### ISSUE THREAD

**Issue by rhkjyn** [smartloli/kafka-eagle#10]
HTTP Status 500 - Servlet.init() for servlet SpringMvc threw exception

type Exception report

message Servlet.init() for servlet SpringMvc threw exception

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.servlet.ServletException: Servlet.init() for servlet SpringMvc threw exception
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
root cause

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mappingJacksonHttpMessageConverter' defined in class path resource [spring-mvc.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.SerializationConfig
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1101)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:663)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:629)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:677)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:548)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:489)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
root cause

org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter]: Constructor threw exception; nested exception is java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.SerializationConfig
	org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1094)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:663)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:629)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:677)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:548)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:489)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.lang.Thread.run(Thread.java:745)
root cause

java.lang.NoClassDefFoundError: Could not initialize class com.fasterxml.jackson.databind.SerializationConfig
	com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:558)
	com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:474)
	org.springframework.http.converter.json.Jackson2ObjectMapperBuilder.build(Jackson2ObjectMapperBuilder.java:521)
	org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.<init>(MappingJackson2HttpMessageConverter.java:56)
	sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1094)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:663)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:629)
	org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:677)
	org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:548)
	org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:489)
	org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	javax.servlet.GenericServlet.init(GenericServlet.java:158)
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:522)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:1110)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:785)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1425)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

**Comment by zmwxiaoming** [comment]
我也是报这个错误,有没有老版本的啊,不知道新版本的咋回事

**Comment by smartloli** [comment]
@rhkjyn @zmwxiaoming It should be the configuration file that initializes the conflict. Download address [http://download.smartloli.org/](http://download.smartloli.org/) . Running through environment :

- JDK 1.7+ (Recommend 1.8)
- Copy ,Delete,Decompression (Current User Owner)
- Configuration requires reference [Kafka Eagle Manual](https://ke.smartloli.org/2.Install/2.Installing.html)

Finally, if there are problems, you can describe the steps you started, and good luck.

**Comment by zmwxiaoming** [comment]
我的jdk1.8.0_111符合要求,都是按照文档步骤来的,
1.
vi /etc/profile
export KE_HOME=/home/hadoop/kafka-eagle
![kafkaeagle](https://user-images.githubusercontent.com/8034998/27064342-79bfe330-5029-11e7-97a2-5eb97084b36e.jpg)

export PATH=$PATH:$KE_HOME/bin
2.
[hadoop@Master conf]$ ls
jdbc.properties  log4j.properties  offsets-quartz.xml  shiro-ehcache.xml  spring-mvc.xml  spring-mybatis.xml  spring-shiro.xml  system-config.properties
3.
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://127.0.0.1:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=hive
4.
[hadoop@Master conf]$ vi system-config.properties 
![kafkaeagle](https://user-images.githubusercontent.com/8034998/27064349-82dc816c-5029-11e7-9061-c28ff5ddf88f.jpg)

**Comment by rhkjyn** [comment]
经测试是linux版本问题，如果用centos6就OK

**Comment by jianxp** [comment]
@rhkjyn  我的是centos6.5的系统，也和你报错一样的。

**Comment by AlvinYang-2017** [comment]
@rhkjyn 哥们 这个错误是操作系统的问题？还是哪里的配置需要调整？

**Comment by jianxp** [comment]
很高兴，自己已经解决这个问题了。下载源码修改kafka-eagle-web\pom文件中的jackson-databind和jackson-core版本，重新编译就解决了。

**Comment by z11220857** [comment]
@jianxp 具体怎么修改？

**Comment by z11220857** [comment]
@rhkjyn @zmwxiaoming 后来你们解决了么？

**Comment by littlejiangyuan** [comment]
哎，看了有些人解决了也不详细说一下解决方法，我来说一下吧，对于不太熟java，不了解spring的我花了好久才解决这个问题。
1.下载源码，使用intelli idea(使用maven方式)打开源码，会发现
<img width="462" alt="65b51dd4-dc21-4679-bb7a-fe115d53feb7" src="https://user-images.githubusercontent.com/6269604/30807911-6d90c2f8-a22e-11e7-9035-fac211cba0fb.png">
说明jackson-core和jackson-databind中都有一个重复版本。把2.1.1版本拷贝出来，一会使用。
2.第一次按照教程运行程序，在浏览器输入ip:port/ke。如果没有问题，恭喜你，如果出现该issue，那么就走后面流程。
3.打开ke.sh，注释掉以下几行代码（在每行前面加个#，或者删除代码）
rm -rf $KE_HOME/kms/webapps/ke
rm -rf $KE_HOME/kms/work
mkdir -p $KE_HOME/kms/webapps/ke
cd $KE_HOME/kms/webapps/ke
${JAVA_HOME}/bin/jar -xvf $KE_HOME/kms/webapps/ke.war
4.进入目录kms/webapps/ke/WEB-INF/lib，把第一步中的两个文件拷贝进来，同时把版本2.8.7的两个文件删掉。
5.再次运行ke.sh，应该就可以了。
对于为啥会出现步骤1那种情况，不知道是不是作者的一个小bug，可能跟其他库重复引入了，是的话希望作者从源码解决一下。当然感谢作者提供这么好的工具！

**Comment by lbx6z** [comment]
折腾了很久，来记录一下。
环境：ubuntu16.04, kafka-eagle-1.3.8
解决方案：修改源码 kafka-eagle-web/pom.xml，把 jackson.version 版本由 2.9.6 改为 2.4.5，重新编译一下即可。
```
<properties>
   ...
   <jackson.version>2.9.6</jackson.version>
</properties>
```
```
<properties>
   ...
   <jackson.version>2.4.5</jackson.version>
</properties>
```

下面描述一些经过。。

1、 一开始参考 littlejiangyuan，我查看了 kms/webapps/ke/WEB-INF/lib 下 jackson 相关的包
```
> ls kms/webapps/ke/WEB-INF/lib/*jackson*
kms/webapps/ke/WEB-INF/lib/jackson-annotations-2.9.0.jar
kms/webapps/ke/WEB-INF/lib/jackson-core-2.9.6.jar
kms/webapps/ke/WEB-INF/lib/jackson-databind-2.9.6.jar
```
发现 jackson-annotations 版本和其他两个包不一致，以为会有问题，于是在 kafka-eagle-web/pom.xml 里加上了
```
<dependencies>
 ...
     <dependency>
          <groupId>com.fasterxml.jackson.core</groupId>
          <artifactId>jackson-annotations</artifactId>
          <version>${jackson.version}</version>
     </dependency>
</dependencies>
```
结果，jackson-annotations 版本变成了 2.9.6，但还是报 500。

2、从报错信息可知，应该是 spring-core 和 jackson 版本不一致所致（没有保留报错信息，如需要，后续可以复现一下）。问题是应该改成什么版本呢？

2.1 同样参考 littlejiangyuan，TA 用的是 2.8.7，于是我把 jackson.version 改成 2.8.7，但还是报错。

2.2 从 kafka-eagle-web/pom.xml 可知，spring.version 是 4.1.6.RELEASE，到 https://github.com/spring-projects/spring-framework/blob/v4.1.6.RELEASE/build.gradle 这里一查，当时他们编译 spring 用的 jackson 版本是 `ext.jackson2Version      = "2.4.5"`
最后把 jackson.version 版本由 2.9.6 改为 2.4.5 果然正常了。

另外，测试了一下，jackson-annotations 和 其他两个 jackson 包 版本不一致，不会有影响（也就是第1步可以不做）。

**Comment by dingdingding-0515** [comment]
看了一下没有我的解决方法，提供给大家参考一下（系统：centos7，版本：kafka-eagle-bin-1.2.4.tar.gz ）。
第一步：停止Bootstrap进程
kill -9 Bootstrap进程号
第二步：修改bin/ke.sh文件
注释以下四行：（在前面加上#即可）
 rm -rf $KE_HOME/kms/webapps/ke
rm -rf $KE_HOME/kms/work
 mkdir -p $KE_HOME/kms/webapps/ke
cd $KE_HOME/kms/webapps/ke
${JAVA_HOME}/bin/jar -xvf $KE_HOME/kms/webapps/ke.war
第三步：修改conf/system-config.properties文件，使用自带的数据库（我觉得我的错误可能就是使用了自己安装的MySQL数据库，导致版本不兼容）
kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/home/***/eagle/db/ke.db （安装包下的db文件夹，若没有ke数据库会新建）
kafka.eagle.username=root
kafka.eagle.password=123456
第四步：启动Kafka eagle
