### ISSUE TITLE
kafka-eagle的consumer监控识别不出flink程序中起的kafka consumer

### ISSUE THREAD

**Issue by ZhiXingHeYiApple** [smartloli/kafka-eagle#101]
我使用flink1.6的flink-connector-kafka-0.11_2.11连接器来连接kafka进行消费，当程序执行时，kafka-eagle的consumer监控识别不出来flink流任务中的kafka consumer，这个具体是什么原因引起的呢？

**Comment by smartloli** [comment]
fixed by [kafka-eagle-v1.2.9](https://github.com/smartloli/kafka-eagle-bin/archive/v1.2.9.tar.gz)
