### ISSUE TITLE
好像还不支持kafka-2.11，Consumers Offsets 功能无法使用

### ISSUE THREAD

**Issue by celesky** [smartloli/kafka-eagle#103]
好像还不支持kafka-2.11，Consumers Offsets 功能无法使用，作者有计划支持一下么

**Comment by smartloli** [comment]
Now (Oct 18, 2018), Kakfa version is 2.0 , The 2.11 is the version number of Scala, not the version number of Kafka. Please provide the actual version number. Such as
```
 kafka_2.11-2.0.0.tgz
```

**Comment by cocodroid** [comment]
@celesky 使用Windows会出现这样吗？你可以试下Linux下
