### ISSUE TITLE
kafka eagle 无法查看消费组消息

### ISSUE THREAD

**Issue by sushicai** [smartloli/kafka-eagle#104]
我现在使用kafka单机 下载了eagle并安装提供文档配置好了。所有功能都能正常使用！唯独查看消费组 running时 一直在加载中 显示不了 信息 是什么情况 有人能解答一下吗

**Comment by smartloli** [comment]
1. kafka version ?
2. use kafka api (new or old)
3. Reference blog [Kafka Eagle Install](https://www.cnblogs.com/smartloli/p/9371904.html)
