### ISSUE TITLE
设置alarm后，无法发送邮件

### ISSUE THREAD

**Issue by dongjunjie** [smartloli/kafka-eagle#105]
my config:
![image](https://user-images.githubusercontent.com/10395782/47331937-45e4a280-d6b0-11e8-92c8-c8c58c54e819.png)

alerm config:
![image](https://user-images.githubusercontent.com/10395782/47331899-2cdbf180-d6b0-11e8-88da-bcf239641ca3.png)

my lag:
![image](https://user-images.githubusercontent.com/10395782/47331968-67458e80-d6b0-11e8-8bbb-d94a3f03936b.png)

But i can't recieve the e-mail. What's wrong?

**Comment by dongjunjie** [comment]
无用是用邮箱的原始密码，还是smtp授权码密码，都无法收到邮件。

而且日志里面也没有报相关错误，求指导

**Comment by smartloli** [comment]
If you use 126 email , you must be open ```smtp.126.com``` protocol & enable.
