### ISSUE TITLE
页面无法打开

### ISSUE THREAD

**Issue by boking** [smartloli/kafka-eagle#106]
安装完成之后启动成功，然后打开页面，输入账号密码之后开始报错，无法显示页面
error.log 里面直接 
KafkaOffsetGetter.Thread-58 - ERROR - Get consumer records has error, msg is Error reading field 'metadata': String length -17083 cannot be negative
刷屏
使用的mysql存储
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://172.16.13.47:3550/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=test
kafka.eagle.password=test@1234+1s

**Comment by boking** [comment]
> @boking What version of Kafka are you using?

**Comment by smartloli** [comment]
[Kafka Eagle Install Blog](https://www.cnblogs.com/smartloli/p/9371904.html)
