### ISSUE TITLE
启动Kafka-eagle-bin1.2.4 提示The JAVA_HOME environment variable is not defined correctly.

### ISSUE THREAD

**Issue by dawsongzhao** [smartloli/kafka-eagle#111]
问题：启动Kafka-eagle-bin1.2.4 提示The JAVA_HOME environment variable is not defined correctly.
配置：
1、vi /etc/profile
JAVA_HOME=/usr/java/jdk1.8  
export PATH=$PATH:$JAVA_HOME
2、source /etc/profile 执行后shell终端echo $JAVA_HOME以及java -version都有正确输出
3、启动./ke.sh 报错The JAVA_HOME environment variable is not defined correctly.

解决：shell终端echo $JAVA_HOME以及java -version都有正确输出；ke.sh脚本中JAVA_HOME却无法获取值；原因在于/etc/profile中没有export JAVA_HOME这个问题太隐蔽了 可否建议启动脚本中 直接判断java是否安装呢？如if type -p java; then xxx fi

**Comment by cocodroid** [comment]
@dawsongzhao please see the document : https://ke.smartloli.org/2.Install/1.Env.html
