### ISSUE TITLE
当使用kafka提供内网+外网消费时，默认zookeeper暴露外网ip；metrics功能不可用

### ISSUE THREAD

**Issue by dawsongzhao** [smartloli/kafka-eagle#112]
当使用kafka提供内网+外网消费时，默认zookeeper暴露外网ip；
kafka jmx端口9999 没有通过防火墙nat映射出去，这种组网有两个问题：
1、内网kafka地址和端口 eagle无法监控
2、metrics功能不可用

**Comment by cocodroid** [comment]
@dawsongzhao I don't know what you mean. Can you describe it more clearly? Please solve the network access problem yourself.

**Comment by smartloli** [comment]
@dawsongzhao
