### ISSUE TITLE
从zookeeper上获取不到kafka信息

### ISSUE THREAD

**Issue by Junyewu** [smartloli/kafka-eagle#113]
日志报错：
KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-1 - ERROR - Get kafka consumer has error,msg is No resolvable bootstrap urls given in bootstrap.servers

已在kafka-server-start.sh中增加JMX配置，并重启生效:
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms4G -Xmx4G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
fi

kafka版本0.11.0.1
zookeeper版本为kafka中自带的zookeeper-3.4.10.jar

是否存在兼容性问题，导致获取zookeeper上kafka信息异常？

**Comment by Junyewu** [comment]
system-config.properties：
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=es1:2181,es2:2181,es3:2181
kafka.zk.limit.size=25
kafka.eagle.webui.port=8048
cluster1.kafka.eagle.offset.storage=kafka
kafka.eagle.metrics.charts=true
kafka.eagle.mail.enable=flase
kafka.eagle.mail.sa=alert_sa
kafka.eagle.mail.username=alert_sa@163.com
kafka.eagle.mail.password=mqslimczkdqabbbh
kafka.eagle.mail.server.host=smtp.163.com
kafka.eagle.mail.server.port=25
kafka.eagle.topic.token=keadmin
kafka.eagle.sasl.enable=false
kafka.eagle.sasl.protocol=SASL_PLAINTEXT
kafka.eagle.sasl.mechanism=PLAIN
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://es2:3306/kedb?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=ke
kafka.eagle.password=KE123qaz!

**Comment by Junyewu** [comment]
有没有可能是zookeeper路径获取的问题？kafka集群在zookeeper上是/kafka/broker……
但是KafkaServiceImpl.java和引用的ZkUtils.scala中缺少了/kafka这层路径。
KafkaServiceImpl code：
	private final String BROKER_IDS_PATH = "/brokers/ids";
	private final String BROKER_TOPICS_PATH = "/brokers/topics";
	private final String CONSUMERS_PATH = "/consumers";
	private final String TOPIC_ISR = "/brokers/topics/%s/partitions/%s/state";

ZkUtils code：
object ZkUtils {
  val ConsumersPath = "/consumers"
  val ClusterIdPath = "/cluster/id"
  val BrokerIdsPath = "/brokers/ids"
  val BrokerTopicsPath = "/brokers/topics"
  val ControllerPath = "/controller"
  val ControllerEpochPath = "/controller_epoch"
  val ReassignPartitionsPath = "/admin/reassign_partitions"
……

**Comment by Junyewu** [comment]
问题已解决，在配置中指定/kafka为root父级节点，即可读取zookeeper上kafka信息
cluster1.zk.list=es1:2181,es2:2181,es3:2181/kafka

**Comment by cocodroid** [comment]
ok
