### ISSUE TITLE
Consumers Offsets details 超时

### ISSUE THREAD

**Issue by hao117** [smartloli/kafka-eagle#114]
JMX service url[192.168.1.24:9993] create has error,msg is Connection refused to host: 172.22.0.2; nested exception is: 
	java.net.ConnectException: Connection timed out: connect

kafka版本：2.11_0.10.0.1
offset存储方式：kafka
kafka使用docker容器部署的
为什么host变172.22.0.2了？但使用kafka-manager可以查看到消费offset

**Comment by smartloli** [comment]
@hao117 Because your metadata is stored in Zookeeper's kafka broker address is this.
