### ISSUE TITLE
监控1.0以上的kafka 获取不到 消费者信息

### ISSUE THREAD

**Issue by zsjohny** [smartloli/kafka-eagle#115]
1.2.6 版本 
![image](https://user-images.githubusercontent.com/8543865/49723655-4954dd00-fca2-11e8-935f-a2173636c7f4.png)

**Comment by libaidian** [comment]
我用 kafka_2.11-2.1.0 ，kafka-eagle-1.2.6版本也是没有消费者信息，求指导

**Comment by smartloli** [comment]
Maybe you can read this blog. [Kafka Eagle Install QA](https://www.cnblogs.com/smartloli/p/9371904.html)

**Comment by zsjohny** [comment]
> Maybe you can read this blog. [Kafka Eagle Install QA](https://www.cnblogs.com/smartloli/p/9371904.html)

改过之后也是一样，这个结果就改过之后的 只有这里面的不正常其他存储到kafka 的都是正常的

**Comment by smartloli** [comment]
What information is printed in the log?

**Comment by smartloli** [comment]
@All Fixed consumer offset kafka-2.1.0 by [Kafka Eagle V1.2.7](http://download.smartloli.org/)
