### ISSUE TITLE
1.2.6 角色设置也有问题 没有alarm 集群里面的角色授权

### ISSUE THREAD

**Issue by zsjohny** [smartloli/kafka-eagle#116]
![image](https://user-images.githubusercontent.com/8543865/49723691-6a1d3280-fca2-11e8-8abd-07c9008e1535.png)

**Comment by smartloli** [comment]
@zsjohny you need to update database , have this function in v1.2.6
![image](https://user-images.githubusercontent.com/16030669/50261187-5a41e300-0446-11e9-8ed6-e311eb546f71.png)
