### ISSUE TITLE
登陆账号权限控制

### ISSUE THREAD

**Issue by f-zhao** [smartloli/kafka-eagle#12]
新版本中权限控制需要通过数据库，但是在不同的系统中，一般使用SSO进行统一登陆，新版这样的设计是否显得多余？

**Comment by smartloli** [comment]
@f-zhao Thank you very much for your feedback. But what do you mean? Is there anything wrong with it ?

**Comment by f-zhao** [comment]
我的意思是，一般监控系统都会接入到各个公司的统一登录平台SSO，实现账户管理等，目前ke里面自己实现了一套登录账号认证等功能，感觉上来说，如果需要自己实现接入各个公司的登录，就需要将现有的登录代码删除，所以现有的登录显得有些多余。个人意见，仅供参考。

**Comment by zoumm** [comment]
啦啦啦

**Comment by smartloli** [comment]
@f-zhao That's a good suggestion, but the monitoring system is independent, such as [Ambari](https://github.com/apache/ambari) (Hadoop management platform), [Azkaban](https://github.com/azkaban/azkaban) scheduling system and so on, all of which are independent privileges, and have nothing to do with the business level.
