### ISSUE TITLE
 Quartz statistics offset haserror,msg is null

### ISSUE THREAD

**Issue by zhouhoo** [smartloli/kafka-eagle#120]
kafka-eagle 1.2.6
centos 7.2

set up and config as doc says, but still get error : `OffsetsQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-2 - ERROR - Quartz statistics offset haserror,msg is null`

the kafka and zookeeper is working well .
beside, when I add topic alarm, after clicking the `add` button, there  was a failure with no response !!!!

**Comment by smartloli** [comment]
@zhouhoo Hi, What is the kafka version number you use?

**Comment by zhouhoo** [comment]
kafka is 0.11 version，sorry so late
