### ISSUE TITLE
kafka 1.0 没有数据 消费者告警都能正常触发

### ISSUE THREAD

**Issue by zsjohny** [smartloli/kafka-eagle#121]
![image](https://user-images.githubusercontent.com/8543865/50419694-10edfb00-086d-11e9-98e4-477440a0adb0.png)

![image](https://user-images.githubusercontent.com/8543865/50419724-4266c680-086d-11e9-812c-7e69f14bcd72.png)

**Comment by smartloli** [comment]
@duhanmin 
You can use [v1.2.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.2.8.tar.gz)
Query topic like this:

```sql
select * from "KV_T" where "partition" in (0) limit 1
```
![image](https://user-images.githubusercontent.com/16030669/50573868-25a33380-0e17-11e9-950c-782a986d2ec8.png)

**Comment by duhanmin** [comment]
> @duhanmin
> 您可以 像这样使用[v1.2.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.2.8.tar.gz)
> 查询主题：
> 
> ```sql
> 选择 *  从 “ KV_T ” 哪里 “分区” 在（0）限制 1
> ```
> 
> ![图片](https://user-images.githubusercontent.com/16030669/50573868-25a33380-0e17-11e9-950c-782a986d2ec8.png)



表示无法查询大写Topic，当我去查询大写Topic的时候什么也查询不到，而且它会自己创建一个小写的Topic
``

**Comment by smartloli** [comment]
@duhanmin 
Check you query sql in kafka eagle log, also you can try set ```kafka.eagle.sql.fix.error=true```.

**Comment by duhanmin** [comment]
> @duhanmin
> 检查你在kafka eagle日志中查询sql，也可以尝试设置`kafka.eagle.sql.fix.error=true`。

日志中依旧是小写，那个参数也已经配置，没有效果

**Comment by duhanmin** [comment]
查询sql: SELECT "partition","offset","msg" FROM "DUDU" WHERE "partition" IN (0,1,2) limit 10
日志：[2019-01-04 11:46:26] KafkaSqlParser.http-nio-19527-exec-9 - INFO  - KafkaSqlParser - SQL[select "partition","offset","msg" from "dudu" where "partition" in (0,1,2) limit 10]

**Comment by duhanmin** [comment]
问题已经通过修改代码解决
删除 toLowerCase();
但是日志中一直有警告@smartloli 
WARN  - Session 0x0 for server master.fulin.com/172.16.245.38:2181, unexpected error, closing socket connection and attempting reconnect
 java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1141)
