### ISSUE TITLE
Kafka Eagle查询大写Topic异常

### ISSUE THREAD

**Issue by duhanmin** [smartloli/kafka-eagle#123]
在使用kafka-eagle中发现，sql查询大写Topic找不到数据，并且会自己创建一个小写的Topic，也就是说kafka-eagle默认都是小写，但是kafka是对大小写敏感的

**Comment by duhanmin** [comment]
查不到，且会自己创建一个小写的Topic

**Comment by smartloli** [comment]
@duhanmin 
Read  #121
