### ISSUE TITLE
kafka 2.1.0 不兼容

### ISSUE THREAD

**Issue by Barbazoo** [smartloli/kafka-eagle#124]
本地用的wurstmeister/kafka:2.12-2.1.0镜像，查看offset时会出现图示的情况
![1546497847753](https://user-images.githubusercontent.com/38100427/50625921-1c74ac80-0f66-11e9-86c0-3d49a8c22434.jpg)

![image](https://user-images.githubusercontent.com/38100427/50625932-3b733e80-0f66-11e9-9a5a-1a68a8e0bd90.png)

**Comment by smartloli** [comment]
@Barbazoo 
Hi,
If you are using a ```kafka eagle version``` other than ```v1.2.8```, please upgrade to that version.
Read Manual:
[Install Kafka Eagle](https://ke.smartloli.org/2.Install/2.Installing.html)
[Kafka Eagle Blog](https://www.cnblogs.com/smartloli/p/9371904.html)
