### ISSUE TITLE
kafka_2.11-0.10.2.0不兼容

### ISSUE THREAD

**Issue by zoush2016** [smartloli/kafka-eagle#126]
使用 kafka_2.11-0.10.2.0版本时，在Tipic List页面一直显示“Processing......”，我使用的是最新版kafak-eagle-1.2.8,文档里写是支持0.10.x版本的kafka。

**Comment by smartloli** [comment]
@zoush2016 
Hi,
Read Manual:
[Install Kafka Eagle](https://ke.smartloli.org/2.Install/2.Installing.html)
[Kafka Eagle Blog](https://www.cnblogs.com/smartloli/p/9371904.html)

Anyway, you can also read ```kafka-eagle``` logs information.
