### ISSUE TITLE
源码打包后,kms下无logs文件夹,启动失败.

### ISSUE THREAD

**Issue by ilaotan** [smartloli/kafka-eagle#130]
如题. 官网下载的,kms下有logs文件夹,但源码里没有.

**Comment by ilaotan** [comment]
另外,我源码直接打包失败,必须使用
`<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.7.0</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>`

**Comment by smartloli** [comment]
@ilaotan 
* kms/logs in gitignore file, adjusted filtering strategy.
* Maven default use ```jdk1.5```, If you have not set up the ```Maven JDK``` version, you will need to edit the pom file.

**Comment by ilaotan** [comment]
touch: cannot touch ‘/root/test/kafka-eagle-web-1.2.8/kms/logs/catalina.out’: No such file or directory
/root/test/kafka-eagle-web-1.2.8/kms/bin/catalina.sh: line 434: /root/test/kafka-eagle-web-1.2.8/kms/logs/catalina.out: No such file or directory

@smartloli

**Comment by smartloli** [comment]
@ilaotan 
You must update lastest code, and rebuild code.
Master branch:
https://github.com/smartloli/kafka-eagle/tree/master/kafka-eagle-web/src/main/resources/kms
