### ISSUE TITLE
Support for non Java based clients

### ISSUE THREAD

**Issue by mohigup** [smartloli/kafka-eagle#14]
I have tried kafka-consumer-groups.sh and see that it doesn't support non java based clients (producer, consumer). Does the project support clients written in go?

Versions

Kafka Version: 0.10.2.1
Go Version: 1.8

**Comment by smartloli** [comment]
@mohigup I haven't tested the Go programming language, so I'm sorry I can't give you a positive answer.

**Comment by mohigup** [comment]
Thanks for the Reply.
