### ISSUE TITLE
Active Topics 展示不出来

### ISSUE THREAD

**Issue by navyaijm2017** [smartloli/kafka-eagle#15]
你好，我跟着文档把环境搭建起来之后，发现Consumers这个tab的内容展示不出来，查看日志报错如下：

2017-07-08 15:04:07 ERROR [KafkaServiceImpl.http-nio-8048-exec-19] - Get kafka consumer has error,msg is Request METADATA failed on brokers List(ip-172-31-4-53:9092 (id: -3 rack: null), ip-172-31-4-54:9092 (id: -2 rack: null), ip-172-31-4-55:9092 (id: -1 rack: null))

**Comment by smartloli** [comment]
@navyaijm2017 Maybe something wrong with the basic setup/configuration. Try the shell script that comes with kafka:
```bash
kafka-consumer-groups --new-consumer --bootstrap-server dn1:9092,dn2:9092,dn3:9092 --list
```
OR
```bash
./kafka-console-consumer.sh --bootstrap-server dn1:9092,dn2:9092,dn3:9092 --topic es_client_error --from-beginning
```
Will the same error occur? If the same error occurs, check your cluster configuration information.

**Comment by lsyarn** [comment]
I got the same problem. When I run 
`bin/kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic test --from-beginning --consumer.config config/consumer.properties` , everything is ok. Should I tell KE use the `conumer.properties` file, and how?

**Comment by smartloli** [comment]
@lsyarn If you use ```kafka-console-consumer.sh``` script run consumer application,  the consumer offsets information will be stored in Zookeeper.
You can set ```$KE_HOME/conf/system.properties``` file, such as 
```
# Disabled the attribute or set value zookeeper
# kafka.eagle.offset.storage=zookeeper
```

**Comment by Jedore** [comment]
3.0.1 也遇到这个问题了， 日志没有报错，但是无法展示 消费组的 Active Topics 和 主题的 TOPIC CONSUMER GROUPS
