### ISSUE TITLE
kafka-eagle SASL 兼容问题

### ISSUE THREAD

**Issue by adminops** [smartloli/kafka-eagle#151]
A套kafka集群开启了sasl认证，B套kafka集群没有开启认证。

kafka-eagle-1.3.0 配置sasl.enable=true时，无法与B套建立连接。

如果只把kafka开启sasl，zk没有开启，eagle也会对zk验证，并报错，监控无法获取到zk数据。
例如：ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.

**Comment by senlin0820** [comment]
我也遇到了相同问题，Kafka ZK都没开启sasl认证，sasl.enable=false，但是启动报错：
ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.

**Comment by zhyliu** [comment]
我也遇到了这个问题，最后是怎么解决的？
