### ISSUE TITLE
收不到告警邮件

### ISSUE THREAD

**Issue by Fanduzi** [smartloli/kafka-eagle#157]
kafka_2.12-2.1.0
zookeeper-3.4.12
kafka eagle 1.3.0

```
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=sa
kafka.eagle.mail.username=papar@sina.com
kafka.eagle.mail.password=pass
kafka.eagle.mail.server.host=smtp.sina.com
kafka.eagle.mail.server.port=25
```
可以ping通 telnet
```
# ping smtp.sina.com
PING smtp.sina.com (49.7.36.22) 56(84) bytes of data.
64 bytes from smtp.sina.com (49.7.36.22): icmp_seq=1 ttl=53 time=2.29 ms
64 bytes from smtp.sina.com (49.7.36.22): icmp_seq=2 ttl=53 time=2.33 ms
^C
--- smtp.sina.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 2.293/2.316/2.339/0.023 ms
# telnet smtp.sina.com 25
Trying 49.7.36.22...
Connected to smtp.sina.com.
Escape character is '^]'.
220 smtp-2-33.smtpsmail.fmail.yf.sinanode.com ESMTP
```
![image](https://user-images.githubusercontent.com/24428128/54282592-4e923280-45d7-11e9-9b15-efb6372afe87.png)

不想做伸手党. 但是吧..文档写的确实简陋了些. 从日志也看不到是配置不对没发邮件 还是说发不出去, 日志中没有这样写信息. 所以我这里无法继续排查了
请问是需要在操作系统装什么包吗?

**Comment by Fanduzi** [comment]
我测了钉钉没问题可以收到告警.说明告警配置没问题

**Comment by Fanduzi** [comment]
体验了下,感觉告警功能还是有待强化. 
一个问题是我使用ke监控了两个集群
在kafka1配置了告警 可以收到kafka宕机的告警
删除kafka1的告警,在kafka2配置告警 无法收到kafka宕机的告警
第二个问题是
kafka节点从宕机中恢复了,收不到已恢复的告警

**Comment by smartloli** [comment]
If you want use mail to send alert message, pelase make sure you mail server ```POP3/SMTP``` or ```IMAP/SMTP``` service has started (default is disabled).

In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.

**Comment by Fanduzi** [comment]
> If you want use mail to send alert message, pelase make sure you mail server `POP3/SMTP` or `IMAP/SMTP` service has started (default is disabled).
> 
> In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.

请问节点从宕机中恢复, 是否会有 `已恢复`的告警通知?

**Comment by smartloli** [comment]
> > If you want use mail to send alert message, pelase make sure you mail server `POP3/SMTP` or `IMAP/SMTP` service has started (default is disabled).
> > In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.
> 
> 请问节点从宕机中恢复, 是否会有 `已恢复`的告警通知?

The current version is not available for the time being. The next version of this requirement can be integrated.

**Comment by Fanduzi** [comment]
> If you want use mail to send alert message, pelase make sure you mail server `POP3/SMTP` or `IMAP/SMTP` service has started (default is disabled).
> 
> In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.

您好,我比较菜,实在没懂你说的开启邮件服务是什么意思?
我以为按这个配置文件就是配好账号密码就行呢.
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=sa 这个选项啥意思我也没懂
kafka.eagle.mail.username=邮箱账号
kafka.eagle.mail.password=密码
kafka.eagle.mail.server.host=smtp.sina.com
kafka.eagle.mail.server.port=25

就是说上面的配置了, 还要做一些别的额外的配置?比如启动什么服务?文档没有写.您能受累详细描述一下吗

**Comment by smartloli** [comment]
In [sina webconsole](http://mail.sina.com.cn/), you click ```setting``` button, then you can find ```Client pop/imap/smtp``` option, ```POP3/SMTP``` or ```IMAP4/SMTP``` service default is closed, you can choose ```open``` option and click save button.

**Comment by Fanduzi** [comment]
> In [sina webconsole](http://mail.sina.com.cn/), you click `setting` button, then you can find `Client pop/imap/smtp` option, `POP3/SMTP` or `IMAP4/SMTP` service default is closed, you can choose `open` option and click save button.

打算放弃了大佬.. 我这开了也收不到. 钉钉机器人🤖倒是报的很欢乐
![image](https://user-images.githubusercontent.com/24428128/54416322-00e20b00-473a-11e9-93f5-a4068cc64043.png)
![image](https://user-images.githubusercontent.com/24428128/54416363-19eabc00-473a-11e9-8cb7-1fdf6c23d495.png)

**Comment by djangogao** [comment]
注意如果的服务部署在阿里云上，阿里为了防止大量的垃圾邮件而禁止了25端口的外发，会发不出邮件的，当前Kafka-eagle还不支持SSL， 建议提上日程，我准备把这块的SSL功能加上去，方便针对此情况的解决！

**Comment by Fanduzi** [comment]
> 注意如果的服务部署在阿里云上，阿里为了防止大量的垃圾邮件而禁止了25端口的外发，会发不出邮件的，当前Kafka-eagle还不支持SSL， 建议提上日程，我准备把这块的SSL功能加上去，方便针对此情况的解决！

我们没用云, 而且这个邮箱也是我们用来发告警用的,一直用的好好的

**Comment by djangogao** [comment]
> > 注意如果的服务部署在阿里云上，阿里为了防止大量的垃圾邮件而禁止了25端口的外发，会发不出邮件的，当前Kafka-eagle还不支持SSL， 建议提上日程，我准备把这块的SSL功能加上去，方便针对此情况的解决！
> 
> 我们没用云, 而且这个邮箱也是我们用来发告警用的,一直用的好好的

明白你的意思，你的邮箱服务本身是没问题的。当前的状况是，我把kafka-eagle部署在阿里云上，服务尝试连接邮箱服务器，由于端口25被阿里云禁掉了，所以邮件发不出去（连接邮箱服务器不成功）。

**Comment by djangogao** [comment]
接下来，我想提交一个关于启用邮箱的SSL的pull request, 很希望参与到你们开源项目中去. ^_^

**Comment by djangogao** [comment]
> > If you want use mail to send alert message, pelase make sure you mail server `POP3/SMTP` or `IMAP/SMTP` service has started (default is disabled).
> > In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.
> 
> 您好,我比较菜,实在没懂你说的开启邮件服务是什么意思?
> 我以为按这个配置文件就是配好账号密码就行呢.
> kafka.eagle.mail.enable=true
> kafka.eagle.mail.sa=sa 这个选项啥意思我也没懂
> kafka.eagle.mail.username=邮箱账号
> kafka.eagle.mail.password=密码
> kafka.eagle.mail.server.host=smtp.sina.com
> kafka.eagle.mail.server.port=25
> 
> 就是说上面的配置了, 还要做一些别的额外的配置?比如启动什么服务?文档没有写.您能受累详细描述一下吗

kafka.eagle.mail.sa=sa 这个选项也是用邮箱账号试试（跟kafka.eagle.mail.username=邮箱账号一样）

这是我的测试账号，已经测试可用（前提：你的kafka-eagle部署的机器环境没有禁掉端口25）：
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=django_vip_test@163.com
kafka.eagle.mail.username=django_vip_test@163.com
kafka.eagle.mail.password=djangos8
kafka.eagle.mail.server.host=smtp.163.com
kafka.eagle.mail.server.port=25

**Comment by Fanduzi** [comment]
> > > If you want use mail to send alert message, pelase make sure you mail server `POP3/SMTP` or `IMAP/SMTP` service has started (default is disabled).
> > > In addition, the kafka alarms in multiple clusters will be available. If they are not received, please check whether they are missing or the interface address of the alarm is limited.
> > 
> > 
> > 您好,我比较菜,实在没懂你说的开启邮件服务是什么意思?
> > 我以为按这个配置文件就是配好账号密码就行呢.
> > kafka.eagle.mail.enable=true
> > kafka.eagle.mail.sa=sa 这个选项啥意思我也没懂
> > kafka.eagle.mail.username=邮箱账号
> > kafka.eagle.mail.password=密码
> > kafka.eagle.mail.server.host=smtp.sina.com
> > kafka.eagle.mail.server.port=25
> > 就是说上面的配置了, 还要做一些别的额外的配置?比如启动什么服务?文档没有写.您能受累详细描述一下吗
> 
> kafka.eagle.mail.sa=sa 这个选项也是用邮箱账号试试（跟kafka.eagle.mail.username=邮箱账号一样）
> 
> 这是我的测试账号，已经测试可用（前提：你的kafka-eagle部署的机器环境没有禁掉端口25）：
> kafka.eagle.mail.enable=true
> kafka.eagle.mail.sa=[django_vip_test@163.com](mailto:django_vip_test@163.com)
> kafka.eagle.mail.username=[django_vip_test@163.com](mailto:django_vip_test@163.com)
> kafka.eagle.mail.password=djangos8
> kafka.eagle.mail.server.host=smtp.163.com
> kafka.eagle.mail.server.port=25

感谢👍, 我有空测一下

**Comment by Fanduzi** [comment]
@djangogao Hi, 我刚才试了一下
我没改任何配置, 除了`kafka.eagle.mail.sa` 把他改成了`kafka.eagle.mail.username`的值
然后就能收到邮件了...
我不知道是不是真的是这个原因, 如果是就太坑了.

**Comment by djangogao** [comment]
> @djangogao Hi, 我刚才试了一下
> 我没改任何配置, 除了`kafka.eagle.mail.sa` 把他改成了`kafka.eagle.mail.username`的值
> 然后就能收到邮件了...
> ![image](https://user-images.githubusercontent.com/24428128/54737584-c1109d00-4beb-11e9-9299-54eed8bb9689.png)
> 用的还是之前的邮箱, 没有用你给的
> 我不知道是不是真的是这个原因, 如果是就太坑了.

是的，就是这样，我也是试了多此，然后把他们改成一样，就好了^_^

**Comment by Fanduzi** [comment]
@smartloli 建议更新文档

**Comment by taoweiming** [comment]
Email password is not available, you need to use the authorization password  T_T

**Comment by smartloli** [comment]
You can view the password corresponding to the username in kafka eagle v1.3.1.
