### ISSUE TITLE
在kafka_2.10-0.8.2.2版本，当partition是0分区时，metadata.leader() == null

### ISSUE THREAD

**Issue by liujianrong** [smartloli/kafka-eagle#16]
报错：[KafkaClusterUtils.getLogSize()] - Can't find Leader for Topic and Partition. Exiting
现象：当分区号为0的时候，findLeader(hosts, topic, partition)方法获取的 leader 为null， 导致最总获取的logSize 为0 ，实际logSize不为空，请问这是一个bug么
![image](https://user-images.githubusercontent.com/12397561/28412806-e19a42f0-6d77-11e7-889b-7e50174c384e.png)
![image](https://user-images.githubusercontent.com/12397561/28412846-fe27a20a-6d77-11e7-96a1-5f87fc52327e.png)

**Comment by smartloli** [comment]
@liujianrong Go to the ```http://ip:port/ke/topic/meta/{topicName}/``` (Topic -> List) and see the values of the ```Leader```, ```Replicas```,``` Isr```, and other attributes of the topic. Are they normal?
