### ISSUE TITLE
这什么操作

### ISSUE THREAD

**Issue by hackereye** [smartloli/kafka-eagle#160]
[](url)
![2019-03-27 10-18-25 的屏幕截图](https://user-images.githubusercontent.com/4652728/55045761-ef71fa80-5079-11e9-83ff-277a5555f9e4.png)

**Comment by taoweiming** [comment]
和你报错相同

**Comment by smartloli** [comment]
You install kafka eagle into Ubuntu OS ? Maybe you can download the source code and compile it yourself.

**Comment by hackereye** [comment]
加份中文吧，没几个老外关注你这里的
