### ISSUE TITLE
在浏览器里访问时出错

### ISSUE THREAD

**Issue by Sky8080** [smartloli/kafka-eagle#161]
我是按照官网的步骤一步一步配置的，程序也启动成功了，显示了启动成功的信息；但是在浏览器里输入访问地址后报 HTTP Status 500 - Servlet.init() for servlet SpringMvc threw exception的错误，是我的系统缺少什么东西吗

**Comment by smartloli** [comment]
I use the Centos OS to compile. If you use other types of OS, you can download the source code and compile it yourself.
