### ISSUE TITLE
1.3.1版本启动报错

### ISSUE THREAD

**Issue by weifeng520** [smartloli/kafka-eagle#162]
kafka-eagle-web-1.3.1-bin.tar.gz 
[2019-04-09 16:23:28] INFO: Status Code[127]
[2019-04-09 16:23:28] ERROR: [Oops! Error occurred! Please see the message upside!]

127是什么意思？

**Comment by smartloli** [comment]
@weifeng520 
```
vi ~/.bash_profile

# set kafka eagle home & jdk env
export KE_HOME=/data/kafka-eagle
export JAVA_HOME=/data/jdk

export PATH=$PATH:$KE_HOME/bin:$JAVA_HOME/bin
```
then
```
source ~/.bash_profile
```

**Comment by nihaojava** [comment]
在1.3.2版本中这么做还是会报同样的错误吧
