### ISSUE TITLE
 Is this a bug?

### ISSUE THREAD

**Issue by WhisperLoli** [smartloli/kafka-eagle#163]
![image](https://user-images.githubusercontent.com/31977300/56149221-a5c46200-5fde-11e9-810b-d9bedf54459a.png)

**Comment by WhisperLoli** [comment]
And the kafka eagle is the lastest

**Comment by WhisperLoli** [comment]
Another problem is that it does not support keyword capitalization.

**Comment by muwednesday** [comment]
```
select * from "test" where "partition" in (0) limit 1
```
When I use the SQL above, the logs show `Finished by [0.542s].`, but nothing shows in the result tab. Maybe something wrong with datatables, which the Chorme console shows error:
```
jquery.dataTables.min.js:65 Uncaught TypeError: Cannot read property 'aDataSort' of undefined
```
Please help @smartloli

**Comment by smartloli** [comment]
@muwednesday 
Got it.
If this happens, you may need to refresh your browser and then execute the SQL statement.
And
I will fix this as soon as possible.

**Comment by codemayq** [comment]
I also have the same problem with the above user @WhisperLoli in the latest version.
