### ISSUE TITLE
1.3.1版本是不是不能监控kafka 0.9版本的consumer offset?

### ISSUE THREAD

**Issue by gcstar** [smartloli/kafka-eagle#164]
我使用的是kafka-eagle 1.3.1 和 kafka 0.9.0.1
当设置offset.storage=zookeeper的时候，可以监控到kakfa-console-consumer消费的offset,
但是设置offset.stoage=kafka的时候，监控不到 new consumer消费的offset信息

**Comment by smartloli** [comment]
@gcstar 
Pelase Read [Kafka Eagle Blog](https://www.cnblogs.com/smartloli/p/9371904.html)
Or
Add QQ Group 825943084 discuss.
