### ISSUE TITLE
ERROR - Get kafka version from jmx has error

### ISSUE THREAD

**Issue by 191801737** [smartloli/kafka-eagle#168]
使用kafka的版本是 kafka_2.12-2.2.0.tgz

kafka-eagled的版本是Version 1.3.1

不能获取Consumers 内容。 查看日志 发现 不能获取正确的kafka版本信息，猜测是版本兼容问题。

**Comment by huzhengyao** [comment]
试了试不太好用，啥时候改成spring boot

**Comment by anpu2018** [comment]
kafka默认不开启jms的，鹰使用jms方式与kafka交互数据，在kafka启动脚本里把jms打开，类似于JMS_PORT=9999

**Comment by navyaijm2017** [comment]
同样遇到这个问题了，kafka-eagle是从kafka的那个jms的端口去抓取数据呢

**Comment by smartloli** [comment]
需要开启Kafka的JMX端口，参考博客文章：【[Kafka Eagle剖析](https://www.cnblogs.com/smartloli/p/9371904.html)】
