### ISSUE TITLE
please start with select?

### ISSUE THREAD

**Issue by ighack** [smartloli/kafka-eagle#171]
ERROR - SQL[SELECT "partition","offset","msg" FROM "Parallel_Computing_Stock" limit 10] has error,please start with select.

我的原始语句就是SELECT "partition","offset","msg" FROM "Parallel_Computing_Stock" limit 10
没有换行。select前没有空格
没有其他语句

**Comment by rinkako** [comment]
I've encountered this problem also, and I use `select` with lower case can resolve this problem. It seems that the syntax parser has a bug? :)

**Comment by ighack** [comment]
However I use lower,I can't get result.
result is empty and logs is empty

**Comment by rinkako** [comment]
try a completed sql, `select * from "topic_name" where "partition" in (0,1,2) limit 10`, don't miss `where "partition" in ... limit ...`.

**Comment by ighack** [comment]
thanks
