### ISSUE TITLE
Topic/list ，停留在processing ,其他功能都正常(查message , 生产消息)

### ISSUE THREAD

**Issue by panda-bear** [smartloli/kafka-eagle#173]
kafka eagle version 1.2.4
Topic/list ，停留在processing，出现不了主题列表。 ,其他功能都正常(查message , 生产消息)

**Comment by smartloli** [comment]
请使用最新版本Kafka Eagle：[https://www.kafka-eagle.org/](https://www.kafka-eagle.org/)
