### ISSUE TITLE
数据库初始化

### ISSUE THREAD

**Issue by ly609098** [smartloli/kafka-eagle#175]
请问初始化数据库的表放在哪呀?

**Comment by smartloli** [comment]
现在Kafka Eagle在启动时，会自动初始化数据库表。相关配置配置请阅读手册：[https://docs.kafka-eagle.org](https://docs.kafka-eagle.org/2.Install/2.Installing.html)

**Comment by xfworld** [comment]
mysql8 没有正常的初始化成功，是否能够准备一份 init script，方便其他版本的完成数据库的初始化？

**Comment by xfworld** [comment]
我用mysql5.7初始化，然后把数据表同步到了8.0，就ok了，有点小蛋疼
