### ISSUE TITLE
在windows上调试部署kafka-eagle

### ISSUE THREAD

**Issue by BooksCup** [smartloli/kafka-eagle#178]
`String tmp = endpoints.split(File.separator + File.separator)[1]`
如果基于windows环境调试部署kafka-eagle，zk是部署在linux上面，endpoint格式是["PLAINTEXT://192.168.0.1:9092"]，windows环境下File.separator是反斜杠,对endpoint进行字符拆分获取第一段则会数组越界，初测会影响到JMX监控，创建topic等等。

**Comment by smartloli** [comment]
Suggested deployment of Kafka Eagle using Linux operating system.
