### ISSUE TITLE
分区数量比较多情况下 消费者分区积压情况显示不出来

### ISSUE THREAD

**Issue by zsjohny** [smartloli/kafka-eagle#179]
![image](https://user-images.githubusercontent.com/8543865/58476727-3c5e7400-8184-11e9-9f5c-26c7db9dba85.png)

![image](https://user-images.githubusercontent.com/8543865/58476717-34063900-8184-11e9-9ff6-3959e66232b3.png)

**Comment by zsjohny** [comment]
@smartloli

**Comment by zzzxx** [comment]
连不上jmx

**Comment by zzzxx** [comment]
我也是这个问题
![图片](https://user-images.githubusercontent.com/22747106/59735762-90dba780-9289-11e9-970b-124347589649.png)

**Comment by jalja** [comment]
created: META-INF/maven/
  created: META-INF/maven/org.smartloli.kafka.eagle/
  created: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/
 inflated: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/pom.xml
 inflated: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/pom.properties
*******************************************************************
* Kafka Eagle system monitor port successful... 
*******************************************************************
[2019-07-24 15:35:43] INFO: Status Code[1]
[2019-07-24 15:35:43] ERROR: [Oops! Error occurred! Please see the message upside!]
