### ISSUE TITLE
Adding blood relationship maps to consumed topics

### ISSUE THREAD

**Issue by kafka123** [smartloli/kafka-eagle#181]
Hi, Kafka Eagle whether can Adding blood relationship maps to consumed topics? Like this:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/51170143/58610209-38923500-82dd-11e9-8172-8f369381a4eb.png">

**Comment by smartloli** [comment]
OK, this feature is under development.

**Comment by jalja** [comment]
created: META-INF/maven/
  created: META-INF/maven/org.smartloli.kafka.eagle/
  created: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/
 inflated: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/pom.xml
 inflated: META-INF/maven/org.smartloli.kafka.eagle/kafka-eagle-web/pom.properties
*******************************************************************
* Kafka Eagle system monitor port successful... 
*******************************************************************
[2019-07-24 15:35:43] INFO: Status Code[1]
[2019-07-24 15:35:43] ERROR: [Oops! Error occurred! Please see the message upside!]
