### ISSUE TITLE
DispatcherServlet.http-nio-8048-exec-1 - ERROR - Context initialization failed

### ISSUE THREAD

**Issue by heqian1024** [smartloli/kafka-eagle#184]
环境：
zookeeper：zookeeper-3.4.12
kafka：kafka_2.11-0.10.2.0
jdk：jdk1.8.0_202
kafka-eagle：kafka-eagle-bin-1.3.3.tar.gz

报错信息：
[2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:27] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:28] ZooKeeperClient.localhost-startStop-1-EventThread - ERROR - [ZooKeeperClient] Auth failed.
 [2019-06-10 18:35:29] DispatcherServlet.localhost-startStop-1 - ERROR - Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mappingJacksonHttpMessageConverter' defined in class path resource [spring-mvc.xml]: Instantiation of bean faile
d; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter]: Constructor threw excep
tion; nested exception is java.lang.NoSuchFieldError: USE_DEFAULTS
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:504)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:663)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:629)
	at org.springframework.web.servlet.FrameworkServlet.createWebApplicationContext(FrameworkServlet.java:677)
	at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:548)
	at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:489)
	at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1194)
	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1110)
	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1000)
	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4902)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5212)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:152)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter]: Constructor threw exception; nested
 exception is java.lang.NoSuchFieldError: USE_DEFAULTS
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:163)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:89)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1094)
	... 33 more

**Comment by smartloli** [comment]
What type of operating system is your server using? ```CentOS```, ```Ubuntu```, or other ```OS``` ?

**Comment by heqian1024** [comment]
kafka机器：2台centos6.5，1台red hat 5.8
kafka-eagle机器：上面3台机器上都装过，都会报这个错误

**Comment by smartloli** [comment]
Maybe you can use ```CentOS 6.6+, 7.x```, or build in ```CentOS6.5``` by youself.

**Comment by heqian1024** [comment]
就是自己biuld的
以下是bould日志信息：

`[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ke                                                                 [pom]
[INFO] kafka-eagle-common                                                 [jar]
[INFO] kafka-eagle-api                                                    [jar]
[INFO] kafka-eagle-core                                                   [jar]
[INFO] kafka-eagle-plugin                                                 [jar]
[INFO] ke                                                                 [war]
[INFO] 
[INFO] ---------------< org.smartloli.kafka.eagle:kafka-eagle >----------------
[INFO] Building ke 1.3.3                                                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle ---
[INFO] 
[INFO] ------------< org.smartloli.kafka.eagle:kafka-eagle-common >------------
[INFO] Building kafka-eagle-common 1.3.3                                  [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle-common ---
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-api >--------------
[INFO] Building kafka-eagle-api 1.3.3                                     [3/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle-api ---
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-core >-------------
[INFO] Building kafka-eagle-core 1.3.3                                    [4/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle-core ---
[INFO] 
[INFO] ------------< org.smartloli.kafka.eagle:kafka-eagle-plugin >------------
[INFO] Building kafka-eagle-plugin 1.3.3                                  [5/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle-plugin ---
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-web >--------------
[INFO] Building ke 1.3.3                                                  [6/6]
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ kafka-eagle-web ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ke 1.3.3 ........................................... SUCCESS [  0.116 s]
[INFO] kafka-eagle-common ................................. SUCCESS [  0.004 s]
[INFO] kafka-eagle-api .................................... SUCCESS [  0.002 s]
[INFO] kafka-eagle-core ................................... SUCCESS [  0.002 s]
[INFO] kafka-eagle-plugin ................................. SUCCESS [  0.002 s]
[INFO] ke 1.3.3 ........................................... SUCCESS [  0.004 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.247 s
[INFO] Finished at: 2019-06-12T16:12:20+08:00
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] ke                                                                 [pom]
[INFO] kafka-eagle-common                                                 [jar]
[INFO] kafka-eagle-api                                                    [jar]
[INFO] kafka-eagle-core                                                   [jar]
[INFO] kafka-eagle-plugin                                                 [jar]
[INFO] ke                                                                 [war]
[INFO] 
[INFO] ---------------< org.smartloli.kafka.eagle:kafka-eagle >----------------
[INFO] Building ke 1.3.3                                                  [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] ------------< org.smartloli.kafka.eagle:kafka-eagle-common >------------
[INFO] Building kafka-eagle-common 1.3.3                                  [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-eagle-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-eagle-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 44 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-eagle-common ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-eagle-common ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ kafka-eagle-common ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kafka-eagle-common ---
[INFO] Building jar: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/target/kafka-eagle-common-1.3.3.jar
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-api >--------------
[INFO] Building kafka-eagle-api 1.3.3                                     [3/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-eagle-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-api/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-eagle-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-api/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-eagle-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-api/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-eagle-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-api/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ kafka-eagle-api ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kafka-eagle-api ---
[INFO] Building jar: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-api/target/kafka-eagle-api-1.3.3.jar
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-core >-------------
[INFO] Building kafka-eagle-core 1.3.3                                    [4/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-eagle-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-core/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-eagle-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 31 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-core/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-eagle-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-core/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-eagle-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-core/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ kafka-eagle-core ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kafka-eagle-core ---
[INFO] Building jar: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-core/target/kafka-eagle-core-1.3.3.jar
[INFO] 
[INFO] ------------< org.smartloli.kafka.eagle:kafka-eagle-plugin >------------
[INFO] Building kafka-eagle-plugin 1.3.3                                  [5/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-eagle-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-plugin/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-eagle-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-plugin/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-eagle-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-plugin/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-eagle-plugin ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ kafka-eagle-plugin ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ kafka-eagle-plugin ---
[INFO] Building jar: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-plugin/target/kafka-eagle-plugin-1.3.3.jar
[INFO] 
[INFO] -------------< org.smartloli.kafka.eagle:kafka-eagle-web >--------------
[INFO] Building ke 1.3.3                                                  [6/6]
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ kafka-eagle-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ kafka-eagle-web ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 49 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/target/classes
[WARNING] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/main/java/org/smartloli/kafka/eagle/web/service/impl/RoleServiceImpl.java: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/main/java/org/smartloli/kafka/eagle/web/service/impl/RoleServiceImpl.java使用或覆盖了已过时的 API。
[WARNING] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/main/java/org/smartloli/kafka/eagle/web/service/impl/RoleServiceImpl.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ kafka-eagle-web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ kafka-eagle-web ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/target/test-classes
[WARNING] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/test/java/org/smartloli/kafka/eagle/factory/TestZkTopic.java: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/test/java/org/smartloli/kafka/eagle/factory/TestZkTopic.java使用或覆盖了已过时的 API。
[WARNING] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/test/java/org/smartloli/kafka/eagle/factory/TestZkTopic.java: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ kafka-eagle-web ---
[INFO] Tests are skipped.
[INFO] 
[INFO] --- maven-war-plugin:2.2:war (default-war) @ kafka-eagle-web ---
[INFO] Packaging webapp
[INFO] Assembling webapp [kafka-eagle-web] in [/home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/target/kafka-eagle-web-1.3.3]
[INFO] Processing war project
[INFO] Copying webapp resources [/home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/src/main/webapp]
[INFO] Webapp assembled in [170 msecs]
[INFO] Building war: /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/target/ke.war
[INFO] WEB-INF/web.xml already added, skipping
[INFO] 
[INFO] --- maven-assembly-plugin:2.2-beta-5:single (make-assembly) @ kafka-eagle-web ---
[INFO] Reading assembly descriptor: src/main/resources/assembly.xml
[INFO] Building tar : /home/kafka/kafka-eagle-1.3.3/kafka-eagle-web/target/kafka-eagle-web-1.3.3-bin.tar.gz
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ke 1.3.3 ........................................... SUCCESS [  0.002 s]
[INFO] kafka-eagle-common ................................. SUCCESS [  1.648 s]
[INFO] kafka-eagle-api .................................... SUCCESS [  0.136 s]
[INFO] kafka-eagle-core ................................... SUCCESS [  0.649 s]
[INFO] kafka-eagle-plugin ................................. SUCCESS [  0.097 s]
[INFO] ke 1.3.3 ........................................... SUCCESS [  8.147 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.814 s
[INFO] Finished at: 2019-06-12T16:12:32+08:00
[INFO] ------------------------------------------------------------------------`

**Comment by heqian1024** [comment]
我build时配置文件加了一下内容，否则build会报错，报错信息见下方
vim pom.xml 
`        <properties>
                <maven.compiler.source>1.8</maven.compiler.source>
                <maven.compiler.target>1.8</maven.compiler.target>
                <maven.compiler.compilerVersion>1.8</maven.compiler.compilerVersion>

        </properties>
`

直接编译会报错：
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/protocol/KafkaSqlInfo.java:[34,57] -source 1.5 中不支持 diamond 运算符
  (请使用 -source 7 或更高版本以启用 diamond 运算符)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/util/KafkaZKPoolUtils.java:[44,84] -source 1.5 中不支持 diamond 运算符
  (请使用 -source 7 或更高版本以启用 diamond 运算符)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/util/KafkaZKPoolUtils.java:[50,60] -source 1.5 中不支持文字中存在下划线
  (请使用 -source 7 或更高版本以允许文字中存在下划线)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/protocol/MailSenderInfo.java:[46,61] -source 1.5 中不支持 diamond 运算符
  (请使用 -source 7 或更高版本以启用 diamond 运算符)
[INFO] 4 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] ke 1.3.3 ........................................... SUCCESS [  0.003 s]
[INFO] kafka-eagle-common ................................. FAILURE [  0.878 s]
[INFO] kafka-eagle-api .................................... SKIPPED
[INFO] kafka-eagle-core ................................... SKIPPED
[INFO] kafka-eagle-plugin ................................. SKIPPED
[INFO] ke 1.3.3 ........................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.990 s
[INFO] Finished at: 2019-06-12T16:29:07+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project kafka-eagle-common: Compilation failure: Compilation failure: 
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/protocol/KafkaSqlInfo.java:[34,57] -source 1.5 中不支持 diamond 运算符
[ERROR]   (请使用 -source 7 或更高版本以启用 diamond 运算符)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/util/KafkaZKPoolUtils.java:[44,84] -source 1.5 中不支持 diamond 运算符
[ERROR]   (请使用 -source 7 或更高版本以启用 diamond 运算符)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/util/KafkaZKPoolUtils.java:[50,60] -source 1.5 中不支持文字中存在下划线
[ERROR]   (请使用 -source 7 或更高版本以允许文字中存在下划线)
[ERROR] /home/kafka/kafka-eagle-1.3.3/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/protocol/MailSenderInfo.java:[46,61] -source 1.5 中不支持 diamond 运算符
[ERROR]   (请使用 -source 7 或更高版本以启用 diamond 运算符)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :kafka-eagle-common

**Comment by little6** [comment]
麻烦问一下,这个问题是否解决了?感谢

**Comment by heqian1024** [comment]
还没解决呢，我在另一台centos6.5测试机上能搭起来，在这3台机器上就是有问题，能不能帮忙再看看是啥原因，需要我再提供什么信息？

**Comment by smartloli** [comment]
you can edit $M2_HOME/conf/setting.xml file, modift ```JDK``` version like this
```
<profile>
      <id>jdk-1.8</id>
      <activation>
        <activeByDefault>true</activeByDefault>
        <jdk>1.8</jdk>
      </activation>
      <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <maven.compiler.compilerVersion>1.8</maven.compiler.compilerVersion>
      </properties>
</profile>
```
