### ISSUE TITLE
Kafka Eagle V1.3.3版本不支持kafka 10.0.1,consumer不能显示完整

### ISSUE THREAD

**Issue by xinming158** [smartloli/kafka-eagle#188]
UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic

**Comment by xinming158** [comment]
我在Kafka Eagle  V1.3.3的时候，consumer不能显示完整，后台提示版本不一致：

UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic

我的kafka版本是：kafka 2.11:0.10.0.1，应该使用哪个版本的Kafka Eagle？

**Comment by smartloli** [comment]
@xinming158 Read #189 
Two ways:

you can checkout v1.2.8;
if you can modify kafka broker server.properties file, like this :
inter.broker.protocol.version=NEW_KAFKA_VERSION (such as 1.0.0, 2.0.0, or newer)
log.message.format.version=NEW_KAFKA_VERSION (such as 1.0.0, 2.0.0, or newer)
