### ISSUE TITLE
can not open dashboard

### ISSUE THREAD

**Issue by sherry0429** [smartloli/kafka-eagle#19]
i do this : https://ke.smartloli.org/2.Install/2.Installing.html
and i start kafka-eagle, 
it's run in Red hat 6 virtual machine in virtualBox
java is ok.

and i can access ip:port/ke, enter login page. but when i input "admin" and "123456", /signin/action not lead me to dashboard.

i check the conf and find "mysql", and it's have eagle.user, eagle.password, is it my mysql account?

when i call stats, i see my ip in "ESTABLISHED/TIME_OUT Status Block.

**Comment by sherry0429** [comment]
ok, i see log "no database ke",
i will try create a database ke in mysql

**Comment by smartloli** [comment]
@sherry0429 Yes, you need create ```ke``` database first.

**Comment by sherry0429** [comment]
i have craete ke database, but sql have "utf8mb4",  i changed it to "utf8"
now i can go to dashboard, but i still met a problem ::

when i use Message kafka Query SQL:

select "msg" from "Topic" where "partition" in (0) limit 10  (my topic only one partition)
Result is empty.

i check my config,  offset.storage= kafka, and i check my kafka log, in topic, *.log file have my message content.

can you help me? thx

**Comment by sherry0429** [comment]
update::
when i query "select "msg" from "topic" where "partition" in (0), 
just without limit.

broswer(chrome) alert:
DataTables warning tableid=result_children0 
cannot reinitialise DataTable.For more information about this error, please see http://datatables.net/tn/3

**Comment by smartloli** [comment]
@sherry0429 Maybe the browser has a cache, you can try using it ```select * from "topic" where "partition" in (0)```

**Comment by sherry0429** [comment]
ok, when i clean cache, query ok without limit.

but still have not result.........

**Comment by smartloli** [comment]
@sherry0429 Display your logger information.

**Comment by sherry0429** [comment]
Aahhh, it's in LAN，
error.log:
JMX serviceURL[192.168.2.102:-1] create has error, msg is failed to  retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException : Connection refused to host 192.168.2.102

**Comment by sherry0429** [comment]
hostname -i is my ip.
ip table closed.
System : Red hat 6

**Comment by smartloli** [comment]
@sherry0429 Check that the port of JMX is started . If you do not start, you can edit the script before you start .
```bash
vi kafka-server-start.sh
...
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
    #export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
fi
```

**Comment by sherry0429** [comment]
@smartloli 

ok，i fix this。but here have a bug. please fix that.
first question is my error, jmx in my machine is wrong setting. but when i fix jmx, not error, but still no data from Result by kafka query sql.

i check out log, i find when i quary
`select "msg" from "A" where "partition" in (0) limit 1`
it changed in log:
`select "msg" from "a" where "partition" in (0) limit 1`

so **"A" -> "a"**, but i have not topic "a", so i can not get data.

this maybe a bug.

can you fix this ? thanks

**Comment by smartloli** [comment]
@sherry0429 View the latest version implementation details, or use the latest version.

**Comment by sherry0429** [comment]
i use 1.1.7.

but now when i input sql,

error.log say:

Execute sql to query kafka topic has error, msg is Consumer is not subscribed to any topics or assigned any partitions

**Comment by sherry0429** [comment]
update:

error.log means in [https://github.com/smartloli/kafka-eagle/blob/master/kafka-eagle-core/src/main/java/org/smartloli/kafka/eagle/core/sql/execute/KafkaSqlParser.java](KafkaSqlParser) class


`					long start = System.currentTimeMillis();
					kafkaSql.setClusterAlias(clusterAlias);
					List<JSONArray> dataSets = KafkaConsumerAdapter.executor(kafkaSql);
					String results = JSqlUtils.query(kafkaSql.getSchema(), kafkaSql.getTableName(), 
dataSets, kafkaSql.getSql());
                                        long end = System.currentTimeMillis();
					status.put("error", false);
					status.put("msg", results);
					status.put("status", "Finished by [" + (end - start) / 1000.0 + "s].");`

this code raise "Consumer is not subscribed...." exception

**Comment by sherry0429** [comment]
@smartloli 
i clone this project open in IDEA, can you tell me how to run it ? thanks

**Comment by sherry0429** [comment]
runTomcatServerListen.java

 Listen Tomcat Server Port Has Error,Msg is E:\kafka-eagle-master\kms\conf\server.xml  system can not find this path..

AAAaaa..

**Comment by smartloli** [comment]
@sherry0429 Download the code for the latest master branch. If you want run this project, you can run it in accordance with the ```maven``` project.
