### ISSUE TITLE
PageNotFound.http-nio-8048-exec-9 - WARN  - Request method 'POST' not supported

### ISSUE THREAD

**Issue by xxJ-2019** [smartloli/kafka-eagle#191]

**Comment by hljhrbeu** [comment]
我也出现了同样问题，不过我是用docker启动的（用压缩包直接启动时可以登录UI界面），经过测试怀疑是  /hadoop/kafka-eagle/db/ 这目录中没有数据文件导致。下一步准备试试MySQL
kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/hadoop/kafka-eagle/db/ke.db
kafka.eagle.username=root
kafka.eagle.password=www.kafka-eagle.org
