### ISSUE TITLE
user manager自定义用户无法修改密码

### ISSUE THREAD

**Issue by liqunlin** [smartloli/kafka-eagle#192]
1、在system-user-user manager模块里，自定义的用户，无法自行修改密码(只能通过登录后右上角reset password实现)。我感觉 用户管理 模块 十分需要reset user password功能项。
2、v1.3.4版本，下载https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.1.tar.gz后，在一台机器上可以在右上角reset user password，在另一台机器上reset user password时点击submit没反应，尝试多次一样，问题复现。

**Comment by smartloli** [comment]
fixed by [Kafka Eagle V1.3.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.8.tar.gz)
