### ISSUE TITLE
建议可以把生产者的信息也展示出来

### ISSUE THREAD

**Issue by stormsend** [smartloli/kafka-eagle#199]

**Comment by smartloli** [comment]
fixed by [Kafka Eagle V1.3.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.8.tar.gz)

**Comment by smartloli** [comment]
fixed by [Kafka Eagle V1.3.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.8.tar.gz)
