### ISSUE TITLE
登录页面输入用户密码后，登录不了

### ISSUE THREAD

**Issue by jayws** [smartloli/kafka-eagle#20]
登录页面输入用户密码后，登录不了，界面一直都是空白，使用1.1.6，kafka 0.8，请问有人可以帮忙解决一下吗？谢谢

**Comment by smartloli** [comment]
@jayws you need create ke database first.

**Comment by jayws** [comment]
嗯，后来才看到的，谢谢

**Comment by jayws** [comment]
想问下，V1.1.6不兼容kafka 0.8的吗？我每次执行操作create topic时服务自动停止，请问是什么回事？谢谢

**Comment by smartloli** [comment]
@jayws 
```bash
# kafka offset storage -- Offset stored in a Kafka cluster, if stored in the zookeeper, you can not use this option
kafka.eagle.offset.storage=
```
Remove ```kafka.eagle.offset.storage``` property value.

**Comment by jayws** [comment]
我把它注册掉也是一样的，但是可以获取到kafka的数据，就是不能对kafka的topic新增、delete操作

**Comment by jayws** [comment]
然后我看了下源码，kafka使用的是0.10，应该是版本问题吧

**Comment by smartloli** [comment]
@jayws View the ```Kafka Eagle``` system log.
