### ISSUE TITLE
topic大概200左右发现加载页面很慢

### ISSUE THREAD

**Issue by stormsend** [smartloli/kafka-eagle#201]

**Comment by smartloli** [comment]
Are you using [Kafka Eagle V1.3.6](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.6.tar.gz) ?

**Comment by stormsend** [comment]
using Kafka Eagle V1.3.4

**Comment by stormsend** [comment]
@smartloli 帮忙看下这个问题

**Comment by smartloli** [comment]
In Kafka Eagle v1.3.6, the problem of slow loading is solved. So please use [Kafka Eagle V1.3.6](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.6.tar.gz).

**Comment by stormsend** [comment]
升级到了1.3.6之后加载的更慢

**Comment by stormsend** [comment]
offset.storage设置成kafka之后topic list加载出来，consumers加载不出来，设置成zk之后，topic加载不出来

**Comment by smartloli** [comment]
Please read install blog [Kafka Eagle Install](https://www.cnblogs.com/smartloli/p/9371904.html)

**Comment by stormsend** [comment]
都是按照这个文档做的，offset是在kafka，配置了没用

**Comment by smartloli** [comment]
Please update [Kafka Eagle V1.3.7](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.7.tar.gz)

**Comment by khaireddine120** [comment]
slowlness exist for me with version 1.4.0
