### ISSUE TITLE
消费者显示不全

### ISSUE THREAD

**Issue by lynnyq** [smartloli/kafka-eagle#203]
kafka-eagle 版本：1.3.6
kafka版本：kafka1.0.0+cdh6.0.0

显示的消费者不全。
kafka-eagle显示的消费只有两个
![image](https://user-images.githubusercontent.com/19179078/62202075-2efb7b00-b3bb-11e9-8c3c-8a8ff7056371.png)

通过命令查出来的有24个消费者
![image](https://user-images.githubusercontent.com/19179078/62202130-50f4fd80-b3bb-11e9-8958-411e989de17d.png)

**Comment by smartloli** [comment]
@lynnyq 
Please read [Kafka Eagle Install](https://www.cnblogs.com/smartloli/p/9371904.html)

**Comment by smartloli** [comment]
[Kafka Eagle V1.3.7](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.7.tar.gz) fixed it.
