### ISSUE TITLE
使用sparkstreaming direct api消费kafka，获取不到groupidea

### ISSUE THREAD

**Issue by jayws** [smartloli/kafka-eagle#21]
使用sparkstreaming direct api消费kafka，获取不到groupidea，zookeeper可以查看到offset，请问是什么问题呢？谢谢！

**Comment by smartloli** [comment]
@jayws Replace ```kafka.eagle.offset.storage=kafka``` to ```kafka.eagle.offset.storage=```

**Comment by jayws** [comment]
注释掉kafka.eagle.offset.storage不行吗

**Comment by smartloli** [comment]
@jayws Of course. ```kafka.eagle.offset.storage=``` or ```# kafka.eagle.offset.storage=kafka```
