### ISSUE TITLE
kafka 启用sasl后，kafka eagle接口响应慢

### ISSUE THREAD

**Issue by xumengqingyuan** [smartloli/kafka-eagle#211]
版本：kafka_2.12-2.3.0
           kafka eagle 1.3.7

kafka_server_jaas.conf配置
KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
};

server.properties配置
listeners=SASL_PLAINTEXT://192.168.121.130:9092
security.inter.broker.protocol=SASL_PLAINTEXT  
sasl.enabled.mechanisms=PLAIN
sasl.mechanism.inter.broker.protocol=PLAIN
authorizer.class.name=kafka.security.auth.SimpleAclAuthorizer
super.users=User:admin;

kafka启用sasl后，kafka eagle 查询kafka实时数据的相关接口响应时间都在1分钟以上。（kafka部署在VM上）

**Comment by smartloli** [comment]
1.[Kafka ACL](https://www.cnblogs.com/smartloli/p/11404610.html)
2.[Kafka Eagle ACL](https://docs.kafka-eagle.org/2.env-and-install/5.security)

**Comment by smartloli** [comment]
fixed by [Kafka Eagle V1.3.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.8.tar.gz)

**Comment by xumengqingyuan** [comment]
> fixed by [Kafka Eagle V1.3.8](https://github.com/smartloli/kafka-eagle-bin/archive/v1.3.8.tar.gz)

thanks
