### ISSUE TITLE
使用过程中会造成zookeeper连接数过多

### ISSUE THREAD

**Issue by renyj2013** [smartloli/kafka-eagle#216]

**Comment by FrommyMind** [comment]
I think the code in [org.smartloli.kafka.eagle.common.util.KafkaZKPoolUtils](https://github.com/smartloli/kafka-eagle/blob/master/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/util/KafkaZKPoolUtils.java) have a bug about zookeeper connection, that make a lot connection to zookeeper, even we set the pool size  to limit .

assume the pool size is 5, 
1. at the begin we try to init  5 connection;
2. The we use getZkClient(clusterAlias) to get one connect, and remove one connection from zkCliPool;
3. If we release a connection, then we add the connect back to zkCliPool;

But , when had used all 5 connection and not realse them,  The zkCliPool will be empty; 
At this time if we try to getZkClient(cluterAlias) , it will recreate 5 conneciton;
```				
for (int i = 0; i < zkCliPoolSize; i++) {
  zkc = KafkaZkClient.apply(clusterAliass.get(clusterAlias), JaasUtils.isZkSecurityEnabled(), ZK_SESSION_TIMEOUT_MS, ZK_CONNECTION_TIMEOUT_MS, Integer.MAX_VALUE, Time.SYSTEM, METRIC_GROUP_NAME, "SessionExpireListener");
 if (zkc != null) {
	 zkCliPool.add(zkc);
	}
}
```

If I had miss any thing , please let me know.
