### ISSUE TITLE
no charts  of kafka  metrics 

### ISSUE THREAD

**Issue by panpanliuBJ** [smartloli/kafka-eagle#217]
kafka eagle： 1.3.7
kafka： 2.3.0 1 broker,   2.0.0 2 brokers

- there are some js errors
- no time selector

![image](https://user-images.githubusercontent.com/12446331/63638153-1ed37480-c6b7-11e9-8cdb-bbfb283b6481.png)

![image](https://user-images.githubusercontent.com/12446331/63638197-a3be8e00-c6b7-11e9-96ba-e03e50ee859a.png)

**Comment by panpanliuBJ** [comment]
Kafka Cluster Info is very slow, at least 30s +


![image](https://user-images.githubusercontent.com/12446331/63638253-6a3a5280-c6b8-11e9-9e7c-c3f2d42ddd3b.png)


![image](https://user-images.githubusercontent.com/12446331/63638251-5d1d6380-c6b8-11e9-9e01-11c9dd0effe1.png)

**Comment by smartloli** [comment]
1. Your server has disabled static resource access. Check your server !
2. Slow, watch $KE_HOME/logs ...
3. Read https://docs.kafka-eagle.org/2.env-and-install/2.installing
