### ISSUE TITLE
MBean Trend can not visible metrics

### ISSUE THREAD

**Issue by chenzhikaida** [smartloli/kafka-eagle#23]
> vi kafka-server-start.sh
> ...
> if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
>     export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
>     export JMX_PORT="9999"
>     #export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
> fi

but i doesn't find  kafka-server-start.sh file

**Comment by chenzhikaida** [comment]
`[2017-07-26 08:30:00] Mx4jServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-1 - ERROR - JMX service url[192.168.77.179:-1] create has error,msg is Failed to retrieve RMIServer stub: javax.naming.ServiceUnavailableException [Root exception is java.rmi.ConnectException: Connection refused to host: 192.168.77.179; nested exception is: 
`

**Comment by smartloli** [comment]
@chenzhikaida ```kafka-server-start.sh```  is the script for your kafka cluster, inside the ```bin``` directory.

<img width="807" alt="image" src="https://user-images.githubusercontent.com/16030669/29395181-af553798-8341-11e7-9515-a093bf527e0c.png">
