### ISSUE TITLE
Can the current kafka eagle work with kafka2.3.0 and zookeeper 3.5.5 through SSL

### ISSUE THREAD

**Issue by dengfengruan** [smartloli/kafka-eagle#238]
HI 
we setup the zookeeper 3.5.5 and kafka2.3.0,
and the zookeeper is based on SSL,
can the newest kafka eagle(2019.9.29) support this case.

if support,can you tell me how to configure it.
if not support, is this in plan?

**Comment by smartloli** [comment]
Fixed by [kafka-eagle-v1.4.0](https://github.com/smartloli/kafka-eagle-bin/archive/v1.4.0.tar.gz)
