### ISSUE TITLE
BScreen 和 Metrics中的kafka无法显示

### ISSUE THREAD

**Issue by chengziCode** [smartloli/kafka-eagle#239]
kafka-eagle版本：1.3.9
kafka版本：2.0.0
浏览器: sougou，Firefox，Chrome

![image](https://user-images.githubusercontent.com/22131562/65830611-8ba7e300-e2e3-11e9-9ba5-fcac557a9519.png)
![image](https://user-images.githubusercontent.com/22131562/65830634-c1e56280-e2e3-11e9-8e50-e932c21a112d.png)
![image](https://user-images.githubusercontent.com/22131562/65830614-96627800-e2e3-11e9-9f62-995e576817a5.png)

**Comment by smartloli** [comment]
Does the server you deploy have Nginx restrictions on static files ? Check it !

![image](https://user-images.githubusercontent.com/16030669/66252260-ddd98000-e78b-11e9-8659-0982272aae43.png)

**Comment by chengziCode** [comment]
是部署在腾讯云上的。 放在本地测试环境是可以的。 是不是云上的就没办法用这个功能。

**Comment by emhlbmc** [comment]
@chengziCode add maxHttpHeaderSize="1024000" in file 'kms/conf/server.xml' , like this
```
<Connector port="8048" protocol="HTTP/1.1" URIEncoding="UTF-8" minSpareThreads="25" maxSpareThreads="75" enableLookups="false" disableUploadTimeout="true" connectionTimeout="100" acceptCount="500" maxThreads="500" maxProcessors="1000" minProcessors="5" useURIValidationHack="false" compression="on" compressionMinSize="2048" compressableMimeType="text/html,text/xml,text/javascript,text/css,text/plain" redirectPort="8443" maxHttpHeaderSize="1024000"/>
```

**Comment by zhiyuan192shine** [comment]
I add maxHttpHeaderSize="1024000" into 'kms/conf/server.xml' , but not available。
please，Why is it?
![image](https://user-images.githubusercontent.com/13871686/69497597-0115e580-0f1a-11ea-8248-e3ca3fd76b14.png)

**Comment by blareck** [comment]
i modify the compressionMinSize="4096" or close compression(compression="off")，now it's show。
