### ISSUE TITLE
There's no information about required MySQL version

### ISSUE THREAD

**Issue by sparrovv** [smartloli/kafka-eagle#24]
Hi, I've been struggling with MySql related errors.

I couldn't find any information in the readme what version is required, and that it's really required. 
Once I've installed it, it worked fine.

Although there are few assumptions in the schema.sh file.
- the path to mysql. (it could be also /usr/bin/mysql)
- I was getting ` Unknown character set: 'utf8mb4'`, as I had an older version installed on the server

**Comment by smartloli** [comment]
@sparrovv  Two solutions:
* Abandon automatic creation of the database, modify database scripts (path: ```$KE_HOME/sql/ke.sql```), and replace utf8mb4 in scripts with utf8.
* Modify [JConstants.java](https://github.com/smartloli/kafka-eagle/blob/master/kafka-eagle-plugin/src/main/java/org/smartloli/kafka/eagle/plugin/util/JConstants.java),and then compile kafka eagle project.
