### ISSUE TITLE
Can not receive alarm by dingding @1.4.0version kafka-eagle

### ISSUE THREAD

**Issue by str-yl** [smartloli/kafka-eagle#241]
After config dingding alarm in system-config.properties ,and add alarm about kafka-consumer by the web side, finally still cannot receive alarm by dingding and email 。
config in system-config.properties shown by below:
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=xxxxx@163.com
kafka.eagle.mail.username=xxxxx@163.com
kafka.eagle.mail.password=123456
kafka.eagle.mail.server.host=smtp.163.com
kafka.eagle.mail.server.port=25

######################################
# alarm im configure
######################################
kafka.eagle.im.dingding.enable=true
kafka.eagle.im.dingding.url=https://oapi.dingtalk.com/robot/send?access_token=6e9226d0cb488798de5d4f018f8cedca75df21024d0dxxxxxxxxxx

**Comment by str-yl** [comment]
![image](https://user-images.githubusercontent.com/56385272/66550223-81a1a200-eb77-11e9-9a53-f6956f0ac093.png)
the Lag Threshold of the kafka consumer alarm is set to be 100，the current LAG is 6k+，but can not reveive any alarm。

**Comment by str-yl** [comment]
After checking the code and change the dingding url, this issue already has been sloved. actually the detail exception information can not be shown in log file by  using "LOG.error("Do post form request has error, msg is " + e.getMessage());"，it is difficult to troubleshoot。

**Comment by smartloli** [comment]
V1.4.0 moved the alarm to webconsole for configuration
