### ISSUE TITLE
无法在eagle界面上创建topic

### ISSUE THREAD

**Issue by iamwzt** [smartloli/kafka-eagle#245]
目前是监控了两个集群，一个是本地试验用的，另一个则是开启了`kerberos`的集群，两个都可以查看监控指标，但是开启了`kerberos`的集群无法创建`topic`，报`405`错误。

请问是需要额外的配置么？

**Comment by nuomimick** [comment]
I've met the question as you too. #237

**Comment by smartloli** [comment]
Set Kerberos. [https://docs.kafka-eagle.org/2.env-and-install/5.security](https://docs.kafka-eagle.org/2.env-and-install/5.security). 
Or add QQ Group: [825943084](825943084)
