### ISSUE TITLE
v1.3.9 UnsupportedVersionException

### ISSUE THREAD

**Issue by liushuangfromwh** [smartloli/kafka-eagle#246]
KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#2_Worker-10 - ERROR - Get kafka consumer metadata has error, msg is org.apache.kafka.common.errors.UnsupportedVersionException: The broker only supports OffsetFetchRequest v1, but we need v2 or newer to request all topic partitions.

Hi~! my kafka version is 0.10.1.0

**Comment by sophiesun333** [comment]
问题解决了吗？ 我也遇到了这个问题
