### ISSUE TITLE
访问http://host:port/ke报404

### ISSUE THREAD

**Issue by Jerrywgl** [smartloli/kafka-eagle#251]
按照文档部署后，后端存储使用的是mariadb。但是访问首页出现404
Version 1.3.9

**Comment by smartloli** [comment]
Please use the default SQLite or MySQL database.

**Comment by Jerrywgl** [comment]
Mariadb now not compatible? I try. Thank you very much

**Comment by Jerrywgl** [comment]
换成mysql5.7也是报404,查看日志报错如下:
[2019-10-30 14:38:55] ContextLoader.main - ERROR - Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'topicServiceImpl' defined in file [/usr/local/kafka-eagle/kms/webapps/ke/WEB-INF/classes/org/smartloli/kafka/eagle/web/service/impl/TopicServiceImpl.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError

**Comment by smartloli** [comment]
[Kafka Eagle Install](https://docs.kafka-eagle.org/2.env-and-install/2.installing)
