### ISSUE TITLE
ConsumerGroups. displays incorrectly on different authorizations

### ISSUE THREAD

**Issue by EvgenijO** [smartloli/kafka-eagle#253]
jdk1.8.0_201
kafka-eagle-web-1.4.0
------------------------------
conf:
...
work.kafka.eagle.offset.storage=zk
work.kafka.eagle.sasl.enable=true
work.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
work.eagle.sasl.mechanism=PLAIN
work.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka";
....

Brokers 3
Topics 2
Zookeepers 3

ConsumerGroups = 0
---------------
---------------
conf :
....
work.kafka.eagle.offset.storage=kafka
work.kafka.eagle.sasl.enable=true
work.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
work.eagle.sasl.mechanism=PLAIN
work.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafka" password="kafka";
....
view:
Dashboard
Brokers 0
Topics 0
Zookeepers 0
ConsumerGroups 0

,but
/ke/cluster/info
everything displays ok
------------------
------------------
conf:
....
work.kafka.eagle.offset.storage=kafka
work.kafka.eagle.sasl.enable=false
....
ConsumerGroups 10
----------------
----------------
conf:
...
work.kafka.eagle.offset.storage=zk
work.kafka.eagle.sasl.enable=false
....
view:
ConsumerGroups 20

**Comment by smartloli** [comment]
Read [https://docs.kafka-eagle.org/2.Install/2.Installing.html](https://docs.kafka-eagle.org/2.Install/2.Installing.html)

**Comment by EvgenijO** [comment]
This is part of the configuration for understanding the picture, I can send the complete configuration of the files. Is the essence of the problem clear?

**Comment by EvgenijO** [comment]
jdk1.8.0_201
kafka-eagle-web-1.4.0

conf:
...
work.kafka.eagle.offset.storage=zk
work.kafka.eagle.sasl.enable=true
work.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
work.eagle.sasl.mechanism=PLAIN
work.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule
required username="kafka" password="kafka";
....

Brokers 3
Topics 2
Zookeepers 3
ConsumerGroups = 0
------------------------------

conf :
....
work.kafka.eagle.offset.storage=kafka
work.kafka.eagle.sasl.enable=true
work.kafka.eagle.sasl.protocol=SASL_PLAINTEXT
work.eagle.sasl.mechanism=PLAIN
work.kafka.eagle.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule
required username="kafka" password="kafka";
....
view:
Dashboard
Brokers 0
Topics 0
Zookeepers 0
ConsumerGroups 0
,but
/ke/cluster/info
everything displays ok
------------------------------
conf:
....
work.kafka.eagle.offset.storage=kafka
work.kafka.eagle.sasl.enable=false
....
ConsumerGroups 10
------------------------------

conf:
...
work.kafka.eagle.offset.storage=zk
work.kafka.eagle.sasl.enable=false
....
view:
ConsumerGroups 20


This is part of the configuration for understanding the picture, I can send
the complete configuration of the files. Is the essence of the problem
clear?
