### ISSUE TITLE
xml文件报错 1.4.0

### ISSUE THREAD

**Issue by androidZhy** [smartloli/kafka-eagle#255]
<img width="875" alt="微信截图_20191108105253" src="https://user-images.githubusercontent.com/20261434/68445816-eeab6480-0215-11ea-8271-70f0820035c2.png">

**Comment by androidZhy** [comment]
<img width="394" alt="微信截图_20191108111131" src="https://user-images.githubusercontent.com/20261434/68446741-9b86e100-0218-11ea-8896-5822d2ba9cb6.png">

**Comment by androidZhy** [comment]
<img width="956" alt="微信截图_20191108141246" src="https://user-images.githubusercontent.com/20261434/68453935-f7aa2f00-0231-11ea-90e4-295eecfc5e47.png">

**Comment by smartloli** [comment]
fixed it and release by v1.4.1
