### ISSUE TITLE
BrokerServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-2 - ERROR

### ISSUE THREAD

**Issue by EvgenijO** [smartloli/kafka-eagle#259]
ConsumerGroups. Displays incorrectly on several types of authorization simultaneously on Kafka
-------
in kafka
...
listeners=SASL_PLAINTEXT://localhost:6666,SSL://localhost:7777
--------
in Kafka Eagle
BrokerServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-2 - ERROR - Get topic real logsize has error, msg is No resolvable bootstrap urls given in bootstrap.servers
KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-9 - ERROR - For input string: "6666","SS"

**Comment by smartloli** [comment]
Check you kafka broker `server.properties`

**Comment by EvgenijO** [comment]
in kafka
I use several authorization methods at the same time in file server.properties:
...
listeners=SASL_PLAINTEXT://localhost:6666,SSL://localhost:7777
advertised.listeners=SASL_PLAINTEXT://localhost:6666,SSL://localhost:7777
.....

in Kafka Eagle
BrokerServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#3_Worker-2 - ERROR - Get topic real logsize has error, msg is No resolvable bootstrap urls given in bootstrap.servers
KafkaServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-9 - ERROR - For input string: "6666","SS"
