### ISSUE TITLE
When does this framework support Windows

### ISSUE THREAD

**Issue by cocodroid** [smartloli/kafka-eagle#26]
When will this framework work under Windows?thanks

**Comment by smartloli** [comment]
@cocodroid Subsequent releases will be considered.

**Comment by smartloli** [comment]
@cocodroid  Fixed by ![v1.1.8](https://github.com/smartloli/kafka-eagle/tree/v1.1.8)

**Comment by cocodroid** [comment]
@smartloli Thank you very much！
