### ISSUE TITLE
windows上启动问题

### ISSUE THREAD

**Issue by Borische** [smartloli/kafka-eagle#262]
..\log4j.properties
系统找不到指定路径
..\system-config.properties
系统找不到指定路径

麻烦问下怎么解决啊 感谢

**Comment by Dr-kyle** [comment]
环境变量 例如：KE_HOME E:\kafka-eagle-bin-1.4.0\kafka-eagle-web-1.4.0 配置了吗？

**Comment by Borische** [comment]
![image](https://user-images.githubusercontent.com/24266229/69200468-33b88a80-0b76-11ea-97b9-9a0c914f2297.png)
配置了的 怎么还是不行啊 感谢

**Comment by hjhhjhhjh** [comment]
> ![image](https://user-images.githubusercontent.com/24266229/69200468-33b88a80-0b76-11ea-97b9-9a0c914f2297.png)
> 配置了的 怎么还是不行啊 感谢

不要放在Program Files文件夹下,,,,,路径不要有空格
