### ISSUE TITLE
1.4使用mysql驱动一直提示table不存在

### ISSUE THREAD

**Issue by qq297910962** [smartloli/kafka-eagle#269]
![image](https://user-images.githubusercontent.com/39329230/69474373-776ff600-0dfb-11ea-8cfc-7f5969f27e16.png)
数据库是已经连接了 但是一直提示表不存在 难道需要自己手动创建表吗

**Comment by smartloli** [comment]
Check whether the user you connect to MySQL has the permission to automatically create the database or table ?

**Comment by lhzsdnu** [comment]
我也出现这个问题，还是不明白如何解决

**Comment by ixiekun** [comment]
目前我也是一样，一直提示table不存在，而且我允许远程登陆root用户所有权限

**Comment by ixiekun** [comment]
估计MySQL的版本有比较大的关系。mysql5.1无法创建表，mysql5.5可以创建表
