### ISSUE TITLE
kafka上长时间未使用的 consumer group 无法显示

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#270]
kafka中长时间未使用的 consumer group，在页面 Consumers overview 中没有显示，这样导致无法设置告警等。

- 在 kafka-manager 中是有显示的

![image](https://user-images.githubusercontent.com/13871686/69494565-3c072180-0ef8-11ea-9338-259e8f7a3b9b.png)

- kafka-eagle中无显示

![image](https://user-images.githubusercontent.com/13871686/69494926-19770780-0efc-11ea-9d6d-a8eaffa51fab.png)

**Comment by smartloli** [comment]
Kafka will periodically clean up invalid consumer groups.
