### ISSUE TITLE
拉取源代码，进行打包，前端会出现找不到 echarts.min.js

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#271]
拉取源代码，执行 ./build.sh ， 前端访问会有如下问题，请问如何解决，谢谢
![image](https://user-images.githubusercontent.com/13871686/69495802-f81b1900-0f05-11ea-98ae-670d212dc920.png)

**Comment by smartloli** [comment]
The file exists, but the service on the server fails to load. Check if your server has any restrictions.

**Comment by zhiyuan192shine** [comment]
> The file exists, but the service on the server fails to load. Check if your server has any restrictions.

ok, thank you

**Comment by wx2016520** [comment]
将安装目录下/kms/conf/server.xml配置文件中的connectionTimeout值调大重启后强制刷新页面，如果还是不行那说明调得还不够大
