### ISSUE TITLE
在页面发送某些消息到topic时出现错误

### ISSUE THREAD

**Issue by zhangxiatlq** [smartloli/kafka-eagle#272]
在1.4.0版本中，向队列中发送如下消息会发生错误，消息如下：
{"app":"111","clientType":3,"data":"xxxxxxxxx","hostname":"localhost","im":"862175041056083","msgId":"463694459955970048","msgTime":1574387490547}
执行结果：
![image](https://user-images.githubusercontent.com/26112021/69506876-78c03080-0f6b-11ea-8987-b63a00541128.png)

**Comment by zhugezifang** [comment]
最新版本已经解决了 1.4.3
