### ISSUE TITLE
kafka-eagle 当非本地部署时，会导致 echarts.min.js 无法加载

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#274]
kafka-eagle/kms/conf/server.xml 中 Connector 里 connectionTimeout="100"，这个默认值太小，可能网络还未到达就 timeout 了，应该加大此值比较好

**Comment by columbus9963** [comment]
@zhiyuan192shine @smartloli kafka 
eagle echart未加载的问题解决方案可以参考如下这个issue，在kafka eagle server前面加一个类似nginx/envoy的代理服务器就可以解决，这是一个ajax和浏览器兼容方面的问题

https://stackoverflow.com/questions/49706998/how-to-fix-err-invalid-chunked-encoding-error
