### ISSUE TITLE
能否增加指定bootstrap servers的参数

### ISSUE THREAD

**Issue by zhangcl2002** [smartloli/kafka-eagle#276]
使用kafka-eagle监控 k8s上安装的Kafka, 安装kafka后bootstrap server不仅以默认端口暴露，而是增加了一个端口，这样每个broker Server暴露了本身的9092端口，同时增加了一个反向代理IP和端口。安装kafka-eagle后，如果有参数文件中能够指定bootstrap server的ip和端口就好了。 

另外不知道能否也看看使用容器安装kafka-eagle呀，能更方便。 谢谢

**Comment by huaxuehuaxue** [comment]
+1 ，同需求。

**Comment by yichingwu** [comment]
+1 因為我們有不同網段
