### ISSUE TITLE
现在钉钉加了安全设置，无法发送消息

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#277]
![image](https://user-images.githubusercontent.com/13871686/69897040-3ccd0700-1381-11ea-8cca-195e805c6baa.png)
支持以上三种方式，

目前通过修改源码才能发送告警

**Comment by Tiakon** [comment]
在 v1.4.6 版本中 添加Ip地址，复制Webhook地址到 ke ，告警就可以生效了，亲测有效
