### ISSUE TITLE
can not remove topic

### ISSUE THREAD

**Issue by liansghuaifan** [smartloli/kafka-eagle#28]
i have created a topic named "test",when i want to remove it ,web prompt input Admin token, i get an Internal server error ~~ after  i put my token,can you help me?

**Comment by liansghuaifan** [comment]
i try again use   kafka.eagle.topic.token of  system-config.properties  ,i can delete the topic, but i can not delete again when i  recreate  a name the same topic as before.

**Comment by smartloli** [comment]
All zookeeper stores are Kafka metadata information.
