### ISSUE TITLE
kafka-eagle 从1.4.1 升级到1.4.2 Kafka Performance 图表无法展示

### ISSUE THREAD

**Issue by zhiyuan192shine** [smartloli/kafka-eagle#283]
kafka-eagle 从1.4.1 升级到1.4.2 Kafka  Metric 中 无任何图表展示，在 1.4.1 中图表展示是 ok 的

1.4.2 展示如下：
![image](https://user-images.githubusercontent.com/13871686/70604055-da9ebc80-1c32-11ea-9da5-c020829ab8c2.png)

**Comment by blareck** [comment]
你试试把 server.xml 中的connectionTimeout 改到10000试试

**Comment by zhiyuan192shine** [comment]
> 你试试把 server.xml 中的connectionTimeout 改到10000试试

这个参数我安装的时候就改了，还是不行， 1.4.1 改了是 ok 的

**Comment by smartloli** [comment]
@zhiyuan192shine 
At present, the latest version of Kafka eagle is V1.4.1, and v1.4.2 is currently in the development stage. Some bugs have not been fixed, so you need to read the source code.
