### ISSUE TITLE
Email Alarm type 如何设定?

### ISSUE THREAD

**Issue by yichingwu** [smartloli/kafka-eagle#290]
1.4.2 version, 不确定 email type 下， Alarm URL 该如何填写?
预期是不是应该是 mail server 及相关帐号的设定

![image](https://user-images.githubusercontent.com/829351/71465045-76fdbd00-27f6-11ea-8926-222db840cf9c.png)

**Comment by smartloli** [comment]
Demo email or webhook restful api:
```
http://127.0.0.1:10086/email?address="xxx@gmail.com"&msg="alarm msg"
```

**Comment by yichingwu** [comment]
抱歉，那 mail server 跟 可寄信的帐号及密码需要再哪边设定?
设定画面上已经有一个 Address 来设定收件者的 email address, 为什麽还要设定  http://127.0.0.1:10086/email?address="xxx@gmail.com"&msg="alarm msg test"

**Comment by smartloli** [comment]
Kafka Eagle Alarm URL Setting:
```
http://127.0.0.1:10086/email
```
And you alarm server( such as email server or webhook server) must be provided a restful api:
```
http://127.0.0.1:10086/email?address="xxx@gmail.com"&msg="alarm msg test"
```

**Comment by Husky-gaga** [comment]
解决了吗？我也遇到这个问题了，能解答下吗

**Comment by yichingwu** [comment]
hi @Husky-gaga 目前找不到有提供 restful api 的 mail server, 所以，放棄使用了。
