### ISSUE TITLE
kafkasql 查询不显示任何内容，查看日志也没有报错和相关查询信息

### ISSUE THREAD

**Issue by superfenv** [smartloli/kafka-eagle#292]
![Uploading image.png…]()
![微信图片_20191230120401](https://user-images.githubusercontent.com/30689249/71567775-8170cd00-2afc-11ea-94ee-25a3ca271f9b.png)

**Comment by smartloli** [comment]
You have nginx proxy restrictions or other restrictions on your deployment server.

**Comment by superfenv** [comment]
No nginx is used, a message is generated on a topic, and then kafkasql is
used to query whether the topic has data and no results are returned. But
you can see the number of bytes and the number of messages in the topic
list. Is it used improperly?

smartloli <notifications@github.com> 于2020年1月1日周三 下午5:14写道：
