### ISSUE TITLE
how to enable debugging mode ? 

### ISSUE THREAD

**Issue by snipercy** [smartloli/kafka-eagle#3]

**Comment by smartloli** [comment]
@snipercy Set ```log4j.properties``` file, ```log4j.rootLogger=INFO, SLOG, CONSOLE, SERROR``` replace to ```log4j.rootLogger=DEBUG, SLOG, CONSOLE, SERROR```

**Comment by smartloli** [comment]
@snipercy  Finally, thank you very much for your feedback.
