### ISSUE TITLE
邮件告警配置

### ISSUE THREAD

**Issue by StefanOrmsby** [smartloli/kafka-eagle#302]
请问在最新的1.4.2版本里面，配置邮件告警还需要在配置文件里面配置吗，还是只需要在alarm界面里面配置？具体应该怎么配置呢

**Comment by lyicy** [comment]
同问 Alarm URL 是干什么用的 求解

**Comment by smartloli** [comment]
https://www.cnblogs.com/smartloli/p/12110570.html
