### ISSUE TITLE
关于设置cluster Kafka告警

### ISSUE THREAD

**Issue by peiyuanzheng** [smartloli/kafka-eagle#308]
新手请问下，设置cluster Kafka告警时，"Server" 这一栏是不是填写kafka brokers的ip:port list ？
![image](https://user-images.githubusercontent.com/4730528/75410050-9aa7c580-5955-11ea-8d96-d5e36d1f1e50.png)

**Comment by smartloli** [comment]
For example:
```
192.168.1.100:9092,192.168.1.101:9092,192.168.1.103:9092 
```

**Comment by peiyuanzheng** [comment]
Thanks
