### ISSUE TITLE
How to set topic alarm if topic's producer rate is out of range?

### ISSUE THREAD

**Issue by peiyuanzheng** [smartloli/kafka-eagle#309]
I want to set up topic alarm if topic's producer rate is out of range. Does kafka-eagle support this?

For example, topic_A's producer rate is [100, 1000] msg/min normally. When it's out of this range, I could get alarm messge.

**Comment by smartloli** [comment]
fine, add this features in v1.4.5

**Comment by peiyuanzheng** [comment]
Thanks a lot!
