### ISSUE TITLE
吐槽一下

### ISSUE THREAD

**Issue by littlejiangyuan** [smartloli/kafka-eagle#31]

**Comment by flinkers** [comment]
@littlejiangyuan 就你这心态，真不敢恭维，还来Issues上喷，Issues你给你来喷的吗？官网打不开自己不会动脑子想一想，不会用代理？源代码都托管了，自己不会看，不会调试，自己不会虚心学习，来这里喷作者？作者得罪你了，免费给你用，你有出钱还是怎么滴？懂得尊重一下别人的劳动成果吗？ @smartloli （如果觉得我说的不妥，可以把这条Issues删掉，看到这种伸手拿，还嫌弃这不好那不好的人就烦）

**Comment by littlejiangyuan** [comment]
@flinkers 我这是喷吗，我只是吐槽一些问题，有问题不让说？linux免费给你用你就只能说它好处，不能指出不足，这么多开源软件你就只能跪舔不能吐槽。我对事不对人，我尊重别人成果，但是问题太多我也指出来

**Comment by flinkers** [comment]
@littlejiangyuan 自己还是小孩子？有问题自己动脑子先想，其他人怎么没遇到，就算遇到也没见来Issues喷，自己不动脑子想，就算作者写的工具再优秀，对你也是浪费
