### ISSUE TITLE
Topic-Manager版本支持问题

### ISSUE THREAD

**Issue by ywywn** [smartloli/kafka-eagle#319]
Kafka Eagle ：1.3.4
Kafka ：0.10.1（Scala 2.11）
在正常安装Kafka及Kafka Eagle后其他功能均正常，在使用Topic-Manager对topic进行配置更改时出现问题

1. add config中无法配置，message提示{“type”."ADD","value"."org.apache.kafka.common.errors.UnsupportedVersionException: The broker does not support ALTER_CONFIG"}，相关配置不成功，但是在后台使用kafka-topic.sh可进行配置添加操作；

2. delete config操作虽然提示{“type”."DELETE","value"."SUCCESS"}但实际未删除，后台查询配置项依然存在，后台执行kafka-topic.sh可进行删除；

3. describe config可进行正常操作；

在项目中注意到kafka版本设置为2.0.0，是否对此有影响？
https://github.com/smartloli/kafka-eagle/blob/v1.3.4/kafka-eagle-common/pom.xml

**Comment by smartloli** [comment]
Yes, some properties lower than version 2.0.0 may not be available.

**Comment by ywywn** [comment]
> Yes, some properties lower than version 2.0.0 may not be available.

感谢解答。
