### ISSUE TITLE
本地运行重定向多次

### ISSUE THREAD

**Issue by wangshuaimade** [smartloli/kafka-eagle#325]
本地打包运行时，URL重定向了多次。使用版本为kafka-ealge-1.4.5。

**Comment by haiping216** [comment]
curl -I -u admin:123456 'http://10.0.122.8:8048/ke/'
```
HTTP/1.1 302 
Set-Cookie: MFSHIROSID=74a114c1-05d3-4304-b6f6-fa479b95f6ac; Path=/ke; Max-Age=180000; Expires=Sat, 11-Apr-2020 10:15:16 GMT; HttpOnly
Location: /ke/account/signin?/ke/
Transfer-Encoding: chunked
Date: Thu, 09 Apr 2020 08:15:16 GMT
```

curl -I -u admin:123456 'http://10.0.122.8:8048/ke/account/signin?/ke/'
`HTTP/1.1 200 
Set-Cookie: MFSHIROSID=3cc96550-f51e-46bf-90b3-8069d5fc6d85; Path=/ke; Max-Age=180000; Expires=Sat, 11-Apr-2020 12:03:33 GMT; HttpOnly
vary: accept-encoding
Content-Type: text/html;charset=UTF-8
Content-Language: en-US
Content-Length: 2908
Date: Thu, 09 Apr 2020 10:03:33 GMT
`
