### ISSUE TITLE
使用mysql数据库后无法使用系统

### ISSUE THREAD

**Issue by stuqqq** [smartloli/kafka-eagle#326]
mysql版本为8.0.12
使用配置文件默认mysql配置无法登陆使用系统，后来看网上说修改drive为com.mysql.cj.jdbc.Driver后依旧无法使用

**Comment by Tiakon** [comment]
> mysql版本为8.0.12
> 使用配置文件默认mysql配置无法登陆使用系统，后来看网上说修改drive为com.mysql.cj.jdbc.Driver后依旧无法使用

是不是mysql的版本太高了， 5.7.20  MySQL 没这问题

**Comment by AthenaJava** [comment]
目前使用mysql版本为8.0.12，修改drive为com.mysql.cj.jdbc.Driver后依旧无法使用，并且增加mysql-connector-java-8.0.20.jar驱动可以成功（将驱动放入war包lib目录下，因为每次启动都会重新解压war文件），但是先关表结构脚本不存在，下载的安装包也不存在，请问如何能到拿到数据库脚本？

**Comment by mrzhang638993** [comment]
我的mysql版本是5.1.73 ，启动的时候kafka-eagle对应的是不会进行初始化操作的。

**Comment by GavinAlison** [comment]
我的mysql版本是5.6，启动的时候kafka-eagle对应的是不会进行初始化操作的。 系统启动不了

**Comment by bigdimple** [comment]
我也遇到了相同的问题，kafka-eagle是2.0.5的版本，mysql是5.7.34。启动没有执行任何初始化操作脚本
![image](https://user-images.githubusercontent.com/28156478/121457231-ead75980-c9d9-11eb-823d-39b1f1488052.png)
