### ISSUE TITLE
KafkaConsumerAdapter执行消费时，若无新数据写入便消费不出来数据

### ISSUE THREAD

**Issue by wangshuaimade** [smartloli/kafka-eagle#328]
kafka-eagle-1.4.5版本，个人写了一套kafka消费逻辑，可以支持即使无数据写入也可以消费最新的N条数据，仅供参考。
` public static List<JSONArray> executor(KafkaSqlInfo kafkaSql) {
        List<JSONArray> messages = new ArrayList<>();
        System.out.println("---->sqlinfo:" + kafkaSql);
        Properties props = new Properties();
        props.put(ConsumerConfig.GROUP_ID_CONFIG, Kafka.KAFKA_EAGLE_SYSTEM_GROUP);
        props.put(CommonClientConfigs.BOOTSTRAP_SERVERS_CONFIG, kafkaService.getKafkaBrokerServer(kafkaSql.getClusterAlias()));
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getCanonicalName());
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getCanonicalName());
        props.put(ConsumerConfig.ENABLE_AUTO_COMMIT_CONFIG, false);
        if (kafkaSql.getLimit() <= 50) {
            props.put(ConsumerConfig.MAX_POLL_RECORDS_CONFIG, 1);
        } else if (kafkaSql.getLimit() > 50 && kafkaSql.getLimit() <= 100) {
            props.put("max.poll.records", 50);
        } else if (kafkaSql.getLimit() > 100 && kafkaSql.getLimit() <= 200) {
            props.put("max.poll.records", 100);
        } else if (kafkaSql.getLimit() > 200 && kafkaSql.getLimit() <= 500) {
            props.put("max.poll.records", 300);
        } else {
            props.put("max.poll.records", 500);
        }

        if (SystemConfigUtils.getBooleanProperty("kafka.eagle.sql.fix.error")) {
            props.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, Kafka.EARLIEST);
        }
        if (SystemConfigUtils.getBooleanProperty(kafkaSql.getClusterAlias() + ".kafka.eagle.sasl.enable")) {
            kafkaService.sasl(props, kafkaSql.getClusterAlias());
        }
        KafkaConsumer<String, String> consumer = new KafkaConsumer<>(props);
        List<TopicPartition> topics = new ArrayList<>();
        for (Integer partition : kafkaSql.getPartition()) {
            TopicPartition tp = new TopicPartition(kafkaSql.getTableName(), partition);
            topics.add(tp);
        }
        consumer.assign(topics);
        List<TopicPartition> seekTPList = new ArrayList<>(topics.size());
        for (TopicPartition tp : topics) {
            Map<TopicPartition, Long> endOffsetsMap = consumer.endOffsets(Collections.singleton(tp));
            Long endOffset = endOffsetsMap.get(tp);
            Map<TopicPartition, Long> startOffsetsMap = consumer.beginningOffsets(Collections.singleton(tp));
            Long startOffset = startOffsetsMap.get(tp);
            if (endOffset.equals(0) || endOffset - startOffset <= 0){
                continue;
            }
            long offset;
            if ((endOffset - kafkaSql.getLimit()) > 0 && (endOffset - kafkaSql.getLimit()) > startOffset){
                offset = endOffset - kafkaSql.getLimit();
            } else if ((endOffset - kafkaSql.getLimit()) <= startOffset){
                offset = startOffset;
            } else if (startOffset != 0){
                offset = startOffset;
            } else {
                offset = 0;
            }
            seekTPList.add(tp);
            consumer.seek(tp,offset);
        }

        if (seekTPList.size() == 0) {
            consumer.close();
            return messages;
        }
        JSONArray datasets = new JSONArray();
        Map<TopicPartition, AtomicInteger> indexMap = new HashMap<>(topics.size());
        boolean flag = true;
        int index = 0;
        while (flag) {
            ConsumerRecords<String, String> records = consumer.poll(Duration.ofMillis(Kafka.TIME_OUT));
            for (ConsumerRecord<String, String> record : records) {
                System.out.println(record.topic() + record.partition() + "---" + record.value());
                JSONObject object = new JSONObject();
                object.put(TopicSchema.MSG, record.value());
                object.put(TopicSchema.OFFSET, record.offset());
                object.put(TopicSchema.PARTITION, record.partition());
                datasets.add(object);
                TopicPartition recordTopicPartition = new TopicPartition(record.topic(), record.partition());
                AtomicInteger count = indexMap.get(recordTopicPartition);
                if (count == null) {
                    indexMap.put(recordTopicPartition, new AtomicInteger(1));
                } else {
                    count.getAndIncrement();
                    indexMap.put(recordTopicPartition, count);
                }
                if (indexMap.get(recordTopicPartition).intValue() < kafkaSql.getLimit()) {
                    try {
                        consumer.commitAsync();
                    } catch (Exception e){
                        e.printStackTrace();
                        consumer.commitSync();
                    }
                    Map<TopicPartition, Long> endOffsetsMap = consumer.endOffsets(Collections.singleton(recordTopicPartition));
                    Long endOffset = endOffsetsMap.get(recordTopicPartition);
                    Map<TopicPartition, Long> startOffsetsMap = consumer.beginningOffsets(Collections.singleton(recordTopicPartition));
                    Long startOffset = startOffsetsMap.get(recordTopicPartition);
                    if (startOffset + indexMap.get(recordTopicPartition).longValue() == endOffset) {
                        index++;
                        consumer.pause(Collections.singleton(recordTopicPartition));
                    }
                } else if (indexMap.get(recordTopicPartition).intValue() == kafkaSql.getLimit()) {
                    index++;
                    consumer.pause(Collections.singleton(recordTopicPartition));
                }
                if (index == seekTPList.size()) {
                    flag = false;
                }
            }
        }
        consumer.close();
        messages.add(datasets);
        return messages;
    }`

**Comment by wangshuaimade** [comment]
该段代码亲测通过

**Comment by smartloli** [comment]
It is best to submit [PR](https://github.com/smartloli/kafka-eagle/pulls) .
