### ISSUE TITLE
ZKPoolUtils.localhost-startStop-1 - ERROR - Unable to connect to ...

### ISSUE THREAD

**Issue by xf20110925** [smartloli/kafka-eagle#33]
[2017-10-19 11:40:00] MBeanQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-1 - ERROR - Collector mbean data has error,msg is
### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 2

~

**Comment by smartloli** [comment]
@xf20110925  Please open you kafka cluster jmx port. Such as :
```bash
vi kafka-server-start.sh
...
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
    #export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
fi
```
