### ISSUE TITLE
建议新增功能：kafka web UI 上能查看offset的情况

### ISSUE THREAD

**Issue by 1063238280** [smartloli/kafka-eagle#331]
kafka eagle webUI 十分干净有效，的确是个很好的工具。如果能加上offset的监控，那就完美了！完全可以替代Apache 官方提供的监控方案

**Comment by smartloli** [comment]
This feature exists, you can view it in the consumers.
[https://docs.kafka-eagle.org/3.quick-start/3.consumer](https://docs.kafka-eagle.org/3.quick-start/3.consumer)
![Consumer Offsets](https://gblobscdn.gitbook.com/assets%2F-LjfmXHRajdxow3o-cxI%2F-LjfrvZnr8VnQqA2gTze%2F-LjfrwYl50Cs-WewvUBT%2Foffset_detail@2x.png?generation=1563030447730946&alt=media)

**Comment by 1063238280** [comment]
> This feature exists, you can view it in the consumers.
> https://docs.kafka-eagle.org/3.quick-start/3.consumer
> ![Consumer Offsets](https://camo.githubusercontent.com/858651d4208b6100b09f4398b8adef2204706bbe/68747470733a2f2f67626c6f627363646e2e676974626f6f6b2e636f6d2f6173736574732532462d4c6a666d584852616a64786f77336f2d6378492532462d4c6a6672765a6e7238566e5171413267547a652532462d4c6a667277596c353043732d576577765542542532466f66667365745f64657461696c4032782e706e673f67656e65726174696f6e3d3135363330333034343737333039343626616c743d6d65646961)

建议offset的视图放到consumers的二级菜单中，直接可以看到所有消息的offset的使用情况。
