### ISSUE TITLE
topic 已经被删除了，但仍然显示在主页面 top10 列表中

### ISSUE THREAD

**Issue by leiwangouc** [smartloli/kafka-eagle#333]
![image](https://user-images.githubusercontent.com/19704741/79443112-003a3900-800c-11ea-898c-1610274b88db.png)

如图，总共就 7 个topic，但 列表中有 9 个，两个是已经被删除了的

**Comment by SatoPendragon** [comment]
我也遇到过，我这边的情况应该是延迟了，后来就正常了

**Comment by leiwangouc** [comment]
我这边过了一天了也还没正常。这个列表应该是存在 kafka-eagle 的后台数据库里，但不知道为啥不更新。

**Comment by javajian07** [comment]
Kafka Eagle V1.4.7 version （Add Producers Feature.）  增加生产者的特性  为啥无效
