### ISSUE TITLE
KSQL 没有响应

### ISSUE THREAD

**Issue by leiwangouc** [smartloli/kafka-eagle#334]
![image](https://user-images.githubusercontent.com/19704741/79547891-2cff5680-80c7-11ea-80e3-2cbab851683a.png)
写了这个 KSQL 后点 Qureyr 怎么没有任何反映呢。topic 中是有数据的。

**Comment by smartloli** [comment]
Static resources are not loaded, check if the server has `Nginx` restrictions?

**Comment by leiwangouc** [comment]
I don't quite understand. 
Deed i need to intstall a Nginx? How can i check the Nginx restrictions?
