### ISSUE TITLE
can not show consumer offset

### ISSUE THREAD

**Issue by ricoisme** [smartloli/kafka-eagle#34]
Hi

I can not show consumer offset on my cluster 2 and cluster 3 and I got error as below:
ERROR [OffsetsQuartz.org.springframework.scheduling.quartz.SchedulerFactoryBean#0_Worker-3] - Quartz statistics offset has error,msg is null.
![image](https://user-images.githubusercontent.com/17023972/31888532-0b02e4e2-b82f-11e7-82fd-dbe121773482.png)

![image](https://user-images.githubusercontent.com/17023972/31888863-3e665908-b830-11e7-9222-039041ec3f47.png)

is this as expect?

but i can get correct consumer offset on cluster 1 if I changed cluster from cluster 2 to cluster 1.

my  system-config.properties as below:
######################################
# multi zookeeper&kafka cluster list
######################################
kafka.eagle.zk.cluster.alias=cluster1,cluster2,cluster3
cluster1.zk.list=192.168.137.182:2181,192.168.137.182:2182,192.168.137.182:2183
cluster2.zk.list=192.168.137.183:2181,192.168.137.183:2182,192.168.137.183:2183
cluster3.zk.list=192.168.137.184:2181,192.168.137.184:2182,192.168.137.184:2183

######################################
# zk client thread limit
######################################
kafka.zk.limit.size=25

######################################
# kafka eagle webui port
######################################
kafka.eagle.webui.port=8999

######################################
# kafka offset storage
######################################
kafka.eagle.offset.storage=kafka

by the way , I can get correct consumer offset on each cluster via kafka-manager.
![image](https://user-images.githubusercontent.com/17023972/31888829-1acb50fc-b830-11e7-8913-e1bd75c5cb08.png)

thanks

update:

it seems only response first cluster alias.

**Comment by smartloli** [comment]
@ricoisme What's your Kafka version number?

**Comment by ricoisme** [comment]
kafka:0.10.2.0

**Comment by owenxiaolei** [comment]
same problem 
kafka:0.10.0.0

what can i do？
