### ISSUE TITLE
统计出现负数，如何解决

### ISSUE THREAD

**Issue by huangzhengshun** [smartloli/kafka-eagle#340]
![image](https://user-images.githubusercontent.com/52736502/80047563-56453a00-8540-11ea-81f5-4938421c684c.png)
![image](https://user-images.githubusercontent.com/52736502/80047588-63fabf80-8540-11ea-8b7c-4a01c94b9f52.png)

**Comment by Tiakon** [comment]
我也遇到了，修改 test-cluster.kafka.eagle.offset.storage 这个参数后就遇见了。
kafka          ： 4.0.0-1.4.0.0.p0.1（2.1.0+kafka4.0.0+17）
zookeeper ：  3.4.5-cdh5.15.2
