### ISSUE TITLE
kafka eagle1.3.7到1.4.6出现下面的报错导致很多功能不可用，例如topic list失败，comsumer list一直显示Processing,首页DashBoard broker,topic,zookeeper等数量均显示0

### ISSUE THREAD

**Issue by takehub** [smartloli/kafka-eagle#342]
![TIM图片20200503211844](https://user-images.githubusercontent.com/8803969/80932607-c54d4900-8df2-11ea-8888-12260fc34feb.png)
![TIM图片20200503211852](https://user-images.githubusercontent.com/8803969/80932703-342aa200-8df3-11ea-874f-adc07922c1fe.png)

CDH版本，5.16.1 （已开启Kerberos认证）
Kafka版本：1.0.1 + kafka3.1.0
kafka-eagle：1.3.7到1.4.6均存在此问题

**Comment by smartloli** [comment]
https://docs.kafka-eagle.org/2.env-and-install/5.security
