### ISSUE TITLE
Kafka Eagle1.3.5,1.3.6后台报错

### ISSUE THREAD

**Issue by takehub** [smartloli/kafka-eagle#343]
![微信截图_20200504104134](https://user-images.githubusercontent.com/8803969/80932875-f4b08580-8df3-11ea-8f21-956ad9d72d04.png)

![微信截图_20200504104324](https://user-images.githubusercontent.com/8803969/80932934-288bab00-8df4-11ea-9758-6d4150c8dd2c.png)

CDH：5.16.1（已开启Kerberos）
Kafka：1.0.1 + Kafka3.1.0
Kafka-Eagle：1.3.5，1.3.6

**Comment by smartloli** [comment]
https://docs.kafka-eagle.org/2.env-and-install/5.security

**Comment by takehub** [comment]
![1](https://user-images.githubusercontent.com/8803969/81246292-bd3b1680-9049-11ea-8745-07023b3e9879.png)

因为我的zk也开启了Kerberos认证，所以我必须把Kerberos认证的配置拿出来作为单独的配置文件，如下：

![2](https://user-images.githubusercontent.com/8803969/81246344-e65ba700-9049-11ea-9c02-f0bd8f44fe8c.png)

我已经这么做了，但是还是报上面的错误
