### ISSUE TITLE
请问kafka eagle必须要安装在集群内部的主机吗？我选了集群外面的一台主机，结果报错找不到kdc

### ISSUE THREAD

**Issue by takehub** [smartloli/kafka-eagle#345]
![微信截图_20200504200932](https://user-images.githubusercontent.com/8803969/80964318-36b4e800-8e43-11ea-8361-01f4f17ee4c4.png)

**Comment by takehub** [comment]
（版本信息）
CDH：5.16.1（已开启Kerberos）
Kafka：1.0.1 + Kafka3.1.0
Kafka-Eagle：1.3.5

**Comment by smartloli** [comment]
[Kerberos Configure](http://www.kafka-eagle.org/articles/docs/installation/security.html)
