### ISSUE TITLE
ZK详细信息和监控图表（metrics）无法显示

### ISSUE THREAD

**Issue by takehub** [smartloli/kafka-eagle#346]
![image](https://user-images.githubusercontent.com/8803969/81028555-8f709900-8eb4-11ea-9e79-d534197dffc1.png)

![image](https://user-images.githubusercontent.com/8803969/81028586-ac0cd100-8eb4-11ea-979c-0e5e47d9f270.png)
![image](https://user-images.githubusercontent.com/8803969/81028602-c181fb00-8eb4-11ea-922e-f6e16c96f3b2.png)
日志中报错：
![image](https://user-images.githubusercontent.com/8803969/81028642-e6766e00-8eb4-11ea-8e1d-aa03be64b3b7.png)

Kafka-Eagle：1.3.5
CDH：5.14.2（已开启Kerberos认证）
Kafka：1.0.1 + kafka3.1.0

PS:在CDH5.16.1（已开启Kerberos认证），Kafka（1.0.1+kafka3.1.0），kafka-eagle（1.3.5）中可以正常展示

**Comment by takehub** [comment]
考虑可能是zk数量和kafka数量不一致导致的（zk是5个节点，kafka是7个节点），但是在测试集群测试了下（kafka4个节点，zk3个节点）没有发现此问题。
测试集群：
CDH5.16.1（已开启Kerberos认证），Kafka（1.0.1+kafka3.1.0），kafka-eagle（1.3.5）

**Comment by smartloli** [comment]
Maybe you can upgrade [lastest version](http://www.kafka-eagle.org/).
