### ISSUE TITLE
kafka-eagle 1.4.6配置ssl后报错

### ISSUE THREAD

**Issue by zlandyberg** [smartloli/kafka-eagle#349]
kafka-eagle 1.4.6
kafka version 2.12
配置信息
![image](https://user-images.githubusercontent.com/23549720/81504113-0aeda280-931a-11ea-823a-efe3e595f200.png)
日志如下
![image](https://user-images.githubusercontent.com/23549720/81504187-6e77d000-931a-11ea-9cc2-7a9c979c2d8e.png)
![image](https://user-images.githubusercontent.com/23549720/81504226-99faba80-931a-11ea-8bd0-a834cd21ff16.png)
![image](https://user-images.githubusercontent.com/23549720/81504233-a41cb900-931a-11ea-8cbe-9931ce671970.png)
使用java的kafka生产者和消费者都可连接到kafka，用kafka-eagle连接不到ssl

**Comment by smartloli** [comment]
Fixed by [v1.4.7](https://github.com/smartloli/kafka-eagle/projects/5), If you want to use it in advance, you can run `./build.sh` to compile the master branch.

**Comment by zlandyberg** [comment]
> @zlandyberg
> Fixed by [v1.4.7](https://github.com/smartloli/kafka-eagle/projects/5), If you want to use it in advance, you can run `./build.sh` to compile the master branch.

怎么配置zookeeper的ssl呢 我看到issue#238 是v1.4.0支持zookeeper ssl但没找到如何配置zookeeper的ssl

**Comment by zlandyberg** [comment]
> @zlandyberg
> Fixed by [v1.4.7](https://github.com/smartloli/kafka-eagle/projects/5), If you want to use it in advance, you can run `./build.sh` to compile the master branch.

使用1.4.7后报错如下
![image](https://user-images.githubusercontent.com/23549720/82002088-71aeeb00-968f-11ea-9d2c-b2add103c7a2.png)

**Comment by smartloli** [comment]
Use the latest released [v1.4.7](https://github.com/smartloli/kafka-eagle-bin/archive/v1.4.7.tar.gz), and [SSL](http://www.kafka-eagle.org/articles/docs/installation/security.html) configure.
