### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by LegendJ** [smartloli/kafka-eagle#35]
**while running the web project in idea**, visiting localhost:8080,I got an error shows too many redirects.
Broswer had been redirected to "localhost:8080/ke/account/signin?/ke/accounts/signin" , which supposed to be "localhost:port/ke/account/singin?/ke",I guess , cause that **when I package and deploy it in tomcat server** , I made it to visit the web UI, and it shows like that. 
- Is there anything wrong with the signin logic,which cause the problem of redircts?
- btw, I use nested tomcat environment , and I can visit static resources like pictures via localhost:8080/media/img/xxx.png

**Comment by smartloli** [comment]
@LegendJ ```http://host:port/ke```

**Comment by LegendJ** [comment]
I still got this error while running project in IDEA，and everything were fine while deploy by war though. 
- I set an breakpoint in SSOFilter.doFilter method and debug it，finding that redirect problem happened there. 
- Could u please show me your tomcat configurations? I think there must be something wrong with the directory name(contextPath) upon my configuration. Any help will be appreciated!

**Comment by LegendJ** [comment]
@smartloli 
It's okay now After downloading a new Tomcat. Thanks anyway!

**Comment by smartloli** [comment]
@LegendJ Thank you very much for your feedback.
