### ISSUE TITLE
web可以访问，但输入帐号密码之后跑很久，最后甚麽都没有跑出来（出现空白页）

### ISSUE THREAD

**Issue by ghost** [smartloli/kafka-eagle#351]
以下是ke_console.out的结果
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 1: OpenJDK：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 2: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 3: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 4: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 5: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 6: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 7: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 8: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 9: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 10: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 11: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 12: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 13: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 14: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 15: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 16: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 17: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 18: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 19: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 20: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 21: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 22: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 23: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 24: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 25: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 26: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 27: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 28: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 29: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 30: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 31: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 32: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 33: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 34: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 35: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 36: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 37: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 38: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 39: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 40: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 41: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 42: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 43: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 44: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 45: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 46: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 47: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 48: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 49: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 50: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 51: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 52: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 53: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 54: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 55: 15-May-2020：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 56: 2020-05-15：命令找不到
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 57: 未预期的字组「(」附近有语法错误
/home/standalone/kafka-eagle/kafka-eagle-web/target/kafka-eagle/logs/ke_console.out: 列 57: `2020-05-15 11:09:26 INFO  [PostProcessorRegistrationDelegate$BeanPostProcessorChecker.mroot@standalone:/home/stroot@staroot@standalone:/home/stanroot@sroot@sroot@starorootrororootrootrororoot@root@standalone:/home/standaloroot@standalone:/hroot@standalone:/home/standaloroot@sroot@standalone:/home/standroot@standalone:/home/standaloroo

**Comment by appleliou** [comment]
![image](https://user-images.githubusercontent.com/65382646/82034535-e22a2c00-96d0-11ea-8ad7-b312845cb21b.png)

the web is a blank page :(

**Comment by shouer-kong** [comment]
检查一下配置文件的kafka.eagle.url，路径是否为你安装kafka-eagle的路径
