### ISSUE TITLE
Can't get Consumers information..

### ISSUE THREAD

**Issue by spring-bu** [smartloli/kafka-eagle#352]
Cluster info include zk status , kafka topic is nomal.
 
![image](https://user-images.githubusercontent.com/37682426/82172010-87284d00-98fb-11ea-964d-82c9fb1b4304.png)

but can't get consumer info.

![image](https://user-images.githubusercontent.com/37682426/82172022-914a4b80-98fb-11ea-9ea9-53e3f3fd2cf5.png)

**Comment by smartloli** [comment]
![image](https://user-images.githubusercontent.com/16030669/82470569-1dc15d80-9af8-11ea-87e5-39114370bb7d.png)

[Installation](http://www.kafka-eagle.org/articles/docs/installation/linux-macos.html)

**Comment by spring-bu** [comment]
So sad, even I set  

```
mycluster1.kafka.eagle.offset.storage=kafka
```

or set this:

```
mycluster1.kafka.eagle.offset.storage=zk
```

Still not work...
