### ISSUE TITLE
 Kafka Eagle V1.4.7 version, 

### ISSUE THREAD

**Issue by javajian07** [smartloli/kafka-eagle#354]
Add Producers Feature.    生产者特性为啥无效

**Comment by smartloli** [comment]
![image](https://user-images.githubusercontent.com/16030669/82470338-cb803c80-9af7-11ea-8bb1-03ba04b1e6af.png)

**Comment by javajian07** [comment]
![image](https://user-images.githubusercontent.com/33216997/82472253-7bef4000-9afa-11ea-8b64-9d72530b7ecb.png)
我这个配置正确吗
