### ISSUE TITLE
点击界面运行错误日志

### ISSUE THREAD

**Issue by javajian07** [smartloli/kafka-eagle#355]
2020-05-19 05:36:00 ERROR [Mx4jServiceImpl.org.springframework.scheduling.quartz.SchedulerFactoryBean#1_Worker-10] - JMX service url[192.168.59.15:-1] create has error,msg is null
java.lang.ClassCastException

**Comment by smartloli** [comment]
Please open kafka jmx port:
```
vi kafka-server-start.sh
...
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
fi
```
[Metrics](http://www.kafka-eagle.org/articles/docs/quickstart/metrics.html)
