### ISSUE TITLE
主题删除界面依然显示在top里面

### ISSUE THREAD

**Issue by huangzhengshun** [smartloli/kafka-eagle#358]
![image](https://user-images.githubusercontent.com/52736502/82624126-69692980-9c14-11ea-887e-ac0c3841349f.png)
原先测试时有多个主题，后面删除只剩下4个主题，主题列表显示正常，仪表盘那里依然显示之前测试的主题的top

**Comment by smartloli** [comment]
fixed by [v1.4.7](https://github.com/smartloli/kafka-eagle-bin/archive/v1.4.7.tar.gz)
 http://www.kafka-eagle.org/articles/docs/changelog/changelog.html
