### ISSUE TITLE
添加topic capacity告警时有bug

### ISSUE THREAD

**Issue by jsdtcx** [smartloli/kafka-eagle#360]
![IMG_20200525_170404](https://user-images.githubusercontent.com/65941543/82868744-c73a9180-9ef2-11ea-8b29-12642554cb5d.jpg)
当选择新增Topic capacity告警时，这边的条件判断最终会走到第二个的else分支，导致value值是空的，第二个if应该用else if

**Comment by jsdtcx** [comment]
1.4.7版本

**Comment by firehalt** [comment]
安装后Metrics、BScreen都没有数据，你那边有吗
