### ISSUE TITLE
关于url 访问的默认网关

### ISSUE THREAD

**Issue by alinlapland** [smartloli/kafka-eagle#361]
在 centos 中 ，启用 kafka eagle 后， 浏览的url 会默认使用 eth0 默认的，可是我想使用其他的网关，这个该怎么设置？

**Comment by firehalt** [comment]
安装后Metrics、BScreen都没有数据，你那边有吗

**Comment by alinlapland** [comment]
有的，另外 这个问题我直接使用docker 映射出来 ，可以直接用 服务器 ip 访问了

**Comment by firehalt** [comment]
我的就没有数据

![image](https://user-images.githubusercontent.com/29405113/83594239-4d10a980-a591-11ea-9bf4-692974de5508.png)
![image](https://user-images.githubusercontent.com/29405113/83594277-63b70080-a591-11ea-8730-82d6736b8c8c.png)

**Comment by alinlapland** [comment]
额， 你的 cluster 有显示信息吗？ jvm 开了吗？

**Comment by firehalt** [comment]
你邮箱多少？点击cluster数据很久才出来，还有JVM需要设置什么

**Comment by alinlapland** [comment]
Metrics 上面的 那个 cluster 里面有个 展示的 是否显示当前 集群 zookeeper 和 kafka 的版本号？起码开个 JMX_PORT端口 和  设置一下内存
export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70" 这个配置是我看介绍推荐的，修改 kafka-server-start.sh里面的
