### ISSUE TITLE
consumer offset is wrong after change KafkaOffsetGetter to use sasl

### ISSUE THREAD

**Issue by WangFenglun** [smartloli/kafka-eagle#37]
After using startOffsetSaslListener to listen offset thread method with sasl，the old consumer offset is wrong。For example，group ”test“ logsize is 40000 and actually offset is also 40000，we can see it before。but after using startOffsetSaslListener，the offset we can see becomes 20000。And a new group don’t hava the same problem。Why it happen？How can i make the result we can see become true？

**Comment by WangFenglun** [comment]
And some group offset can‘t get。KafkaOffsetGetter’s consumer get message from "__consumer_offset" too slow?

**Comment by zhoukun590014** [comment]
Alarm can not work ?
