### ISSUE TITLE
v1.4.8点击Hub，出现403，No privileges ~~

### ISSUE THREAD

**Issue by githubgavin** [smartloli/kafka-eagle#370]
v1.4.8点击`hub`，出现以下报错

![image](https://user-images.githubusercontent.com/16367150/85942874-da5fd780-b95e-11ea-8dec-140d31128be3.png)

用的是默认的sqlite数据库，请问有没有解决方法？
@smartloli

**Comment by smartloli** [comment]
http://www.kafka-eagle.org/articles/docs/installation/upgrade.html
