### ISSUE TITLE
ksql查询报如下日志

### ISSUE THREAD

**Issue by kaiqiangmeng** [smartloli/kafka-eagle#375]
![Uploading image.png…]()

topic已存在，且还有数据查询看日志就是这个情况

**Comment by kaiqiangmeng** [comment]
![image](https://user-images.githubusercontent.com/45863353/87023414-40bfe200-c20a-11ea-8023-b9ae2db0f6ee.png)
报如上提示

**Comment by smartloli** [comment]
KSQL query need to include `partition`
```
select * from topic_name where `partition` in (0) limit 10
```
http://www.kafka-eagle.org/articles/docs/quickstart/ksql.html
