### ISSUE TITLE
CentOS虚拟机中启动OOM

### ISSUE THREAD

**Issue by goldroad** [smartloli/kafka-eagle#378]
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 2147483648 bytes for committing reserved memory.
# Possible reasons:
#   The system is out of physical RAM or swap space
#   In 32 bit mode, the process size limit was hit
# Possible solutions:
#   Reduce memory load on the system
#   Increase physical memory or swap space
#   Check if swap backing store is full
#   Use 64 bit Java on a 64 bit OS
#   Decrease Java heap size (-Xmx/-Xms)
#   Decrease number of Java threads
#   Decrease Java thread stack sizes (-Xss)
#   Set larger code cache with -XX:ReservedCodeCacheSize=
# This output file may be truncated or incomplete.
#
#  Out of Memory Error (os_linux.cpp:2673), pid=8434, tid=139895182022400
#
# JRE version:  (8.0_40-b25) (build )
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.40-b25 mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
# 

启动成功以后立即挂掉，OOM的问题怎么解决？

**Comment by smartloli** [comment]
Ensure that the Linux OS has enough memory for Kafka-Eagle applications (default is 2G)

**Comment by smartloli** [comment]
`ke.sh`
```
# Default Memory
export KE_JAVA_OPTS="-server -Xmx2g -Xms2g"
```
