### ISSUE TITLE
启动报错java.io.EOFException: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by zhengdegu** [smartloli/kafka-eagle#379]
启动报错java.io.EOFException: Unexpected end of ZLIB input stream 使用的jdk1.8.0_221
![image](https://user-images.githubusercontent.com/32125595/87646995-c51de200-c781-11ea-9dce-8cb373d73eb3.png)

**Comment by QueenaShen** [comment]
安装包没下载完整
