### ISSUE TITLE
topic修改分区数量报404错误

### ISSUE THREAD

**Issue by checkme5** [smartloli/kafka-eagle#385]
Topic/List页面点击Action按钮，Modify修改分区数量报404错误。
![image](https://user-images.githubusercontent.com/1314252/88617571-8bc26c00-d0c9-11ea-8ab6-24a75ef99891.png)

**Comment by smartloli** [comment]
Please check your kafka eagle system error log.

**Comment by ilaotan** [comment]
老哥看我提的issue 有解决方案了，等作者更新吧 #418
