### ISSUE TITLE
能否在Kafka Eagle上加入Connect的监控和管理功能

### ISSUE THREAD

**Issue by wuwba** [smartloli/kafka-eagle#389]
Kafka Eagle非常好用，感谢社区的贡献，不过想提个需求，能否加入对Kafka Connect的监控和管理功能。
在用到CDC和Connect的场景下，只能通过API的方式，非常不直观，如果能在Kafka Eagle里首先加上监控功能，把Kafka的Connect都List出来，查看状态，会方便很多；当Connect状态有异常，通过Alert报警，解决了使用Connect没有监控的一个痛点

其次是如果能在Kafka Eagle中加入Kafka Connect的新建，修改，启停功能，会更好，但这个功能应该会复杂些，可以优先级放低一些，前面的监控和报警应该是目前我们觉得最需要的。

**Comment by VisionaryAries** [comment]
赞，我们也有同样的需求，最近项目上用到很多connect用于数据同步和流计算，急需对connect的监控和管理，想不到KE已经开始开发了，太好了

**Comment by wuwba** [comment]
感谢在新版本2.0.2中加入了Connect的监控功能，满足了我们目前的基本需求 @smartloli

**Comment by wuwba** [comment]
也期待后续加入启停Connector等功能，还要Alert监控功能（当有Connect的Task失败，Alert邮件出来） @wuwba

**Comment by wuwba** [comment]
此外能否在Connect的页面上新增一个字段用来描述这个Connect的名字，当有多个Connect的时候，除了有URL，加上这个Connect名字，这样能更好区分Connect属于那个业务的；另外我们还想开放这个Connect页面给Guest账号，但又不想让Guest知道Connector的配置（配置里边会包含些用户名密码信息），能否Guest的时候只显示状态不显示Connector和Task的配置 @smartloli

**Comment by VisionaryAries** [comment]
今天装上试用了connector监控，非常感谢 @smartloli   ,希望connector监控越做越好，提5个需求，也是日常使用connect过程中的痛点。
1. 监控connector的task状态。日常使用connector过程中，最多的问题是task停了，connector没问题。
2. 通过添加connector地址自动发现集群下的所有connectors。例如添加http://x.x.x.x:8083/connectors后自动列出该connector集群的所有connector，而无需手工一个个添加。像我们的connector集群中connector数从几十到上百不等，手工一个个添加效率太低
3. 增加查看connector中task的报错信息
4. 增加查看connector的配置信息
5. 增加特定connector重启、暂停、和重建功能
