### ISSUE TITLE
Kafka-Eagle 连接失败，报JMX异常

### ISSUE THREAD

**Issue by ExtremeX-Liu** [smartloli/kafka-eagle#398]
![image](https://user-images.githubusercontent.com/13010328/90463081-acb43500-e13c-11ea-8598-b69975bcaa1b.png)

**Comment by ExtremeX-Liu** [comment]
1. kafka服务开启了JMX：9999端口
2. 已开通Kafka-Eagle到Kakfa主机9999的防火墙

**Comment by ExtremeX-Liu** [comment]
请问这个连接异常是什么问题，有大佬遇到并解决过么？谢谢

**Comment by smartloli** [comment]
Linux firewall ports are confirmed to be open. From the screenshot provided by you, the firewall restricts port access.

**Comment by ExtremeX-Liu** [comment]
> Linux firewall ports are confirmed to be open. From the screenshot provided by you, the firewall restricts port access.

主机到kafka的9092和9999端口telnet都是通的

**Comment by ExtremeX-Liu** [comment]
![image](https://user-images.githubusercontent.com/13010328/91009514-513de780-e613-11ea-88d1-1948b6285e4c.png)

**Comment by 1763734039** [comment]
我也遇到了同样的问题，我使用的kafka版本为:kafka_2.12-2.6.0

**Comment by 1763734039** [comment]
![image](https://user-images.githubusercontent.com/26586301/91688539-ca4db980-eb94-11ea-9822-bedf6adc86d3.png)

**Comment by Lay0806** [comment]
你这个解决了吗？我也是同样问题

**Comment by ExtremeX-Liu** [comment]
> 你这个解决了吗？我也是同样问题

没有

**Comment by yingyingqiqi** [comment]
大佬们，现在解决了嘛？ 相同报错。
我Kafka broker 和 eagle 安装到同一台机器。
Kafka版本：kafka_2.13-2.7.0
eagle 版本：kafka-eagle-web-2.0.4

**Comment by yingyingqiqi** [comment]
是自己配置错误了
