### ISSUE TITLE
bscreen

### ISSUE THREAD

**Issue by Berry-w** [smartloli/kafka-eagle#399]
配置两个集群，一个集群有数据，另一个暂时没使用。有数据的集群显示有问题。
![2020-08-21 09 17 02](https://user-images.githubusercontent.com/19390812/90841397-29d6e880-e38f-11ea-9836-74538ad5e04c.jpg)
total records 一直是0，producer records 显示也有问题是0。这个集群之前一直显示正常，也一直在使用，配置第二个集群后就显示异常了，请大神帮忙看看

**Comment by FrommyMind** [comment]
+1
