### ISSUE TITLE
生产速度、消费速度总显示为0

### ISSUE THREAD

**Issue by yanming-zhang** [smartloli/kafka-eagle#4]
生产速度、消费速度总显示为0，感觉是bug，而且要不了多长时间，会挂掉

**Comment by smartloli** [comment]
@yanming-zhang I'm sorry to have caused you to use Kafka Eagle, which has been fixed, you can download the [v1.1.2](http://download.smartloli.org/) version, or look at the repair details. Finally, thank you very much for your feedback.
