### ISSUE TITLE
Dashboard界面无数据，zookeeper集群无法获取版本信息和角色信息，bscreen 显示数据残缺

### ISSUE THREAD

**Issue by 1063238280** [smartloli/kafka-eagle#400]
环境信息：
kafka-eagle version : 2.0.1
kafka version: 2.13-2.4.1
zookeeper version:  3.5.7
java version : 1.8.0_241
日志无报错信息
![image](https://user-images.githubusercontent.com/63490857/91158768-b79d3580-e6f9-11ea-9add-82752cd3c32f.png)
![image](https://user-images.githubusercontent.com/63490857/91158797-c4218e00-e6f9-11ea-92bf-ac48d7450a75.png)
![image](https://user-images.githubusercontent.com/63490857/91158869-dac7e500-e6f9-11ea-95cd-ac3b68115658.png)
![image](https://user-images.githubusercontent.com/63490857/91162478-b1f61e80-e6fe-11ea-9c44-7e069d38890f.png)

**Comment by Cassuis** [comment]
JMX是不是没有设置呀
