### ISSUE TITLE
连接zk问题和jmx连接错误

### ISSUE THREAD

**Issue by fcbwalk** [smartloli/kafka-eagle#402]
我在本地vmware部署了3个节点，**一切正常**。但在生产环境的云平台部署后出现两个问题。(本地vmware和prod环境配置没有差异)
1. 重复连接zk,每隔20s连接一次，导致启动过慢。vmware下基本上几秒就刷过去了，但生产环境得8分钟以上走完这个过程。虽然也能成功连接zk，不影响运行。但确实是一个问题。
prod kafka-eagle启动过程日志：
![image](https://user-images.githubusercontent.com/47557128/91373823-e2969f00-e849-11ea-9c92-4bcf471b8503.png)
prod zk日志：
![image](https://user-images.githubusercontent.com/47557128/91373983-1c67a580-e84a-11ea-9664-b209afba932c.png)
> 上面两张图可以看到20s连接一次，但在vmware是不存在这个问题的，2s就完成了整个过程。vmware zk日志: ![image](https://user-images.githubusercontent.com/47557128/91374318-884a0e00-e84a-11ea-91d3-8af45a6010f0.png)

2. jmx连接错误。
vmware下正常。prod环境，**防火墙已关，telnet端口也是通**的。但一直连接错误。
![image](https://user-images.githubusercontent.com/47557128/91374785-93516e00-e84b-11ea-827d-979c8f9b774c.png)

**Comment by skywateryang** [comment]
你好 ，我也是在云主机上出现了错误，启动后可以看到登录界面，但是登录不进去，
报错的信息在这里，请问你有遇到类似的问题吗
https://github.com/smartloli/kafka-eagle/issues/424

**Comment by fcbwalk** [comment]
> 你好 ，我也是在云主机上出现了错误，启动后可以看到登录界面，但是登录不进去，
> 报错的信息在这里，请问你有遇到类似的问题吗
> #424

java.net.UnknownHostException: dbus-n1.localdomain: dbus-n1.localdomain: Name or service not known，dbus-n1.localdomain这个主机名无法解析，你需要配置主机的hostname。我的连接直接是ip，不是这个错误。
