### ISSUE TITLE
Kafka Eagle Topic List页面能否加上LogSize, Message,TOTAL CAPACITY,Replicas,producer message/s,consumer message/s等

### ISSUE THREAD

**Issue by wuwba** [smartloli/kafka-eagle#403]
Kafka Eagle在dashboard页面能看到Topic 10的Log Size和Capacity的Topic，但是如果想要知道其他Topic的Log Size等信息，就只能点进去具体的Topic看，但实际运维中，我们还想知道Topic 10以外的一些Topic的Log Size情况，如果一个一个点进去，确实比较费劲；能否在Topic List中也加入LogSize, Message,TOTAL CAPACITY这两个关键信息。另外能否跟Kafka Manager一样，在Topic List中加入更多比较有用的信息，例如Replicas，producer message/s,consumer message/s等Summary的信息，只有在Topic List能一目了然了解所有Topic的关键信息，甚至还能像kafka Manager那样排序。
![image](https://user-images.githubusercontent.com/5379958/91382704-e7188300-e85c-11ea-83b9-ec0006be1546.png)

建议先在Topic List加上LogSize, Message,TOTAL CAPACITY这两个比较key信息，其他的一些指标，可以晚些弄，另外如果能做成页面用户自己选择指标就更好了

**Comment by SuperBaBa** [comment]
> Kafka Eagle在dashboard页面能看到Topic 10的Log Size和Capacity的Topic，但是如果想要知道其他Topic的Log Size等信息，就只能点进去具体的Topic看，但实际运维中，我们还想知道Topic 10以外的一些Topic的Log Size情况，如果一个一个点进去，确实比较费劲；能否在Topic List中也加入LogSize, Message,TOTAL CAPACITY这两个关键信息。另外能否跟Kafka Manager一样，在Topic List中加入更多比较有用的信息，例如Replicas，producer message/s,consumer message/s等Summary的信息，只有在Topic List能一目了然了解所有Topic的关键信息，甚至还能像kafka Manager那样排序。
> ![image](https://user-images.githubusercontent.com/5379958/91382704-e7188300-e85c-11ea-83b9-ec0006be1546.png)
> 
> 建议先在Topic List加上LogSize, Message,TOTAL CAPACITY这两个比较key信息，其他的一些指标，可以晚些弄，另外如果能做成页面用户自己选择指标就更好了

我也想要这些信息，我在使用[CMAK](https://github.com/yahoo/CMAK)中，消费组能够看到每个分区对应的消费节点，比如我使用Logstash消费kafka时，能够看到哪些分区在被同一个Logstash消费
**能看到消费组中节点和topic分区的对应关系**也能够在增加kafka分区时清楚看到消费组是不是要增加节点了
国产加油
![image](https://user-images.githubusercontent.com/29269975/91518622-480a8e80-e923-11ea-9aeb-d14284fa63b3.png)

**Comment by wuwba** [comment]
国产加油 @SuperBaBa @smartloli

**Comment by trumpisasb** [comment]
Java code. Maybe I can code . I will try later.
