### ISSUE TITLE
能同时支持offset保存在zk和kafka里面的配置嘛?

### ISSUE THREAD

**Issue by openbytes** [smartloli/kafka-eagle#405]
由于线上的一些老的java服务,使用的是旧的kafka(0.9之前的版本),导致offset保存在zk里面.后面一些新的服务是用的新的版本的kafka 包,offset是保存在kafka
我这里这样配置可以嘛?
`# kafka offset storage
######################################
cluster1.kafka.eagle.offset.storage=kafka
cluster1.kafka.eagle.offset.storage=zk
######################################`

**Comment by smartloli** [comment]
@openbytes 
```
kafka.eagle.zk.cluster.alias=old,new
old.zk.list=127.0.0.1:2181
new.zk.list=127.0.0.1:2181

old.kafka.eagle.offset.storage=zk
new.kafka.eagle.offset.storage=kafka

# old kafka topic limit 
old.kafka.eagle.sasl.cgroup.enable=true
# set your kafka topic name
old.kafka.eagle.sasl.cgroup.topics=old_topic_name_01,old_topic_name_02

# new kafka topic limit 
new.kafka.eagle.sasl.cgroup.enable=true
# set your kafka topic name
new.kafka.eagle.sasl.cgroup.topics=new_topic_name_01,new_topic_name_02
```

**Comment by openbytes** [comment]
谢谢大佬的回复.这种的话,只适合topic很少的场景吧.我们这现在100+topic.这样配置的话,着实有点不科学.以后每增加一个topic都得来配置文件修改.

**Comment by openbytes** [comment]
而已更要命的是,同一个topic,他们新旧kafka 包都往这个topic里面发数据.
