### ISSUE TITLE
添加直接链接smtp邮件服务器

### ISSUE THREAD

**Issue by jingweiz300** [smartloli/kafka-eagle#411]
目前的邮件通知方法必须要额外手动构造一个具有rest api的http服务接收邮件

**Comment by jimbao2019** [comment]
我知道，因為沒有rest api的http服务， 所以希望大神搞一下 SMTP，方便大家使用SMTP發送郵件。

**Comment by smartloli** [comment]
Fixed by [SMTP](https://github.com/smartloli/kafka-eagle/commit/9f67d527319bc0a1a110f611d559fe00442b0c81) mail.
