### ISSUE TITLE
 kafka-eagle 运行中cpu一直处于100% 上下

### ISSUE THREAD

**Issue by 3tem** [smartloli/kafka-eagle#413]
kafka-eagle 运行时cpu一直处于100% 上下

**Comment by smartloli** [comment]
```
100% -> 1 cpu cores
```
CPU resources are used very little.

**Comment by 3tem** [comment]
version: 2.0.1
我屏蔽掉所有的定时任务代码之后，发现，cup 的使用率下降。

**Comment by smartloli** [comment]
If you linux server is `8G` and `4 cores`
CPU Full :
```
400% -> 4 cores
```
100% just fills up 1 cpu cores. Do you understand?
