### ISSUE TITLE
考虑过出一个docker版本的kafka-eagle吗

### ISSUE THREAD

**Issue by hormones** [smartloli/kafka-eagle#414]
大佬，考虑过出一个docker版本的kafka-eagle吗？
感觉满蛮有必要的。

**Comment by smartloli** [comment]
If you want to participate in the project, you can submit a docker [PR](https://github.com/smartloli/kafka-eagle/pulls) to the community.

**Comment by Cassuis** [comment]
自己封装，很简单的，有JDK就 可以
