### ISSUE TITLE
在dashboard界面直接配置钉钉报警，没有收到报警信息

### ISSUE THREAD

**Issue by black-xiu** [smartloli/kafka-eagle#417]
没有编译源码，直接在dashboard界面配置的钉钉报警，测试报警信息可以收到，但是有消费者数据积压的时候没有收到报警信息；底层日志显示的是 DingDing SendMsg Result: {"errcode":310000,"errmsg":"keywords not in content, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq]"}

**Comment by black-xiu** [comment]
是kafka eagle-2.0.1

**Comment by roamerop** [comment]
Kafka-Eagle alarm msg should contains the keyword which config in DingDing.

**Comment by black-xiu** [comment]
看一下你的Message里是否包含Kafka Eagle Alarm 这几个单词或者其中的一个字母



At 2020-10-19 15:14:12, "roamerop" <notifications@github.com> wrote:

Kafka-Eagle alarm msg should contains the keyword which config in DingDing.
