### ISSUE TITLE
我为啥打不开https://ke.smartloli.org/这个页面

### ISSUE THREAD

**Issue by mmmboge** [smartloli/kafka-eagle#42]
我为啥打不开https://ke.smartloli.org/　这个页面,你们可以吗

**Comment by smartloli** [comment]
@mmmboge Sometimes because network problems need to be accessed by VPN.

**Comment by mmmboge** [comment]
@smartloli is there any other way to get the installer guide？ because i can't use VPN in the company

**Comment by smartloli** [comment]
@mmmboge Please visit [wiki](https://github.com/smartloli/Kafka-Eagle-Wiki/blob/master/SUMMARY.md).
