### ISSUE TITLE
KSQL无法查询全量消息记录

### ISSUE THREAD

**Issue by carlos9310** [smartloli/kafka-eagle#423]
某个topic下的某个分区有近3亿条消息，用KSQL只查询出最后的5000条消息。本地磁盘存有全量的消息

**Comment by black-xiu** [comment]
官方文档好像有写，每次限制查询5000条数据，不知道我回答的对不对

**Comment by carlos9310** [comment]
> 官方文档好像有写，每次限制查询5000条数据
> 官方文档链接：http://www.kafka-eagle.org/articles/docs/quickstart/ksql.html
> NOTE：
> Access to topic message data, depending on the underlying interface record of the earliest and latest offset, the default display up to 5000 records.

可以配置查询全量的数据么？文档中貌似没有相关说明

**Comment by black-xiu** [comment]
你可以通过命令行的形式查，这里就是限制了只能查询最近的5000条数据

**Comment by carlos9310** [comment]
好吧
