### ISSUE TITLE
Topic Alarm config bug

### ISSUE THREAD

**Issue by roamerop** [smartloli/kafka-eagle#425]
Topic Alarm config bug, version 1.4.7
1. add config   web-ui  ->  Alarm  -> Cluster -> AlarmType select Topic  -> Add.
2. monitor config   web-ui  ->  Alarm  -> Cluster -> History, the topic value is null, but i have already config.
3. config again   web-ui  ->  Alarm  -> Cluster -> History -> select Topic Action -> Modify -> input Server:{"topic":"ke_alarm_topic","capacity":1024}

**Comment by smartloli** [comment]
Please update 2.0.2 version.

**Comment by roamerop** [comment]
> Please update 2.0.2 version.

Thx.
