### ISSUE TITLE
What is the producer rates mean?

### ISSUE THREAD

**Issue by roamerop** [smartloli/kafka-eagle#426]
Not issue, What is the producer rates mean?  I toticed when the comsumer rates was 0 msg/min ,but Alarm rates was `real.speeds(5)`  in my example.   Thanks a lot
1. Alarm  Producer Rates
 Write topic and speed alarm value(unit is msg/min), such as {"topic":"ke_alarm_topic","speed":"10000,20000"}.
2. Consumer group  Producer Rates
example :   Producer Rates 0 msg / min.

**Comment by smartloli** [comment]
Producer and consumer are independent, and there is no necessary connection between alarms.

**Comment by roamerop** [comment]
> Producer and Consumer are independent, and there is no necessary connection between alarms.

I want to know how to calculate producer/consumer rates.
