### ISSUE TITLE
后台服务路径的前缀支持配置化问题

### ISSUE THREAD

**Issue by helloyaoge** [smartloli/kafka-eagle#435]
![image](https://user-images.githubusercontent.com/12529019/98191009-3bbe3580-1f53-11eb-8a12-35196060a454.png)

希望这个后端服务端路径是可以配置。 或者是固定，spring 后端所有的controller都有这个。貌似tomcat 层面可以支持。背景是nginx 在配置反向代理的时候需要用到

**Comment by helloyaoge** [comment]
这个需要前端的jsp 配置路径，路径比较多，不太好改，还是需要你们支持一下

**Comment by helloyaoge** [comment]
这个能快速的支持一下吗？

**Comment by smartloli** [comment]
Please used [kafka-eagle-v2.0.2](http://www.kafka-eagle.org/index.html)
![startup_img](http://www.kafka-eagle.org/images/docs/startup@2x.png)

**Comment by helloyaoge** [comment]
这个版本不知道吧。 我需要通过nginx 的方向代理进行反问，需要后台的所有路径都有一个固定的前缀。这个版本不支持吧？

**Comment by helloyaoge** [comment]
即使后端通过kms 路径路径下面的server.xml 进行配置了，但是。前段的jsp action的路径也需要指定。 我的问题描述清楚了吗？

**Comment by helloyaoge** [comment]
可以快速只的支持一下吗？ 我自己改有点费劲啊，这个路径跳来跳去的，全都是硬编码。
