### ISSUE TITLE
Dashboard页面显示问题

### ISSUE THREAD

**Issue by lzpsqzr** [smartloli/kafka-eagle#437]
dashboard页面中 ranking 数据有显示，点击topic后进入详细页面也有数据，但是汇总数据为0
![image](https://user-images.githubusercontent.com/12146453/98636575-1b7ee400-2362-11eb-8f1f-8f4788eee5c9.png)
![image](https://user-images.githubusercontent.com/12146453/98636716-61d44300-2362-11eb-990e-4004861f0ada.png)

**Comment by konghouyin** [comment]
我的也存在这个问题，需要等待一会，才会显示数据

**Comment by zfq314** [comment]
请问这个问题有办法解决没？我也存在同样的问题。

**Comment by yasin-bj** [comment]
我也同样的问题

**Comment by yasin-bj** [comment]
ksql 里的 Query按钮点了也没反应
