### ISSUE TITLE
无法查看到Zookeeper的版本信息和Metrics信息，但是kafka的信息和Metrics都很正常

### ISSUE THREAD

**Issue by Cassuis** [smartloli/kafka-eagle#440]
无法查看到Zookeeper的版本信息和Metrics信息，折线图等，但是kafka的信息和Metrics都很正常，JMX都是正常的
zookeeper:3.6.1
kafka:2.13-2.6.0
kafka-eagle无报错信息，只是在Dashboard提示Note: Kafka version is "-" or JMX Port is "-1" maybe kafka broker jmxport disable.但是实际Kafka的折线图和Metrics数据库都正常，BScreen也正常显示。

Zookeeper Client 终端 ls /也正常
[zk: (CONNECTED) ] > ls /
[cluster, controller, brokers, zookeeper, admin, isr_change_notification, canal-adapter, log_dir_event_notification, otter, controller_epoch, kafka-manager, consumers, latest_producer_id_block, config]
[zk: (CONNECTED) ] >

**Comment by WilliamGuozi** [comment]
遇到同样的问题

**Comment by Cherishwang2229** [comment]
同样遇到zookeeper不能查看版本信息和mode，通过安装  yum install nc -y   和在zoo.cfg配置文件中添加
4lw.commands.whitelist=*,解决不能显示zookeeper版本信息和mode问题。

**Comment by WilliamGuozi** [comment]
> 同样遇到zookeeper不能查看版本信息和mode，通过安装 yum install nc -y 和在zoo.cfg配置文件中添加
> 4lw.commands.whitelist=*,解决不能显示zookeeper版本信息和mode问题。

亲测有效，感谢🙏

**Comment by walkeradmin** [comment]
有效，Thank u

**Comment by walkeradmin** [comment]
> 同样遇到zookeeper不能查看版本信息和mode，通过安装 yum install nc -y 和在zoo.cfg配置文件中添加
> 4lw.commands.whitelist=*,解决不能显示zookeeper版本信息和mode问题。

有效，Thank u

**Comment by zfq314** [comment]
有效，赞
