### ISSUE TITLE
查不到数据

### ISSUE THREAD

**Issue by Mrchenli** [smartloli/kafka-eagle#46]
SELECT "partition","offset","msg" FROM "test" WHERE "partition" IN (0) limit 10;
弹出来这个DataTables warning: table id=result_children0 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3
logs:Finished by [0.61s].
result:是空
只有partition0分区 logsize700 offset700 lag0

**Comment by smartloli** [comment]
@Mrchenli Whether there is a print exception in the Kafka Eagle system log.

**Comment by Mrchenli** [comment]
这个是日志，谢谢啊
[2017-12-27 21:05:37] AppInfoParser.http-nio-8048-exec-14 - INFO  - Kafka version : 0.10.2.0
 [2017-12-27 21:05:37] AppInfoParser.http-nio-8048-exec-14 - INFO  - Kafka commitId : 576d93a8dc0cf421
 [2017-12-27 21:05:57] KafkaSqlParser.http-nio-8048-exec-16 - INFO  - KafkaSqlParser - SQL[select "partition","offset","msg" from "test" where "partition" in (0)]
 [2017-12-27 21:05:57] ConsumerConfig.http-nio-8048-exec-16 - INFO  - ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [10.0.10.74:9092]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = kafka.eagle.system.group
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

 [2017-12-27 21:05:57] ConsumerConfig.http-nio-8048-exec-16 - INFO  - ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [10.0.10.74:9092]
	check.crcs = true
	client.id = consumer-52
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = kafka.eagle.system.group
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

 [2017-12-27 21:05:57] AppInfoParser.http-nio-8048-exec-16 - INFO  - Kafka version : 0.10.2.0
 [2017-12-27 21:05:57] AppInfoParser.http-nio-8048-exec-16 - INFO  - Kafka commitId : 576d93a8dc0cf421
 [2017-12-27 21:05:57] Fetcher.http-nio-8048-exec-16 - INFO  - Fetch offset 0 is out of range for partition test-0, resetting offset
 [2017-12-27 21:05:58] AbstractCoordinator.http-nio-8048-exec-16 - INFO  - Discovered coordinator 10.0.10.74:9092 (id: 2147483647 rack: null) for group kafka.eagle.system.group.

**Comment by smartloli** [comment]
@Mrchenli Only supports SASL.

**Comment by Mrchenli** [comment]
配置了SASL还是不行。。。[2017-12-28 03:21:25] KafkaSqlParser.http-nio-8048-exec-7 - INFO  - KafkaSqlParser - SQL[select "partition","offset","msg" from "test" where "partition" in (0) limit 10]
 [2017-12-28 03:21:25] ConsumerConfig.http-nio-8048-exec-7 - INFO  - ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [10.0.10.74:9092]
	check.crcs = true
	client.id = 
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = kafka.eagle.system.group
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

 [2017-12-28 03:21:25] ConsumerConfig.http-nio-8048-exec-7 - INFO  - ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [10.0.10.74:9092]
	check.crcs = true
	client.id = consumer-15
	connections.max.idle.ms = 540000
	enable.auto.commit = true
	exclude.internal.topics = true
	fetch.max.bytes = 52428800
	fetch.max.wait.ms = 500
	fetch.min.bytes = 1
	group.id = kafka.eagle.system.group
	heartbeat.interval.ms = 3000
	interceptor.classes = null
	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
	max.partition.fetch.bytes = 1048576
	max.poll.interval.ms = 300000
	max.poll.records = 500
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
	receive.buffer.bytes = 65536
	reconnect.backoff.ms = 50
	request.timeout.ms = 305000
	retry.backoff.ms = 100
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.mechanism = PLAIN
	security.protocol = SASL_PLAINTEXT
	send.buffer.bytes = 131072
	session.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	value.deserializer = class org.apache.kafka.common.serialization.StringDeserializer

 [2017-12-28 03:21:25] AppInfoParser.http-nio-8048-exec-7 - INFO  - Kafka version : 0.10.2.0
 [2017-12-28 03:21:25] AppInfoParser.http-nio-8048-exec-7 - INFO  - Kafka commitId : 576d93a8dc0cf421
 [2017-12-28 03:21:25] Fetcher.http-nio-8048-exec-7 - INFO  - Fetch offset 0 is out of range for partition test-0, resetting offset
 [2017-12-28 03:21:26] AbstractCoordinator.http-nio-8048-exec-7 - INFO  - Discovered coordinator 10.0.10.74:9092 (id: 2147483647 rack: null) for group kafka.eagle.system.group.
![image](https://user-images.githubusercontent.com/20294244/34405004-dcd5eb50-ebeb-11e7-81ee-5ea67aa4e106.png)
![image](https://user-images.githubusercontent.com/20294244/34405061-1e3497fe-ebec-11e7-94f9-50e7161a2e1a.png)

**Comment by smartloli** [comment]
@Mrchenli Your Kafka cluster is also consistent with the configuration of the SASL and Kafka Eagle system configuration, and the Zookeeper cluster is also the SASL protocol to be used when the cluster is started. Such as 
```
Kafka Cluster Set SASL
Kafka Eagle Set SASL
Zookeeper Set SASL
```
