### ISSUE TITLE
读取zookeeper buffer 报错

### ISSUE THREAD

**Issue by yangvipguang** [smartloli/kafka-eagle#461]
![image](https://user-images.githubusercontent.com/11416887/104932933-35344b80-59e3-11eb-8432-0c53b0fd5413.png)
这个属于bug 还是配置问题。

**Comment by BsoBird** [comment]
哥们你解决这个问题了吗？这应该是zk连接起太多打满zk上限导致的。

**Comment by yangvipguang** [comment]
@BsoBird  不知道我已经弃用了。 可以推荐你用滴滴开源的。

**Comment by BsoBird** [comment]
DIDI这个需要等几个版本迭代。它接管已有kafka集群不太方便,主要是topic不能直接管理。

**Comment by BsoBird** [comment]
我这边打算先cmak + eagle顶一阵子。然后观望下滴滴的进展

**Comment by yangvipguang** [comment]
挺方便的啊。我们用这个不错的。

**Comment by BsoBird** [comment]
他这个接管已存在的topic现在很麻烦。我想等两个版本

**Comment by BsoBird** [comment]
我找到他bug在哪了，他代码的zk连接池有问题。连接池请求资源空了之后没有又直接新创建了满的连接池,而且在释放的时候,对于不在连接池管控内的连接 不关闭。诶呦,代码怎么能这么写呢。

**Comment by KingNF** [comment]
这个问题，修复后，还是有问题，你们的eagle 可以跑多久，不挂？

**Comment by yangvipguang** [comment]
@KingNF   已经不用了。总是出现502 问题。
