### ISSUE TITLE
没有MySQL数据库初始化脚本

### ISSUE THREAD

**Issue by EricJayLsh** [smartloli/kafka-eagle#464]
所有都配置好了，登录页面也可以打开，但是我实在是找不到初始化数据库的脚本啊，老版本我也下载了一些，但是都没找到初始化数据库的脚本，db文件夹下只是一个README文件，没有SQL脚本，我想问问你们怎么搞得？

**Comment by smartloli** [comment]
Automatically initialize the database with system startup.
