### ISSUE TITLE
V2.0.3 前端echarts报错，折线图无法显示

### ISSUE THREAD

**Issue by lizheng0329** [smartloli/kafka-eagle#468]
V2.0.3 前端echarts报错，折线图无法显示

**Comment by smartloli** [comment]
Clear browser cache.

**Comment by lizheng0329** [comment]
> Clear browser cache.

找到原因了，不是浏览器缓存的问题，是由于这个项目自带的tomcat超时时间是100ms，js未加载完成就被截断了，，，调整tomcat配置后就可以了。
