### ISSUE TITLE
why kafka-eagle create too many zookeeper connection?

### ISSUE THREAD

**Issue by BsoBird** [smartloli/kafka-eagle#470]

**Comment by BsoBird** [comment]
zookeeper 版本3.4.6    kafka1.1.1 。
现象:kafka-eagle不停地起zookeeper连接直至打满zk的上限。

**Comment by Tiakon** [comment]
+1

**Comment by SmileGf** [comment]
> zookeeper 版本3.4.6 kafka1.1.1 。
> 现象:kafka-eagle不停地起zookeeper连接直至打满zk的上限。

有个lfka1.1.1 。
> 现象:kafka-eagle不停地起zookeeper连接直至打满zk的上限。

有个临时解决方案: 1. 在这个类 KafkaZKPoolUtils 里面的getZkClient() 这个方法中的zkCliPool.remove(0); 注释掉。2. release() 这个方法中的 zkCliPool.add(zkc); 这个注释掉(这个是主要注释掉)。这样可以暂时解决打满的问题。

这属于零时解决方案，将就着用吧！还是让作者后期优化吧。

**Comment by BsoBird** [comment]
@SmileGf  我早就提PR了,https://github.com/smartloli/kafka-eagle/pull/476  我的思路是根本不释放ZK链接,反正是线程安全的。顶大加个存活检测。

**Comment by daviddone** [comment]
+1

**Comment by BsoBird** [comment]
https://github.com/smartloli/EFAK/issues/461
