### ISSUE TITLE
dashboard不显示任何数据，但是能做到topic创建和读取

### ISSUE THREAD

**Issue by DADA-shuai** [smartloli/kafka-eagle#472]
![image](https://user-images.githubusercontent.com/58056514/107017602-51edc300-67da-11eb-9f7e-0c1a685a888d.png)
![image](https://user-images.githubusercontent.com/58056514/107017638-5b772b00-67da-11eb-94be-1ef93fb848e7.png)

**Comment by yasin-bj** [comment]
我也是这样，单纯的看zk&kafka集群也是ok的。 dashboard死活出不来， 也没任何错误日志，eagle版本2.0.4

**Comment by Huangvivi** [comment]
> 我也是这样，单纯的看zk&kafka集群也是ok的。 dashboard死活出不来， 也没任何错误日志，eagle版本2.0.4

+1，我也是2.0.4，而且KSQL还查不了，查询界面那个框都变形缩小了，点击buttun请求都不发的

**Comment by MichaelLee826** [comment]
我也是2.0.4，也是同样的问题

**Comment by DADA-shuai** [comment]
2.12 - 2.20
