### ISSUE TITLE
使用select 提示 start with  a select

### ISSUE THREAD

**Issue by tanwen19932** [smartloli/kafka-eagle#48]
#错误
SQL选择的时候输入sql后提示 start with  a select
![image](https://user-images.githubusercontent.com/15818553/34804042-78a4473c-f6b1-11e7-9b11-402835ded473.png)

#版本
ke v1.1.8
kafka 2.11-0.10.1.1

**Comment by smartloli** [comment]
@tanwen19932 Example:``` select * from "ke_test" where "partition" in (0,1,2,3,4,5) limit 10```, you must be use kafka topic partition.

**Comment by tanwen19932** [comment]
@smartloli SELECT "partition","offset","msg" FROM "Doc4Analyse" WHERE "partition" IN (0,1,2) limit 10
use this query also get this error 
in fact , use lower or upper case or whatever form the error always occurs

**Comment by smartloli** [comment]
@tanwen19932 In addition, it is recommended to use kafka-eagle-1.2.0
