### ISSUE TITLE
kafka eagle 启动正常，但是登录不了

### ISSUE THREAD

**Issue by JackieGG** [smartloli/kafka-eagle#49]
启动后，访问localhost:8048/ke 后，显示登录页面，请问下用户名和密码要在哪里配置么?本地mysql中也有新建ke库。下面是我的配置，还请帮忙看下，谢谢。
######################################
# multi zookeeper&kafka cluster list
######################################
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=localhost:2181

######################################
# zk client thread limit
######################################
kafka.zk.limit.size=25

######################################
# kafka eagle webui port
######################################
kafka.eagle.webui.port=8048

######################################
# kafka offset storage
######################################
kafka.eagle.offset.storage=kafka

######################################
# alarm email configure
######################################
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=alert_sa
kafka.eagle.mail.username=alert_sa@163.com
kafka.eagle.mail.password=mqslimczkdqabbbg
kafka.eagle.mail.server.host=smtp.163.com
kafka.eagle.mail.server.port=25

######################################
# delete kafka topic token
######################################
kafka.eagle.topic.token=test

######################################
# kafka sasl authenticate
######################################
#kafka.eagle.sasl.enable=false
#kafka.eagle.sasl.protocol=SASL_PLAINTEXT
#kafka.eagle.sasl.mechanism=PLAIN
#kafka.eagle.sasl.client=kafka_client_jaas.conf

######################################
# kafka jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://localhost:3306/ke?useUnicode=true&characterEncoding=UTF8
kafka.eagle.username=root
kafka.eagle.password=root

看到使用quartz job去跑创建表的sql,但是报错了，是不是和这个有关呢?ke数据库是不是要初始化表等。
errorInfo:

### Cause: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ke.ke_trend' doesn't exist
; bad SQL grammar []; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'ke.ke_trend' doesn't exist

thx

**Comment by smartloli** [comment]
@JackieGG User information is initialized when the system is started. Such as
<img width="642" alt="default" src="https://user-images.githubusercontent.com/16030669/34933440-c253304c-fa11-11e7-8a5d-ba5c643766c9.png">
