### ISSUE TITLE
Official helm chart

### ISSUE THREAD

**Issue by survivant** [smartloli/kafka-eagle#493]
there should have a official Helm chart for this projet with a readme that explain how to configure it and run it.

**Comment by smartloli** [comment]
http://www.kafka-eagle.org/articles/docs/installation/linux-macos.html

**Comment by survivant** [comment]
thanks for the answer, but I was talking about to add a Helm chart to the projet and add the proper "helm" documentation to add to install it from Helm chart  (https://helm.sh/)

**Comment by survivant** [comment]
the first step should be to create a dockerfile.  In it you include the application + add lots of environement variables for the configuration and use can have a default confilguration file in it.

# 2 - create a Helm chart.  In it you can add/override default values.. and with a configMap you can generate the configuration file dynamically.  

# 3 - update the documentation to describe how to build/run it with docker   and another step how to deploy it with Helm in your kubernetes cluster

**Comment by jinze1107** [comment]
> e. In it you include the application + add lots of environement variables for the configuration and use can have a default confilguration file in it.
> 
> 2 - create a Helm chart. In it you can add/override default values.. and with a configMap you can generate the configuration file dynamically.
> 
> 3 - update the documentation to describe how to build/run it with docker and another step how to deploy it with Helm in your kubernetes cluster

agree
