### ISSUE TITLE
UI上查看某条消息的内容

### ISSUE THREAD

**Issue by bayern01kahn** [smartloli/kafka-eagle#509]
Hi Smartloli,  
    请教下, Eagle UI上能否直接查看某条消息的具体内容, 便于验证信息?  (除了通过ksql 的result 来查询) 谢谢

**Comment by smartloli** [comment]
The current version only uses ksql to preview the results. The next version will add this suggestion (preview the data directly on topic).

**Comment by bayern01kahn** [comment]
好的 感谢 期待下个版本
