### ISSUE TITLE
Consumers无法获取

### ISSUE THREAD

**Issue by ghostcry** [smartloli/kafka-eagle#52]
Consumers 页面中没有消费者信息，zk /consumers路径下是有消费者的。
另外建议Mock message中增加上传文件功能，文件按行导入到指定主题，该功能比较实用。

**Comment by smartloli** [comment]
@ghostcry If you store consumer information into zookeeper,Please set ```kafka.eagle.offset.storage=```

**Comment by ghostcry** [comment]
Consumers' information works for the zookeeper.<br/>
But when the offsets stored in topic of "__consumer_offsets" cannot be loaded.
