### ISSUE TITLE
Misuse of the ASF's Kafka trademark in Kafka Eagle

### ISSUE THREAD

**Issue by junrao** [smartloli/kafka-eagle#525]
On behalf of the Apache Kafka PMC, I am emailing you about Kafka Eagle (https://github.com/smartloli/kafka-eagle).

You may not be aware of this, but the name Kafka Eagle actually misuses the Apache Kafka trademark. For details, please see https://www.apache.org/foundation/marks/faq/#poweredby. In general, the name in the form of  "foo for Apache Kafka" or "foo powered by Apache Kafka" would both be acceptable.

We'd appreciate it if you can fix the misuse accordingly.

Thank you for your time and respect for the Apache trademark.

Jun Rao
on behalf of the Apache Kafka PMC

**Comment by smartloli** [comment]
I've left a message for you by email.
