### ISSUE TITLE
how can the email work well?

### ISSUE THREAD

**Issue by shang7053** [smartloli/kafka-eagle#53]
eg,I have a group ,named 'flume', and there a topic named 'flume_channel',
In eagle web ,I saw The LAG is 986! and then I config a alerm,such as GROUP:flume,topics:flume_channel,LAG:1,email:javascc@126.com,
so long ,the LAG alerady been 2000+,but my email received nothing!
so  how can the email work well?
thanks for so perfect kafka soft！

**Comment by smartloli** [comment]
@shang7053 See if the default configuration mail server is able to send mail:
```
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=alert_sa
kafka.eagle.mail.username=alert_sa@163.com
kafka.eagle.mail.password=mqslimczkdqabbbg
kafka.eagle.mail.server.host=smtp.163.com
kafka.eagle.mail.server.port=25
```
and if not, you can configure your own mail server, as shown in the following:
```
kafka.eagle.mail.enable=true
kafka.eagle.mail.sa=<your_sa>
kafka.eagle.mail.username=<your_mail_server_username>
kafka.eagle.mail.password=<password>
kafka.eagle.mail.server.host=<mail_server_host>
kafka.eagle.mail.server.port=<mail_server_port>
```

**Comment by shang7053** [comment]
Thanks，I onfused The config  kafka.eagle.mail.sa，now I will update it to right and test it

**Comment by shang7053** [comment]
@smartloli it's work！
