### ISSUE TITLE
ke.sh file not found in ${KE_HOME}/bin

### ISSUE THREAD

**Issue by Paw2Pom** [smartloli/kafka-eagle#54]
Version: 1.2.1

After unarchive the tarball file into the ${KE_HOME} directory, the file ke.sh cannot be located in the $KE_HOME/bin/ke.sh directory, as specified by the installation guide.

**Comment by smartloli** [comment]
@Paw2Pom Set ```KE_HOME``` & ```JAVA_HOME```like this:
```
export JAVA_HOME=/hadoop/jdk8
export KE_HOME=/hadoop/kafka-eagle
export PATH=$PATH:$KE_HOME/bin:$JAVA_HOME/bin
```
Run ```source /etc/profile``` or ```source ~/.bash_profile```.
Last, Start Kafka Eagle script, like this:
```
ke.sh start
```
Also, you can visit [Kafka Eagle Wiki](http://ke.smartloli.org/).

**Comment by Paw2Pom** [comment]
It works! Thank you!

**Comment by Paw2Pom** [comment]
I ran into another trouble, that there is an error message pops out when i starting up KE:

java.sql.SQLException: path to '/hadoop/kafka-egale/db/ke.db'

I think there maybe some typo exists in the script?

**Comment by smartloli** [comment]
@Paw2Pom Can you paste out a more detailed exception log.

**Comment by Paw2Pom** [comment]
Absolutely. I have created a dockerfile to create the KE, and below is the error output log.

==================================
kafka-eagle              | [2018-01-29 15:30:00] DruidDataSource.Druid-ConnectionPool-Create-582620180 - ERROR - create connection error, url: jdbc:sqlite:/hadoop/kafka-egale/db/ke.db, errorCode 0, state null
kafka-eagle              |  java.sql.SQLException: path to '/hadoop/kafka-egale/db/ke.db': '/hadoop/kafka-egale' does not exist
kafka-eagle              | 	at org.sqlite.core.CoreConnection.open(CoreConnection.java:192)
kafka-eagle              | 	at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
kafka-eagle              | 	at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
kafka-eagle              | 	at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
kafka-eagle              | 	at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
kafka-eagle              | 	at org.sqlite.JDBC.createConnection(JDBC.java:114)
kafka-eagle              | 	at org.sqlite.JDBC.connect(JDBC.java:88)
kafka-eagle              | 	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:148)
kafka-eagle              | 	at com.alibaba.druid.filter.stat.StatFilter.connection_connect(StatFilter.java:220)
kafka-eagle              | 	at com.alibaba.druid.filter.FilterChainImpl.connection_connect(FilterChainImpl.java:142)
kafka-eagle              | 	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1466)
kafka-eagle              | 	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1529)
kafka-eagle              | 	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2109)

**Comment by Paw2Pom** [comment]
Just incase, I also paste the dockerfile as below:

=====
`
FROM openjdk:8-jdk-alpine

ENV KE_VERSION 1.2.1
ENV KE_HOME /hadoop/kafka-eagle
ENV KE_CONF $KE_HOME/conf
ENV KE_LOG /app/ke/log

ENV JAVA_HOME /usr/lib/jvm/java-1.8-openjdk

ENV PATH $PATH:$KE_HOME/bin:$JAVA_HOME/bin



ENV TARBALL "https://github.com/smartloli/kafka-eagle-bin/archive/v1.2.1.tar.gz"

# Install kafka-eagle
RUN apk update \
    && apk add --no-cache bash tzdata \
    && rm -f /etc/localtime \
    && ln -sf /usr/share/zoneinfo/Asia/Taipei /etc/localtime \
    && apk add --no-cache -t .build-deps wget openssl tar \
    && cd /tmp \
    && wget --no-check-certificate --progress=bar:force -O kafka-eagle.tar.gz "$TARBALL" \
    && mkdir -p "$KE_HOME" \
    && tar -zxvf kafka-eagle.tar.gz --strip-components=1 -C "$KE_HOME" \
    && rm -f kafka-eagle.tar.gz \
    && apk del --purge .build-deps \
    && rm -fr /tmp/* \
    && cd "$KE_HOME" \
    && tar -zxvf kafka-eagle-web-1.2.1-bin.tar.gz --strip-components=1 -C "$KE_HOME" \
    && rm -f kafka-eagle-web-1.2.1-bin.tar.gz

# Install mysql & update mysql config
ENV MYSQL_LOG /app/mysql/log
COPY my.cnf /etc/my.cnf
RUN apk update \
    && mkdir -p /run/mysqld \
    && apk add --no-cache mysql mysql-client \
    && rm -rf /var/cache/apk/*

# Update kafka-eagle config & log4j
ENV KE_PORT 8999

RUN chmod +x "$KE_HOME"/bin/ke.sh
RUN mkdir -p ${MYSQL_LOG} \
    && mkdir -p ${KE_LOG}

VOLUME ["/var/lib/mysql", "/app/mysql/log", "/app/ke/log", "/hadoop/kafka-eagle/kms/logs"]
EXPOSE 8999 3306

# start mysql & ke.sh
WORKDIR /app/mysql

COPY startup.sh ./startup.sh
RUN chmod +x ./startup.sh

ENTRYPOINT ["/app/mysql/startup.sh"]
`
