### ISSUE TITLE
Get kafka consumer has error

### ISSUE THREAD

**Issue by zsjohny** [smartloli/kafka-eagle#55]
[2018-02-01 17:40:37] Mx4jServiceImpl.http-nio-8999-exec-13 - ERROR - JMX service url[XXXX.XXXX.XX:1571] create has error,msg is Connection refused to host: XXXX.XXXX.XX; nested exception is: 
        java.net.ConnectException: Connection refused (Connection refused)

kafka:  FROM wurstmeister/kafka:0.8.2.2

already  use the config  but not work
vi kafka-server-start.sh
...
```
if [ "x$KAFKA_HEAP_OPTS" = "x" ]; then
    export KAFKA_HEAP_OPTS="-server -Xms2G -Xmx2G -XX:PermSize=128m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:ParallelGCThreads=8 -XX:ConcGCThreads=5 -XX:InitiatingHeapOccupancyPercent=70"
    export JMX_PORT="9999"
    #export KAFKA_HEAP_OPTS="-Xmx1G -Xms1G"
fi
```
@smartloli

**Comment by kevinmiao** [comment]
do you fix it ?
