### ISSUE TITLE
when using sasl, the ipc monitor often interrupt

### ISSUE THREAD

**Issue by captainzmc** [smartloli/kafka-eagle#57]
This should be a bug. I found in class org.smartloli.kafka.eagle.core.ipc.KafkaOffsetGetter the function startOffsetSaslListener without try catch. So when there is a problem,the monitor will interrupt. I have fix this in my local environment. Here‘s  my code，hope merge to master:

`private static synchronized void startOffsetSaslListener(
			String clusterAlias, KafkaConsumer<String, String> consumer) {

		consumer.subscribe(Arrays.asList(Topic.GroupMetadataTopicName()));
		boolean flag = true;
		while (flag) {
			try {
				ConsumerRecords<String, String> records = consumer.poll(1000);
				for (ConsumerRecord<String, String> record : records) {
					if (record != null && record.value() != null) {
						Object offsetKey = GroupMetadataManager
								.readMessageKey(ByteBuffer.wrap(record.key()
										.getBytes()));
						if (offsetKey instanceof OffsetKey) {
							GroupTopicPartition commitKey = ((OffsetKey) offsetKey)
									.key();
							if (commitKey.topicPartition().topic()
									.equals(Topic.GroupMetadataTopicName())) {
								continue;
							}
							OffsetAndMetadata commitValue = GroupMetadataManager
									.readOffsetMessageValue(ByteBuffer
											.wrap(record.value().getBytes()));
							if (multiKafkaConsumerOffsets
									.containsKey(clusterAlias)) {
								multiKafkaConsumerOffsets.get(clusterAlias)
										.put(commitKey, commitValue);
							} else {
								Map<GroupTopicPartition, OffsetAndMetadata> kafkaConsumerOffsets = new ConcurrentHashMap<>();
								kafkaConsumerOffsets
										.put(commitKey, commitValue);
								multiKafkaConsumerOffsets.put(clusterAlias,
										kafkaConsumerOffsets);
							}
						} else {
							LOG.info("Consumer group[" + offsetKey.toString()
									+ "] thread has shutdown.");
						}
					}
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}`

**Comment by smartloli** [comment]
@captainzmc Thank you very much for your feedback. The repair code has been merged with the master version. See it in detail [commit log](https://github.com/smartloli/kafka-eagle/commit/6b2ffe191c348db668b9277de49acbc7aada0ba5).
