### ISSUE TITLE
Typo: java.sql.SQLException: path to '/hadoop/kafka-egale/db/ke.db'

### ISSUE THREAD

**Issue by Paw2Pom** [smartloli/kafka-eagle#58]
![screen shot 2018-02-02 at 11 10 13 am](https://user-images.githubusercontent.com/21134942/35714802-c587c088-0809-11e8-86c0-7fb7b73527dd.png)

**Comment by smartloli** [comment]
@Paw2Pom One is the configuration in the development environment, and the other is the deployment template on the production.

**Comment by Paw2Pom** [comment]
sorry so its not an error typo?

**Comment by smartloli** [comment]
@Paw2Pom Check your ```/hadoop/kafka-egale/db/ke.db``` has existed.

**Comment by Paw2Pom** [comment]
I just tried again. 1.2.0 works perfect, but 1.2.1 has the same error.

**Comment by smartloli** [comment]
@Paw2Pom If you install ```kafka-eagle``` in ```/hadoop/kafka-eagle```. Then you must be create a ``` /hadoop/kafka-egale/db/ ``` path.
Else, you can parse error logs information.
