### ISSUE TITLE
关于 Metrics && Trend 建议

### ISSUE THREAD

**Issue by saup007** [smartloli/kafka-eagle#60]
1、Metrics
现在 Metrics 都是关于整个 Kafka Cluster 的，**是否可以包含每个 borker 和每个 Topic**。
kafka manager 是包含 每个 broker 的Metrics，还有关于每个 Topic 的Metrics。

<img width="1163" alt="111" src="https://user-images.githubusercontent.com/1343717/36849696-a5398d9c-1d9f-11e8-9cb7-52688aae2718.png">

<img width="460" alt="222" src="https://user-images.githubusercontent.com/1343717/36849729-bfe2999a-1d9f-11e8-97f3-4cacc664c21b.png">

2、Trend
是否可配置采集周期，默认是 1 小时，数据记录到 MySQL，我可以通过脚本去定时清理历史数据。
是否可以查看每个 Topic 的历史消息曲线，现在是通过这个方式查看的，只能看当前 broker 的
https://www.robustperception.io/monitoring-kafka-with-prometheus/

<img width="1200"  src="https://www.robustperception.io/wp-content/uploads/2016/10/Screenshot-231016-211712.png">

**Comment by zoumm** [comment]
感觉这个提议挺好的，楼主赶紧添加哦

**Comment by smartloli** [comment]
@saup007 
Thank you very much. I'll optimize it with the feedback advice.
