### ISSUE TITLE
kafka.eagle.sasl.enable=true无法解析kafka 数据

### ISSUE THREAD

**Issue by AndrewChen2013** [smartloli/kafka-eagle#78]
![image](https://user-images.githubusercontent.com/2252117/40827034-0ea60056-65af-11e8-8644-ee6fdbe1285a.png)

**Comment by AndrewChen2013** [comment]
上面是我改过的

**Comment by smartloli** [comment]
@AndrewChen2013 You can give detailed JSON data to see why it can not be resolved.

**Comment by AndrewChen2013** [comment]
几个问题一遍问你了
1、多kafka集群是该如何配置？
2、是否能同时支持zk offset 和kafka自身管理偏移量的？
3、lag值是不是用图形显示更好一些？

**Comment by smartloli** [comment]
@AndrewChen2013 
#### 1. Multiple clusters:
For example, if you have two clusters, first set aliases, and then set the corresponding Zookeeper addresses for each alias.
```
kafka.eagle.zk.cluster.alias=cluster1,cluster2
cluster1.zk.list=dn1:2181,dn2:2181,dn3:2181
cluster2.zk.list=tn1:2181,tn2:2181,tn3:2181
```

#### 2.  ZK or Kafka
Sorry. ZK and Kafka can not be supported at the same time, either in Kafka or in ZK.

#### 3. Lag to charts
This is a good idea. I will consider adding this function later.
