### ISSUE TITLE
zk连接错误

### ISSUE THREAD

**Issue by MeepoMeepo** [smartloli/kafka-eagle#8]
你好，配置是
![image](https://cloud.githubusercontent.com/assets/23380553/26095172/507e7468-3a4f-11e7-9ef9-68988b9e06df.png)

系统log
![image](https://cloud.githubusercontent.com/assets/23380553/26095271/941b8daa-3a4f-11e7-8f55-1e041472ee4d.png)

**Comment by smartloli** [comment]
@MeepoMeepo  Make sure the zookeeper address is set properly .
