### ISSUE TITLE
最新版本的bug

### ISSUE THREAD

**Issue by javaChain** [smartloli/kafka-eagle#84]
1. 首先启动的时候说是用默认的存储，但是下载的包db文件夹下没有ke.db文件
# Default use sqlite to store data
kafka.eagle.driver=org.sqlite.JDBC
# It is important to note that the '/hadoop/kafka-eagle/db' path must exist.
kafka.eagle.url=jdbc:sqlite:/hadoop/kafka-eagle/db/ke.db
2.接上面1问题，使用sqlite需要安装其他环境吗？
3. 然后我想使用mysql作为存储介质，但是我编辑配置文件的时候，默认是没有mysql的配置文件，然后我就从官网的文档copy了一下mysql的配置，结果启动还是报错。我的mysql链接配置也没有问题，我能访问，但是程序启动就报错说链接异常，我在想最新版本的是移除了对MySQL的支持了吗？配置文件都给移除了。

**Comment by smartloli** [comment]
@javaChain 
#### 1. Sqlite
If you want to use sqlite , you must be set ```kafka.eagle.url``` property, and you need to ensure that the path of the ```ke.db``` exists. Such as:
Your ```$KE_HOME``` is ```/data/hadoop/kafka-eagle```, then you can set ```kafka.eagle.url=/data/hadoop/kafka-eagle/db/ke.db```

#### 2. MySQL
If you want to use mysql , you can set like this:
```
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://127.0.0.1:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=smartloli
```

**Comment by javaChain** [comment]
![错误](http://ore1lqh59.bkt.clouddn.com/18-6-13/44684455.jpg)
![配置文件](http://ore1lqh59.bkt.clouddn.com/18-6-13/74442492.jpg)
springmvc配置了这个属性，但是配置文件没有，也不知道怎么配置。

**Comment by javaChain** [comment]
@smartloli ![](http://ore1lqh59.bkt.clouddn.com/18-6-13/11647175.jpg)
![查看ke_console.log](http://ore1lqh59.bkt.clouddn.com/18-6-13/13017586.jpg)
感觉我已经花费了至少6个小时入门了，我再换个工具吧。

**Comment by javaChain** [comment]
虽然知道做一个东西不易，但是这个坑踩的我有点蒙，首先我配置的kafka.eagle.url=/data/hadoop/kafka-eagle/db/ke.db这个东西是不是以sqlite作为数据库？如果不是，那么手机的数据存储在哪，如果是，那么我Linux都没有安装sqlite数据库。快速入门也没有稍微介绍一下工作流程，这个配置文件全靠蒙，猜逻辑。
革命尚未成功，gay佬love萝莉！

**Comment by javaChain** [comment]
然后我接着修改配置文件，改为MySQL的方式，🙄
配置文件![](http://ore1lqh59.bkt.clouddn.com/18-6-13/66450741.jpg)
ke_console.log![](http://ore1lqh59.bkt.clouddn.com/18-6-13/29026044.jpg)
idea链接mysql ![](http://ore1lqh59.bkt.clouddn.com/18-6-13/51712986.jpg)
idea链接MySQL的连接串和配置文件的连接串是一样的。报错就是连接不上。good job,这些我就没有理由回头了，虽然我还可以编译源码然后查看原因修复，但是我需要的只是一个工具，查看一下kafka的消息，oh no！

**Comment by smartloli** [comment]
@javaChain 
If you use sqlite , such as  property:
```
kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/hadoop/kafka-eagle/db/ke.db
kafka.eagle.username=root
kafka.eagle.password=smartloli
```
Wiki: https://ke.smartloli.org/2.Install/2.Installing.html

**Comment by javaChain** [comment]
@smartloli 
this is my sqlite config
```kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/usr/local/kafka-eagle/db/ke.db
kafka.eagle.username=
kafka.eagle.password=
```

**Comment by smartloli** [comment]
@javaChain 
Driver must be set it.
```
kafka.eagle.driver=org.sqlite.JDBC
```

**Comment by smartloli** [comment]
Anyway, this system is so easy. Read wiki (http://ke.smartloli.org) and set a bit of information. Such as ```zookeeper``` address & ```sqlite``` db file store path or ```mysql``` connection address. That's it.
Then, run script ```ke.sh start```.

**Comment by javaChain** [comment]
So terrible! I don't want to use it .question also is a  question , if you use last version tar.gz you  will be  find question .see you

**Comment by WangDaQi7** [comment]
./ke.sh: line 97: usr/local/kafkaeagle/bin/ke.pid: No such file or directory

**Comment by mainlove** [comment]
Is is import to give docker version
