### ISSUE TITLE
eagle不能登录进去

### ISSUE THREAD

**Issue by franplk** [smartloli/kafka-eagle#85]
我启动后，密码提示：Account or password is error
配置文件：
kafka.eagle.driver=org.sqlite.JDBC
kafka.eagle.url=jdbc:sqlite:/app/software/kafka-eagle/db/ke.db
kafka.eagle.username=admin
kafka.eagle.password=admin123

**Comment by cnfree0355** [comment]
默认用户名是 admin 123456

**Comment by smartloli** [comment]
@franplk Well done, @cnfree0355 It's right.
Kafka Eagle Login information(Default Administrator):
```
Accout: admin
Password: 123456
```
Anyway,```kafka.eagle.username``` & ```kafka.eagle.password``` is database username & password, it's not system login accout & passowrd.

**Comment by franplk** [comment]
OK, I understand. Thanks you two. But I want to know where and how the login account 
was configured, the coding style or the sqlite db style.

**Comment by smartloli** [comment]
You can login kafka eagle, then reset administrator password.

**Comment by franplk** [comment]
@smartloli Thanks
