### ISSUE TITLE
why can not connect to kafka after set SASL_PLAINTEXT and acls

### ISSUE THREAD

**Issue by cyhrosefer** [smartloli/kafka-eagle#87]
only list topics ,  can not get broker info and others, how to add jaas client configuration

**Comment by smartloli** [comment]
@cyhrosefer 
Please read operation manual, [https://ke.smartloli.org/](https://ke.smartloli.org/)
```
# kafka sasl authenticate, current support SASL_PLAINTEXT
kafka.eagle.sasl.enable=true
kafka.eagle.sasl.protocol=SASL_PLAINTEXT
kafka.eagle.sasl.mechanism=PLAIN
kafka.eagle.sasl.client=<kafka_client_jaas.conf file path>
```

**Comment by cyhrosefer** [comment]
@smartloli ,thanks you reply,    still be abnormal,     when click Topic-> List -> select one topic,  then can not display detail info.

**Comment by smartloli** [comment]
@cyhrosefer 
What kind of SASL protocol do you use.
