### ISSUE TITLE
Kafka Query SQL error

### ISSUE THREAD

**Issue by cyhrosefer** [smartloli/kafka-eagle#88]
the sql is  SELECT "partition","offset","msg" FROM "zhou" WHERE "partition" IN (0) limit 10

Fetcher.http-nio-8048-exec-18 - INFO  - [Consumer clientId=consumer-4, groupId=kafka.eagle.system.group] Fetch offset 0 is out of range for partition zhou-0, resetting offset

kafka version is kafka_2.12-1.0.0

**Comment by smartloli** [comment]
@cyhrosefer 
Hi, try it like this
```
# If offset is out of range occurs, enable this property -- Only suitable for kafka sql
kafka.eagle.sql.fix.error=false
```
