### ISSUE TITLE
kafka-eagle启动没报错（1.2.3），netstat -an|grep 8048显示没启动

### ISSUE THREAD

**Issue by zhangyingjie1984** [smartloli/kafka-eagle#89]
*******************************************************************
* Kafka Eagle system monitor port successful... 
*******************************************************************
[2018-07-06 17:07:24] INFO: Status Code[0]
[2018-07-06 17:07:24] INFO: [Job done!]
Welcome to
    __ __    ___     ____    __ __    ___            ______    ___    ______    __     ______
   / //_/   /   |   / __/   / //_/   /   |          / ____/   /   |  / ____/   / /    / ____/
  / ,<     / /| |  / /_    / ,<     / /| |         / __/     / /| | / / __    / /    / __/   
 / /| |   / ___ | / __/   / /| |   / ___ |        / /___    / ___ |/ /_/ /   / /___ / /___   
/_/ |_|  /_/  |_|/_/     /_/ |_|  /_/  |_|       /_____/   /_/  |_|\____/   /_____//_____/   
                                                                                             

Version 1.2.3
*******************************************************************
* Kafka Eagle Service has started success.
* Welcome, Now you can visit 'http://<your_host_or_ip>:port/ke'
* Account:admin ,Password:123456
*******************************************************************
* <Usage> ke.sh [start|status|stop|restart|stats] </Usage>
* <Usage> http://ke.smartloli.org/ </Usage>
*******************************************************************
[root@app bin]# netstat -an|grep 8048
[root@app bin]# 
部分配置：
kafka.eagle.zk.cluster.alias=cluster1
cluster1.zk.list=localhost:2181
kafka.eagle.webui.port=8048
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://127.0.0.1:3306/ke?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
kafka.eagle.username=root
kafka.eagle.password=123456

**Comment by smartloli** [comment]
@zhangyingjie1984 
Please exec ```less $KE_HOME/logs/ke_console.out``` command, then whether has something error ?
