### ISSUE TITLE
Why my kafka eagle cannot connect to mysql?

### ISSUE THREAD

**Issue by KingWang93** [smartloli/kafka-eagle#90]
[2018-07-11 21:51:48] DruidDataSource.Druid-ConnectionPool-Create-287137443 - ERROR - create connection error, url: jdbc:mysql://localhost:3306/ke, errorCode 0, state 08001
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
_____________________________________________________________________________________________________________
mysql version 8
windows system
kafka eagle version:1.2.3
_____________________________________________________________________________________________________________
here is my configuration:
######################################

kafka jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://localhost:3306/ke
kafka.eagle.username=root
kafka.eagle.password=mypassword

**Comment by KingWang93** [comment]
[2018-07-11 21:51:48] DruidDataSource.Druid-ConnectionPool-Create-287137443 - ERROR - create connection error, url: jdbc:mysql://localhost:3306/ke, errorCode 0, state 08001
 com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server.
-----------------
mysql version 8
windows system
kafka eagle version:1.2.3
----------------
here is my configuration:
######################################
# kafka jdbc driver address
######################################
kafka.eagle.driver=com.mysql.jdbc.Driver
kafka.eagle.url=jdbc:mysql://localhost:3306/ke
kafka.eagle.username=root
kafka.eagle.password=mypassword

**Comment by smartloli** [comment]
@KingWang93 Whether ```localhost``` has mapper such as ```127.0.0.1```, maybe you can use ```127.0.0.1``` replace to ```localhost```.

**Comment by zishenlaowanjia** [comment]
@smartloli  
I also configured mysql, but it only creates ke database, why is there no table under ke database?

**Comment by smartloli** [comment]
If you use mysql has something error, also you can use default ```sqlite``` database.
