### ISSUE TITLE
Kafka同时启动SASAL和普通PLAINTEXT通信地址时启动eagle后系统错误

### ISSUE THREAD

**Issue by yourcaptain** [smartloli/kafka-eagle#93]
版本：kafka eagle 1.2.3

再现方式：
1、Kafka eagle开启sasl认证，
2、kafka的advertised.listeners同时配置常规的与安全的两个地址，即 
      PLAINTEXT://localhost:9002,SASL_PLAINTEXT://localhost:9003

然后启动kafka eagle，error.log中会出现：
ERROR - Get kafka consumer has error, msg is No resolvable bootstrap urls given in bootstrap.servers 
ERROR - For input string “9004”,”SASL_PLAINTEX”

**Comment by smartloli** [comment]
@yourcaptain 
Do you use the old version of Kafka API ？Something use ```metadata.broker.list``` property ？
