### ISSUE TITLE
Build fails from command line: ./build.sh

### ISSUE THREAD

**Issue by anam-dodhy** [smartloli/kafka-eagle#96]
When I try to build the project from the command line (without using any IDE), 
./build.sh
I get the following error:

kafka-eagle/kafka-eagle-common/src/main/java/org/smartloli/kafka/eagle/common/protocol/KafkaSqlInfo.java:[34,57] diamond operator is not supported in -source 1.5
[ERROR]   (use -source 7 or higher to enable diamond operator)

I believe the fix is to specify following property in the pom.xml file of the "kafka-eagle-common" project:
```
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
```

**Comment by smartloli** [comment]
@anam-dodhy Hi, you can set ``` settings.xml``` file, like this:
```
<profile>
      <id>jdk-1.7</id>
      <activation>
        <activeByDefault>true</activeByDefault>
        <jdk>1.7</jdk>
      </activation>
      <properties>
        <maven.compiler.source>1.7</maven.compiler.source>
        <maven.compiler.target>1.7</maven.compiler.target>
        <maven.compiler.compilerVersion>1.7</maven.compiler.compilerVersion>
      </properties>
</profile>
```
