### ISSUE TITLE
ubuntu 设置环境变量老是出错 说环境变量配置错误

### ISSUE THREAD

**Issue by Messilimeng** [smartloli/kafka-eagle#97]
Error: The KE_HOME environment variable is not defined correctly.
[2018-08-06 23:39:24] Error: This environment variable is needed to run this program.

**Comment by Messilimeng** [comment]
![image](https://user-images.githubusercontent.com/12272166/43768154-41c52388-9a69-11e8-9ad5-8b94405296c6.png)

**Comment by smartloli** [comment]
@Messilimeng KE_HOME env is not KAFKA_HOME, you can set like this
```
export KE_HOME=/hadoop/kafka-eagle
export PATH=$PATH:$KE_HOME/bin
```

**Comment by Messilimeng** [comment]
@smartloli 可以加个qq 吗  我急用

**Comment by Messilimeng** [comment]
我并没有用KAFKA_HOME 就是你那个文件的目录

**Comment by Messilimeng** [comment]
![image](https://user-images.githubusercontent.com/12272166/43875198-2f5daa58-9bc2-11e8-8b32-03e42c976ad5.png)

**Comment by smartloli** [comment]
@Messilimeng Sure, QQ Group: 424769183

**Comment by Messilimeng** [comment]
@smartloli 我加了好几遍了 都没有通过

**Comment by smartloli** [comment]
@Messilimeng Set env like this:
```
export KE_HOME=/hadoop/kafka-eagle
export JAVA_HOME=/usr/lib/jdk8
export PATH=$PATH:$KE_HOME/bin:$JAVA_HOME/bin
```
Save & exit ```~/.bash_profile``` or ```/etc/profile```, then run ```source ~/.bash_profile``` or ```source /etc/profile``` command.

**Comment by Messilimeng** [comment]
qq群 不给加了啊？

**Comment by Messilimeng** [comment]
JAVA_HOME 我是系统apt 安装的 不用再加了吧

**Comment by smartloli** [comment]
@Messilimeng Please give me you QQ No .

**Comment by Messilimeng** [comment]
@smartloli 536403003
